/**
 * /api/v1/companies/{companyId}/salary-runs/{id}/lines/{lineId}
 *
 * PATCH  : update a payslip line (amount, description, quantity, ...) in a
 *          DRAFT run.
 * DELETE : remove a payslip line from a DRAFT run.
 *
 * Both verify the line belongs to the given run (via its
 * salary_run_employees row) so a lineId from another run 404s instead of
 * silently mutating.
 */

import { z } from 'zod'
import { ok, noContent } from '@/lib/api/v1/response'
import { dryRunPreview } from '@/lib/api/v1/dry-run'
import { registerEndpoint, dataEnvelope, NoBodyResponse } from '@/lib/api/v1/registry'
import { withApiV1 } from '@/lib/api/v1/with-api-v1'
import { v1ErrorResponseFromCode, v1ValidationError } from '@/lib/api/v1/errors'
import { readV1JsonBody } from '@/lib/api/v1/body'
import { UpdateSalaryLineItemSchema } from '@/lib/api/schemas'
import { updatePayslipLine, deletePayslipLine } from '@/lib/salary/payslip-lines'

const LineItemResponse = z.object({
  salary_line_item_id: z.string().uuid(),
  salary_run_employee_id: z.string().uuid(),
  item_type: z.string(),
  description: z.string(),
  quantity: z.number().nullable(),
  unit_price: z.number().nullable(),
  amount: z.number(),
  is_taxable: z.boolean(),
  is_avgift_basis: z.boolean(),
  is_vacation_basis: z.boolean(),
  is_gross_deduction: z.boolean(),
  is_net_deduction: z.boolean(),
  account_number: z.string().nullable(),
  sort_order: z.number(),
  one_off_tax_percent: z.number().nullable().optional(),
  vacation_category: z.string().nullable().optional(),
  vacation_saved_year: z.string().nullable().optional(),
})

registerEndpoint({
  operation: 'salary-runs.lines.update',
  method: 'PATCH',
  path: '/api/v1/companies/:companyId/salary-runs/:id/lines/:lineId',
  summary: 'Update a payslip line in a draft salary run.',
  description:
    'Updates fields on a salary_line_items row (amount, description, quantity, unit_price, flags, account_number, one_off_tax_percent, vacation_category, vacation_saved_year) while the run is a draft. Amounts are rounded to whole öre. one_off_tax_percent: null removes the engångsskatt and returns the line to table taxation. vacation_category: null returns a vacation line to this year\'s paid days.',
  useWhen:
    'You spotted a wrong amount or description on a manual line before calculating: fix it in place instead of delete + recreate.',
  doNotUseFor:
    'Post-calculation tax/avgifter adjustments (review-stage overrides are not on v1). Engine-derived lines (absence/benefits): they are regenerated by :calculate, so edits are overwritten.',
  pitfalls: [
    'Draft-only: 400 SALARY_RUN_LINE_NOT_DRAFT once the run has advanced.',
    'A lineId that belongs to a different run returns 404 SALARY_LINE_NOT_FOUND.',
    'Line edits do not recompute tax or totals: call POST /salary-runs/{id}/calculate afterwards.',
    'A line the calculation owns (absence, Övertid 50/100 % and OB rows, förmån and recurring-line rows, the engine\'s semesterersättning and öresavrundning rows), or a patch changing item_type to such a type, returns 400 SALARY_LINE_CALCULATED: the next :calculate would overwrite the edit. Change the source (absence, worked hours, the förmån, the recurring line) instead.',
    'The row is validated as it reads after the patch: flipping is_net_deduction or is_gross_deduction on, setting is_taxable false, or making the amount non-positive on a line that carries one_off_tax_percent is refused with 400 VALIDATION_ERROR; clear the percentage (null) in the same call.',
    'vacation_category (paid, extra_paid, saved, unpaid, advance) is only valid while item_type is vacation, and vacation_saved_year only with category saved; a patch that breaks either is refused with 400 VALIDATION_ERROR.',
  ],
  example: {
    request: { amount: 5500 },
    response: {
      data: { salary_line_item_id: 'sli_31c9…', amount: 5500 },
      meta: { request_id: 'req_…', api_version: '2026-05-12' },
    },
  },
  scope: 'payroll:write',
  risk: 'low',
  idempotent: true,
  reversible: true,
  dryRunSupported: true,
  request: { body: UpdateSalaryLineItemSchema },
  response: { success: dataEnvelope(LineItemResponse) },
})

function parsePathIds(id: string, lineId: string):
  | { ok: true; runId: string; lineId: string }
  | { ok: false; field: string } {
  const runParse = z.string().uuid().safeParse(id)
  if (!runParse.success) return { ok: false, field: 'id' }
  const lineParse = z.string().uuid().safeParse(lineId)
  if (!lineParse.success) return { ok: false, field: 'lineId' }
  return { ok: true, runId: runParse.data, lineId: lineParse.data }
}

function toResponsePayload(row: Record<string, unknown>): Record<string, unknown> {
  const { id, company_id: _companyId, created_at: _c, updated_at: _u, ...rest } = row as {
    id: string
    company_id?: string
    created_at?: string
    updated_at?: string
  } & Record<string, unknown>
  return { salary_line_item_id: id, ...rest }
}

export const PATCH = withApiV1<{ params: Promise<{ companyId: string; id: string; lineId: string }> }>(
  'salary-runs.lines.update',
  async (request, ctx, params) => {
    const { id, lineId } = await params.params
    const ids = parsePathIds(id, lineId)
    if (!ids.ok) {
      return v1ErrorResponseFromCode('VALIDATION_ERROR', ctx.log, {
        requestId: ctx.requestId,
        details: { field: ids.field, message: 'Path ids must be UUIDs.' },
      })
    }

    const rawBodyResult = await readV1JsonBody(request, ctx)
    if (!rawBodyResult.ok) return rawBodyResult.response
    const rawBody = rawBodyResult.body

    const parsed = UpdateSalaryLineItemSchema.safeParse(rawBody)
    if (!parsed.success) return v1ValidationError(ctx, parsed.error)

    // Zod .default() materializes flags the caller never sent; strip anything
    // not explicitly present so a PATCH can't silently reset flags. (Same
    // explicit-keys defense as the salary-runs PATCH.)
    const POLLUTING_KEYS = new Set(['__proto__', 'constructor', 'prototype'])
    const rawKeys =
      typeof rawBody === 'object' && rawBody !== null && !Array.isArray(rawBody)
        ? Object.keys(rawBody).filter((k) => !POLLUTING_KEYS.has(k))
        : []
    const patch: Record<string, unknown> = {}
    for (const [key, value] of Object.entries(parsed.data) as Array<[string, unknown]>) {
      if (rawKeys.includes(key) && value !== undefined) {
        patch[key] = value
      }
    }
    if (Object.keys(patch).length === 0) {
      return v1ErrorResponseFromCode('VALIDATION_ERROR', ctx.log, {
        requestId: ctx.requestId,
        details: { field: 'body', message: 'At least one updatable field is required.' },
      })
    }

    const result = await updatePayslipLine(ctx.supabase, {
      companyId: ctx.companyId!,
      salaryRunId: ids.runId,
      lineId: ids.lineId,
      patch,
      dryRun: ctx.dryRun,
    })

    if (!result.ok) {
      return v1ErrorResponseFromCode(result.code, ctx.log, {
        requestId: ctx.requestId,
        details: result.details,
      })
    }

    const payload = toResponsePayload(result.data as unknown as Record<string, unknown>)
    if (ctx.dryRun) {
      return dryRunPreview(payload, { requestId: ctx.requestId, log: ctx.log })
    }
    return ok(payload, { requestId: ctx.requestId })
  },
  { requireIdempotencyKey: true },
)

registerEndpoint({
  operation: 'salary-runs.lines.delete',
  method: 'DELETE',
  path: '/api/v1/companies/:companyId/salary-runs/:id/lines/:lineId',
  summary: 'Delete a payslip line from a draft salary run.',
  description:
    'Removes a salary_line_items row while the run is a draft. Engine-derived lines (absence, benefits) reappear on the next :calculate; delete the underlying absence/benefit record instead.',
  useWhen:
    'A manual line (bonus, deduction) was added by mistake and the run has not been calculated/advanced yet.',
  doNotUseFor:
    'Removing an employee from the run entirely: DELETE /salary-runs/{id}/employees/{employeeId}. Suppressing engine-derived lines: fix the source data (absence days, benefits).',
  pitfalls: [
    'Draft-only: 400 SALARY_RUN_LINE_NOT_DRAFT once the run has advanced.',
    'A line the calculation owns (absence, Övertid 50/100 % and OB rows, förmån and recurring-line rows, the engine\'s semesterersättning and öresavrundning rows) returns 400 SALARY_LINE_CALCULATED: :calculate would bring it back. Change the source (absence, worked hours, the förmån, the recurring line) instead.',
  ],
  example: { response: { data: null } },
  scope: 'payroll:write',
  risk: 'low',
  idempotent: true,
  reversible: false,
  dryRunSupported: true,
  response: { success: NoBodyResponse },
})

export const DELETE = withApiV1<{ params: Promise<{ companyId: string; id: string; lineId: string }> }>(
  'salary-runs.lines.delete',
  async (_request, ctx, params) => {
    const { id, lineId } = await params.params
    const ids = parsePathIds(id, lineId)
    if (!ids.ok) {
      return v1ErrorResponseFromCode('VALIDATION_ERROR', ctx.log, {
        requestId: ctx.requestId,
        details: { field: ids.field, message: 'Path ids must be UUIDs.' },
      })
    }

    const result = await deletePayslipLine(ctx.supabase, {
      companyId: ctx.companyId!,
      salaryRunId: ids.runId,
      lineId: ids.lineId,
      dryRun: ctx.dryRun,
    })

    if (!result.ok) {
      return v1ErrorResponseFromCode(result.code, ctx.log, {
        requestId: ctx.requestId,
        details: result.details,
      })
    }

    if (ctx.dryRun) {
      return dryRunPreview(result.data, { requestId: ctx.requestId, log: ctx.log })
    }
    return noContent({ requestId: ctx.requestId })
  },
  { requireIdempotencyKey: true },
)
