import type { BASReferenceAccount } from '../bas-reference'

export const CLASS_3_ACCOUNTS: BASReferenceAccount[] = [
  {
    account_number: '3000',
    account_name: 'Försäljning inom Sverige',
    account_class: 3,
    account_group: '30',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Försäljning inom Sverige',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3001',
    account_name: 'Försäljning inom Sverige, 25 % moms',
    account_class: 3,
    account_group: '30',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Intäkter från försäljning med 25% moms - den vanligaste intäktsraden för svenska företag.',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3002',
    account_name: 'Försäljning inom Sverige, 12 % moms',
    account_class: 3,
    account_group: '30',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Intäkter från försäljning med 12% moms, t.ex. livsmedel och restaurang.',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3003',
    account_name: 'Försäljning inom Sverige, 6 % moms',
    account_class: 3,
    account_group: '30',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Intäkter från försäljning med 6% moms, t.ex. böcker, tidningar och kollektivtrafik.',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3004',
    account_name: 'Försäljning inom Sverige, momsfri',
    account_class: 3,
    account_group: '30',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Intäkter från försäljning som är undantagen från moms, t.ex. sjukvård och utbildning.',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3100',
    account_name: 'Försäljning av varor utanför Sverige',
    account_class: 3,
    account_group: '31',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Försäljning av varor utanfor Sverige, gruppkonto.',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3105',
    account_name: 'Försäljning varor till land utanför EU',
    account_class: 3,
    account_group: '31',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Intäkter från försäljning av varor till kunder utanfor EU. Momsfritt.',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3106',
    account_name: 'Försäljning varor till annat EU-land, momspliktig',
    account_class: 3,
    account_group: '31',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Försäljning varor till annat EU-land, momspliktig',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3108',
    account_name: 'Försäljning varor till annat EU-land, momsfri',
    account_class: 3,
    account_group: '31',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Intäkter från försäljning av varor till momsregistrerade företag i andra EU-länder.',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3200',
    account_name: 'Försäljning VMB och omvänd moms',
    account_class: 3,
    account_group: '32',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Försäljning VMB och omvänd moms',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3211',
    account_name: 'Försäljning positiv VMB 25 %',
    account_class: 3,
    account_group: '32',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Försäljning positiv VMB 25 %',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3212',
    account_name: 'Försäljning negativ VMB 25 %',
    account_class: 3,
    account_group: '32',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Försäljning negativ VMB 25 %',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3231',
    account_name: 'Försäljning inom byggsektorn, omvänd betalningsskyldighet moms',
    account_class: 3,
    account_group: '32',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Försäljning inom byggsektorn, omvänd betalningsskyldighet moms',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3300',
    account_name: 'Försäljning av tjänster utanför Sverige',
    account_class: 3,
    account_group: '33',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Försäljning av tjänster utanför Sverige',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3305',
    account_name: 'Försäljning tjänster till land utanför EU',
    account_class: 3,
    account_group: '33',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Intäkter från försäljning av tjänster till kunder utanfor EU. Momsfritt.',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3308',
    account_name: 'Försäljning tjänster till annat EU-land',
    account_class: 3,
    account_group: '33',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Intäkter från försäljning av tjänster till företag i andra EU-länder. Omvänd skattskyldighet.',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3400',
    account_name: 'Försäljning, egna uttag',
    account_class: 3,
    account_group: '34',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Försäljning, egna uttag',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3401',
    account_name: 'Egna uttag momspliktiga, 25 %',
    account_class: 3,
    account_group: '34',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Egna uttag momspliktiga, 25 %',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3402',
    account_name: 'Egna uttag momspliktiga, 12 %',
    account_class: 3,
    account_group: '34',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Egna uttag momspliktiga, 12 %',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3403',
    account_name: 'Egna uttag momspliktiga, 6 %',
    account_class: 3,
    account_group: '34',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Egna uttag momspliktiga, 6 %',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3404',
    account_name: 'Egna uttag, momsfria',
    account_class: 3,
    account_group: '34',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Egna uttag, momsfria',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3500',
    account_name: 'Fakturerade kostnader (gruppkonto)',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Fakturerade kostnader (gruppkonto)',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3510',
    account_name: 'Fakturerat emballage',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Kostnader för emballage som vidarefaktureras till kunder.',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3511',
    account_name: 'Fakturerat emballage',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Fakturerat emballage',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3518',
    account_name: 'Returnerat emballage',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Returnerat emballage',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3520',
    account_name: 'Fakturerade frakter',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Fakturerade frakter',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3521',
    account_name: 'Fakturerade frakter, EU-land',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Fraktkostnader som vidarefaktureras till kunder i andra EU-länder.',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3522',
    account_name: 'Fakturerade frakter, export',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Fraktkostnader som vidarefaktureras till kunder utanfor EU. Momsfritt.',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3530',
    account_name: 'Fakturerade tull- och speditionskostnader m.m.',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Fakturerade tull- och speditionskostnader m.m.',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3540',
    account_name: 'Faktureringsavgifter',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Faktureringsavgifter',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3541',
    account_name: 'Faktureringsavgifter, EU-land',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Faktureringsavgifter, EU-land',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3542',
    account_name: 'Faktureringsavgifter, export',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Faktureringsavgifter, export',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3550',
    account_name: 'Fakturerade resekostnader',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Fakturerade resekostnader',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3560',
    account_name: 'Fakturerade kostnader till koncernföretag',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Fakturerade kostnader till koncernföretag',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3561',
    account_name: 'Fakturerade kostnader till moderföretag',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Fakturerade kostnader till moderföretag',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3562',
    account_name: 'Fakturerade kostnader till dotterföretag',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Fakturerade kostnader till dotterföretag',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3563',
    account_name: 'Fakturerade kostnader till andra koncernföretag',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Fakturerade kostnader till andra koncernföretag',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3570',
    account_name: 'Fakturerade kostnader till intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Fakturerade kostnader till intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3590',
    account_name: 'Övriga fakturerade kostnader',
    account_class: 3,
    account_group: '35',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Övriga fakturerade kostnader',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3600',
    account_name: 'Rörelsens sidointäkter (gruppkonto)',
    account_class: 3,
    account_group: '36',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Rörelsens sidointäkter (gruppkonto)',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3610',
    account_name: 'Försäljning av material',
    account_class: 3,
    account_group: '36',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Försäljning av material',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3611',
    account_name: 'Försäljning av råmaterial',
    account_class: 3,
    account_group: '36',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Försäljning av råmaterial',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3612',
    account_name: 'Försäljning av skrot',
    account_class: 3,
    account_group: '36',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Försäljning av skrot',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3613',
    account_name: 'Försäljning av förbrukningsmaterial',
    account_class: 3,
    account_group: '36',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Försäljning av förbrukningsmaterial',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3619',
    account_name: 'Försäljning av övrigt material',
    account_class: 3,
    account_group: '36',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Försäljning av övrigt material',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3620',
    account_name: 'Tillfällig uthyrning av personal',
    account_class: 3,
    account_group: '36',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Tillfällig uthyrning av personal',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3630',
    account_name: 'Tillfällig uthyrning av transportmedel',
    account_class: 3,
    account_group: '36',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Tillfällig uthyrning av transportmedel',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3670',
    account_name: 'Intäkter från värdepapper',
    account_class: 3,
    account_group: '36',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Intäkter från värdepapper',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3671',
    account_name: 'Försäljning av värdepapper',
    account_class: 3,
    account_group: '36',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Försäljning av värdepapper',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3672',
    account_name: 'Utdelning från värdepapper',
    account_class: 3,
    account_group: '36',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Utdelning från värdepapper',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3679',
    account_name: 'Övriga intäkter från värdepapper',
    account_class: 3,
    account_group: '36',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Övriga intäkter från värdepapper',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3680',
    account_name: 'Management fees',
    account_class: 3,
    account_group: '36',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Management fees',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3690',
    account_name: 'Övriga sidointäkter',
    account_class: 3,
    account_group: '36',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Övriga sidointäkter',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3700',
    account_name: 'Intäktskorrigeringar (gruppkonto)',
    account_class: 3,
    account_group: '37',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Intäktskorrigeringar (gruppkonto)',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3710',
    account_name: 'Ofördelade intäktsreduktioner',
    account_class: 3,
    account_group: '37',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Ofördelade intäktsreduktioner',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3730',
    account_name: 'Lämnade rabatter',
    account_class: 3,
    account_group: '37',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Lämnade rabatter',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3731',
    account_name: 'Lämnade kassarabatter',
    account_class: 3,
    account_group: '37',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Lämnade kassarabatter',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3732',
    account_name: 'Lämnade mängdrabatter',
    account_class: 3,
    account_group: '37',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Lämnade mängdrabatter',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3740',
    account_name: 'Öres- och kronutjämning',
    account_class: 3,
    account_group: '37',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Oreskillnad som uppstår vid avrundning av betalningar (oret).',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3750',
    account_name: 'Punktskatter',
    account_class: 3,
    account_group: '37',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Punktskatter',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3751',
    account_name: 'Intäktsförda punktskatter (kreditkonto)',
    account_class: 3,
    account_group: '37',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Intäktsförda punktskatter (kreditkonto)',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3752',
    account_name: 'Skuldförda punktskatter (debetkonto)',
    account_class: 3,
    account_group: '37',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Skuldförda punktskatter (debetkonto)',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3790',
    account_name: 'Övriga intäktskorrigeringar',
    account_class: 3,
    account_group: '37',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Övriga intäktskorrigeringar',
    sru_code: '7410',
    k2_excluded: false,
  },
  {
    account_number: '3800',
    account_name: 'Aktiverat arbete för egen räkning (gruppkonto)',
    account_class: 3,
    account_group: '38',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Aktiverat arbete för egen räkning (gruppkonto)',
    sru_code: '7412',
    k2_excluded: false,
  },
  {
    account_number: '3840',
    account_name: 'Aktiverat arbete (material)',
    account_class: 3,
    account_group: '38',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Aktiverat arbete (material)',
    sru_code: '7412',
    k2_excluded: false,
  },
  {
    account_number: '3850',
    account_name: 'Aktiverat arbete (omkostnader)',
    account_class: 3,
    account_group: '38',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Aktiverat arbete (omkostnader)',
    sru_code: '7412',
    k2_excluded: false,
  },
  {
    account_number: '3870',
    account_name: 'Aktiverat arbete (personal)',
    account_class: 3,
    account_group: '38',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Aktiverat arbete (personal)',
    sru_code: '7412',
    k2_excluded: false,
  },
  {
    account_number: '3900',
    account_name: 'Övriga rörelseintäkter (gruppkonto)',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Andra intäkter som inte hör till kärnverksamheten, t.ex. uthyrning av lokal.',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3910',
    account_name: 'Hyres- och arrendeintäkter',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Intäkter från uthyrning av lokaler, mark eller annan egendom.',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3911',
    account_name: 'Hyresintäkter',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Hyresintäkter',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3912',
    account_name: 'Arrendeintäkter',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Arrendeintäkter',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3913',
    account_name: 'Frivilligt momspliktiga hyresintäkter',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Frivilligt momspliktiga hyresintäkter',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3914',
    account_name: 'Övriga momspliktiga hyresintäkter',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Övriga momspliktiga hyresintäkter',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3920',
    account_name: 'Provisionsintäkter, licensintäkter och royalties',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Provisionsintäkter, licensintäkter och royalties',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3921',
    account_name: 'Provisionsintäkter',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Provisionsintäkter',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3922',
    account_name: 'Licensintäkter och royalties',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Licensintäkter och royalties',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3925',
    account_name: 'Franchiseintäkter',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Franchiseintäkter',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3940',
    account_name: 'Orealiserade negativa/positiva värdeförändringar på säkringsinstrument',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Orealiserade negativa/positiva värdeförändringar på säkringsinstrument',
    sru_code: '7413',
    k2_excluded: true,
  },
  {
    account_number: '3950',
    account_name: 'Återvunna, tidigare avskrivna kundfordringar',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återvunna, tidigare avskrivna kundfordringar',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3960',
    account_name: 'Valutakursvinster på fordringar och skulder av rörelsekaraktär',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Vinster som uppstår vid valutaväxling eller betalningar i utländsk valuta.',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3970',
    account_name: 'Vinst vid avyttring av immateriella och materiella anläggningstillgångar',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Vinst vid försäljning av anläggningstillgångar, t.ex. maskiner eller inventarier.',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3971',
    account_name: 'Vinst vid avyttring av immateriella anläggningstillgångar',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Vinst vid avyttring av immateriella anläggningstillgångar',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3972',
    account_name: 'Vinst vid avyttring av byggnader och mark',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Vinst vid avyttring av byggnader och mark',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3973',
    account_name: 'Vinst vid avyttring av maskiner och inventarier',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Vinst vid avyttring av maskiner och inventarier',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3980',
    account_name: 'Erhållna offentliga bidrag',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Erhållna offentliga bidrag',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3981',
    account_name: 'Erhållna EU-bidrag',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Erhållna EU-bidrag',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3985',
    account_name: 'Erhållna statliga bidrag',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Erhållna statliga bidrag',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3987',
    account_name: 'Erhållna kommunala bidrag',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Erhållna kommunala bidrag',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3988',
    account_name: 'Erhållna offentliga bidrag för personal',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Erhållna offentliga bidrag för personal',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3989',
    account_name: 'Övriga erhållna offentliga bidrag',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Övriga erhållna offentliga bidrag',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3990',
    account_name: 'Övriga ersättningar, bidrag och intäkter',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Diverse andra rörelseintäkter som inte passar i övriga kategorier.',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3991',
    account_name: 'Konfliktersättning',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Konfliktersättning',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3992',
    account_name: 'Erhållna skadestånd',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Erhållna skadestånd',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3993',
    account_name: 'Erhållna donationer och gåvor',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Erhållna donationer och gåvor',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3994',
    account_name: 'Försäkringsersättningar',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Försäkringsersättningar',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3995',
    account_name: 'Erhållet ackord på skulder av rörelsekaraktär',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Erhållet ackord på skulder av rörelsekaraktär',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3996',
    account_name: 'Erhållna reklambidrag',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Erhållna reklambidrag',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3997',
    account_name: 'Sjuklöneersättning',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Sjuklöneersättning',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3998',
    account_name: 'Återbäring av överskott från försäkringsföretag',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återbäring av överskott från försäkringsföretag',
    sru_code: '7413',
    k2_excluded: false,
  },
  {
    account_number: '3999',
    account_name: 'Övriga rörelseintäkter',
    account_class: 3,
    account_group: '39',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Övriga rörelseintäkter',
    sru_code: '7413',
    k2_excluded: false,
  },
]
