import type { BASReferenceAccount } from '../bas-reference'

export const CLASS_8_ACCOUNTS: BASReferenceAccount[] = [
  {
    account_number: '8010',
    account_name: 'Utdelning på andelar i koncernföretag',
    account_class: 8,
    account_group: '80',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Utdelning på andelar i koncernföretag',
    sru_code: '7414',
    k2_excluded: false,
  },
  {
    account_number: '8012',
    account_name: 'Utdelning på andelar i dotterföretag',
    account_class: 8,
    account_group: '80',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Utdelning på andelar i dotterföretag',
    sru_code: '7414',
    k2_excluded: false,
  },
  {
    account_number: '8016',
    account_name: 'Emissionsinsats, koncernföretag',
    account_class: 8,
    account_group: '80',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Emissionsinsats, koncernföretag',
    sru_code: '7414',
    k2_excluded: false,
  },
  {
    account_number: '8020',
    account_name: 'Resultat vid försäljning av andelar i koncernföretag',
    account_class: 8,
    account_group: '80',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Resultat vid försäljning av andelar i koncernföretag',
    sru_code: '7414',
    k2_excluded: false,
  },
  {
    account_number: '8030',
    account_name: 'Resultatandelar från handelsbolag (dotterföretag)',
    account_class: 8,
    account_group: '80',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Resultatandelar från handelsbolag (dotterföretag)',
    sru_code: '7414',
    k2_excluded: false,
  },
  {
    account_number: '8070',
    account_name: 'Nedskrivningar av andelar i och långfristiga fordringar hos koncernföretag',
    account_class: 8,
    account_group: '80',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Nedskrivningar av andelar i och långfristiga fordringar hos koncernföretag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8072',
    account_name: 'Nedskrivningar av andelar i dotterföretag',
    account_class: 8,
    account_group: '80',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Nedskrivningar av andelar i dotterföretag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8076',
    account_name: 'Nedskrivningar av långfristiga fordringar hos moderföretag',
    account_class: 8,
    account_group: '80',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Nedskrivningar av långfristiga fordringar hos moderföretag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8077',
    account_name: 'Nedskrivningar av långfristiga fordringar hos dotterföretag',
    account_class: 8,
    account_group: '80',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Nedskrivningar av långfristiga fordringar hos dotterföretag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8080',
    account_name: 'Återföringar av nedskrivningar av andelar i och långfristiga fordringar hos koncernföretag',
    account_class: 8,
    account_group: '80',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföringar av nedskrivningar av andelar i och långfristiga fordringar hos koncernföretag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8082',
    account_name: 'Återföringar av nedskrivningar av andelar i dotterföretag',
    account_class: 8,
    account_group: '80',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföringar av nedskrivningar av andelar i dotterföretag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8086',
    account_name: 'Återföringar av nedskrivningar av långfristiga fordringar hos moderföretag',
    account_class: 8,
    account_group: '80',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföringar av nedskrivningar av långfristiga fordringar hos moderföretag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8087',
    account_name: 'Återföringar av nedskrivningar av långfristiga fordringar hos dotterföretag',
    account_class: 8,
    account_group: '80',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföringar av nedskrivningar av långfristiga fordringar hos dotterföretag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8110',
    account_name: 'Utdelningar på andelar i intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Utdelningar på andelar i intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i',
    sru_code: '7415',
    k2_excluded: false,
  },
  {
    account_number: '8111',
    account_name: 'Utdelningar på andelar i intresseföretag',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Utdelningar på andelar i intresseföretag',
    sru_code: '7415',
    k2_excluded: false,
  },
  {
    account_number: '8112',
    account_name: 'Utdelningar på andelar i gemensamt styrda företag',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Utdelningar på andelar i gemensamt styrda företag',
    sru_code: '7415',
    k2_excluded: false,
  },
  {
    account_number: '8113',
    account_name: 'Utdelningar på andelar i övriga företag som det finns ett ägarintresse i',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Utdelningar på andelar i övriga företag som det finns ett ägarintresse i',
    sru_code: '7423',
    k2_excluded: false,
  },
  {
    account_number: '8116',
    account_name: 'Emissionsinsats, intresseföretag',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Emissionsinsats, intresseföretag',
    sru_code: '7415',
    k2_excluded: false,
  },
  {
    account_number: '8117',
    account_name: 'Emissionsinsats, gemensamt styrda företag',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Emissionsinsats, gemensamt styrda företag',
    sru_code: '7415',
    k2_excluded: false,
  },
  {
    account_number: '8118',
    account_name: 'Emissionsinsats, övriga företag som det finns ett ägarintresse i',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Emissionsinsats, övriga företag som det finns ett ägarintresse i',
    sru_code: '7423',
    k2_excluded: false,
  },
  {
    account_number: '8120',
    account_name: 'Resultat vid försäljning av andelar i intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Resultat vid försäljning av andelar i intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i',
    sru_code: '7415',
    k2_excluded: false,
  },
  {
    account_number: '8121',
    account_name: 'Resultat vid försäljning av andelar i intresseföretag',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Resultat vid försäljning av andelar i intresseföretag',
    sru_code: '7415',
    k2_excluded: false,
  },
  {
    account_number: '8122',
    account_name: 'Resultat vid försäljning av andelar i gemensamt styrda företag',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Resultat vid försäljning av andelar i gemensamt styrda företag',
    sru_code: '7415',
    k2_excluded: false,
  },
  {
    account_number: '8123',
    account_name: 'Resultat vid försäljning av andelar i övriga företag som det finns ett ägarintresse i',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Resultat vid försäljning av andelar i övriga företag som det finns ett ägarintresse i',
    sru_code: '7423',
    k2_excluded: false,
  },
  {
    account_number: '8130',
    account_name: 'Resultatandelar från handelsbolag (intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i)',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Resultatandelar från handelsbolag (intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i)',
    sru_code: '7415',
    k2_excluded: false,
  },
  {
    account_number: '8131',
    account_name: 'Resultatandelar från handelsbolag (intresseföretag)',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Resultatandelar från handelsbolag (intresseföretag)',
    sru_code: '7415',
    k2_excluded: false,
  },
  {
    account_number: '8132',
    account_name: 'Resultatandelar från handelsbolag (gemensamt styrda företag)',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Resultatandelar från handelsbolag (gemensamt styrda företag)',
    sru_code: '7415',
    k2_excluded: false,
  },
  {
    account_number: '8133',
    account_name: 'Resultatandelar från handelsbolag (övriga företag som det finns ett ägarintresse i)',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Resultatandelar från handelsbolag (övriga företag som det finns ett ägarintresse i)',
    sru_code: '7423',
    k2_excluded: false,
  },
  {
    account_number: '8170',
    account_name: 'Nedskrivningar av andelar i och långfristiga fordringar hos intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Nedskrivningar av andelar i och långfristiga fordringar hos intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8171',
    account_name: 'Nedskrivningar av andelar i intresseföretag',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Nedskrivningar av andelar i intresseföretag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8172',
    account_name: 'Nedskrivningar av långfristiga fordringar hos intresseföretag',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Nedskrivningar av långfristiga fordringar hos intresseföretag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8173',
    account_name: 'Nedskrivningar av andelar i gemensamt styrda företag',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Nedskrivningar av andelar i gemensamt styrda företag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8174',
    account_name: 'Nedskrivningar av långfristiga fordringar hos gemensamt styrda företag',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Nedskrivningar av långfristiga fordringar hos gemensamt styrda företag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8176',
    account_name: 'Nedskrivningar av andelar i övriga företag som det finns ett ägarintresse i',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Nedskrivningar av andelar i övriga företag som det finns ett ägarintresse i',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8177',
    account_name: 'Nedskrivningar av långfristiga fordringar hos övriga företag som det finns ett ägarintresse i',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Nedskrivningar av långfristiga fordringar hos övriga företag som det finns ett ägarintresse i',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8180',
    account_name: 'Återföringar av nedskrivningar av andelar i och långfristiga fordringar hos intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföringar av nedskrivningar av andelar i och långfristiga fordringar hos intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8181',
    account_name: 'Återföringar av nedskrivningar av andelar i intresseföretag',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföringar av nedskrivningar av andelar i intresseföretag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8182',
    account_name: 'Återföringar av nedskrivningar av långfristiga fordringar hos intresseföretag',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföringar av nedskrivningar av långfristiga fordringar hos intresseföretag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8183',
    account_name: 'Återföringar av nedskrivningar av andelar i gemensamt styrda företag',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföringar av nedskrivningar av andelar i gemensamt styrda företag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8184',
    account_name: 'Återföringar av nedskrivningar av långfristiga fordringar hos gemensamt styrda företag',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföringar av nedskrivningar av långfristiga fordringar hos gemensamt styrda företag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8186',
    account_name: 'Återföringar av nedskrivningar av andelar i övriga företag som det finns ett ägarintresse i',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföringar av nedskrivningar av andelar i övriga företag som det finns ett ägarintresse i',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8187',
    account_name: 'Återföringar av nedskrivningar av långfristiga fordringar hos övriga företag som det finns ett ägarintresse i',
    account_class: 8,
    account_group: '81',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföringar av nedskrivningar av långfristiga fordringar hos övriga företag som det finns ett ägarintresse i',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8210',
    account_name: 'Utdelningar på andelar i andra företag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Utdelningar på andelar i andra företag',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8212',
    account_name: 'Utdelningar, andra företag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Utdelningar, andra företag',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8216',
    account_name: 'Insatsemissioner, andra företag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Insatsemissioner, andra företag',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8220',
    account_name: 'Resultat vid försäljning av värdepapper i och långfristiga fordringar hos andra företag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Resultat vid försäljning av värdepapper i och långfristiga fordringar hos andra företag',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8221',
    account_name: 'Resultat vid försäljning av andelar i andra företag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Resultat vid försäljning av andelar i andra företag',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8222',
    account_name: 'Resultat vid försäljning av långfristiga fordringar hos andra företag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Resultat vid försäljning av långfristiga fordringar hos andra företag',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8223',
    account_name: 'Resultat vid försäljning av derivat (långfristiga värdepappersinnehav)',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Resultat vid försäljning av derivat (långfristiga värdepappersinnehav)',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8230',
    account_name: 'Valutakursdifferenser på långfristiga fordringar',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Valutakursdifferenser på långfristiga fordringar',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8231',
    account_name: 'Valutakursvinster på långfristiga fordringar',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Valutakursvinster på långfristiga fordringar',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8236',
    account_name: 'Valutakursförluster på långfristiga fordringar',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Valutakursförluster på långfristiga fordringar',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8240',
    account_name: 'Resultatandelar från handelsbolag (andra företag)',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Resultatandelar från handelsbolag (andra företag)',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8250',
    account_name: 'Ränteintäkter från långfristiga fordringar hos och värdepapper i andra företag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Ränteintäkter från långfristiga fordringar hos och värdepapper i andra företag',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8251',
    account_name: 'Ränteintäkter från långfristiga fordringar',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Ränteintäkter från långfristiga fordringar',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8252',
    account_name: 'Ränteintäkter från övriga värdepapper',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Ränteintäkter från övriga värdepapper',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8254',
    account_name: 'Skattefria ränteintäkter, långfristiga tillgångar',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Skattefria ränteintäkter, långfristiga tillgångar',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8255',
    account_name: 'Avkastningsskatt kapitalplacering',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Avkastningsskatt kapitalplacering',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8260',
    account_name: 'Ränteintäkter från långfristiga fordringar hos koncernföretag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Ränteintäkter från långfristiga fordringar hos koncernföretag',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8261',
    account_name: 'Ränteintäkter från långfristiga fordringar hos moderföretag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Ränteintäkter från långfristiga fordringar hos moderföretag',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8262',
    account_name: 'Ränteintäkter från långfristiga fordringar hos dotterföretag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Ränteintäkter från långfristiga fordringar hos dotterföretag',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8263',
    account_name: 'Ränteintäkter från långfristiga fordringar hos andra koncernföretag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Ränteintäkter från långfristiga fordringar hos andra koncernföretag',
    sru_code: '7416',
    k2_excluded: false,
  },
  {
    account_number: '8270',
    account_name: 'Nedskrivningar av innehav av andelar i och långfristiga fordringar hos andra företag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Nedskrivningar av innehav av andelar i och långfristiga fordringar hos andra företag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8271',
    account_name: 'Nedskrivningar av andelar i andra företag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Nedskrivningar av andelar i andra företag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8272',
    account_name: 'Nedskrivningar av långfristiga fordringar hos andra företag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Nedskrivningar av långfristiga fordringar hos andra företag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8273',
    account_name: 'Nedskrivningar av övriga värdepapper hos andra företag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Nedskrivningar av övriga värdepapper hos andra företag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8280',
    account_name: 'Återföringar av nedskrivningar av andelar i och långfristiga fordringar hos andra företag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföringar av nedskrivningar av andelar i och långfristiga fordringar hos andra företag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8281',
    account_name: 'Återföringar av nedskrivningar av andelar i andra företag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföringar av nedskrivningar av andelar i andra företag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8282',
    account_name: 'Återföringar av nedskrivningar av långfristiga fordringar hos andra företag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföringar av nedskrivningar av långfristiga fordringar hos andra företag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8283',
    account_name: 'Återföringar av nedskrivningar av övriga värdepapper i andra företag',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföringar av nedskrivningar av övriga värdepapper i andra företag',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8290',
    account_name: 'Värdering till verkligt värde, anläggningstillgångar',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Värdering till verkligt värde, anläggningstillgångar',
    sru_code: '7416',
    k2_excluded: true,
  },
  {
    account_number: '8291',
    account_name: 'Orealiserade värdeförändringar på anläggningstillgångar',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Orealiserade värdeförändringar på anläggningstillgångar',
    sru_code: '7416',
    k2_excluded: true,
  },
  {
    account_number: '8295',
    account_name: 'Orealiserade värdeförändringar på derivatinstrument',
    account_class: 8,
    account_group: '82',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Orealiserade värdeförändringar på derivatinstrument',
    sru_code: '7416',
    k2_excluded: true,
  },
  {
    account_number: '8310',
    account_name: 'Ränteintäkter från omsättningstillgångar',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Ränta på bankkontosaldo, sparkonton och utlånade pengar.',
    sru_code: '7417',
    k2_excluded: false,
  },
  {
    account_number: '8311',
    account_name: 'Ränteintäkter från bank',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Ränteintäkter från bank',
    sru_code: '7417',
    k2_excluded: false,
  },
  {
    account_number: '8312',
    account_name: 'Ränteintäkter från kortfristiga placeringar',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Ränteintäkter från kortfristiga placeringar',
    sru_code: '7417',
    k2_excluded: false,
  },
  {
    account_number: '8313',
    account_name: 'Ränteintäkter från kortfristiga fordringar',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Ränteintäkter från kortfristiga fordringar',
    sru_code: '7417',
    k2_excluded: false,
  },
  {
    account_number: '8314',
    account_name: 'Skattefria ränteintäkter',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Skattefria ränteintäkter',
    sru_code: '7417',
    k2_excluded: false,
  },
  {
    account_number: '8317',
    account_name: 'Ränteintäkter för dold räntekompensation',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Ränteintäkter för dold räntekompensation',
    sru_code: '7417',
    k2_excluded: false,
  },
  {
    account_number: '8319',
    account_name: 'Övriga ränteintäkter från omsättningstillgångar',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Övriga ränteintäkter från omsättningstillgångar',
    sru_code: '7417',
    k2_excluded: false,
  },
  {
    account_number: '8320',
    account_name: 'Värdering till verkligt värde, omsättningstillgångar',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Värdering till verkligt värde, omsättningstillgångar',
    sru_code: '7417',
    k2_excluded: true,
  },
  {
    account_number: '8321',
    account_name: 'Orealiserade värdeförändringar på omsättningstillgångar',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Orealiserade värdeförändringar på omsättningstillgångar',
    sru_code: '7417',
    k2_excluded: true,
  },
  {
    account_number: '8325',
    account_name: 'Orealiserade värdeförändringar på derivatinstrument (oms.-tillg.)',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Orealiserade värdeförändringar på derivatinstrument (oms.-tillg.)',
    sru_code: '7417',
    k2_excluded: true,
  },
  {
    account_number: '8330',
    account_name: 'Valutakursdifferenser på kortfristiga fordringar och placeringar',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Valutakursdifferenser på kortfristiga fordringar och placeringar',
    sru_code: '7417',
    k2_excluded: false,
  },
  {
    account_number: '8331',
    account_name: 'Valutakursvinster på kortfristiga fordringar och placeringar',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Valutakursvinster på kortfristiga fordringar och placeringar',
    sru_code: '7417',
    k2_excluded: false,
  },
  {
    account_number: '8336',
    account_name: 'Valutakursförluster på kortfristiga fordringar och placeringar',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Valutakursförluster på kortfristiga fordringar och placeringar',
    sru_code: '7417',
    k2_excluded: false,
  },
  {
    account_number: '8340',
    account_name: 'Utdelningar på kortfristiga placeringar',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Utdelningar på kortfristiga placeringar',
    sru_code: '7417',
    k2_excluded: false,
  },
  {
    account_number: '8350',
    account_name: 'Resultat vid försäljning av kortfristiga placeringar',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Resultat vid försäljning av kortfristiga placeringar',
    sru_code: '7417',
    k2_excluded: false,
  },
  {
    account_number: '8360',
    account_name: 'Övriga ränteintäkter från koncernföretag',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Övriga ränteintäkter från koncernföretag',
    sru_code: '7417',
    k2_excluded: false,
  },
  {
    account_number: '8361',
    account_name: 'Övriga ränteintäkter från moderföretag',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Övriga ränteintäkter från moderföretag',
    sru_code: '7417',
    k2_excluded: false,
  },
  {
    account_number: '8362',
    account_name: 'Övriga ränteintäkter från dotterföretag',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Övriga ränteintäkter från dotterföretag',
    sru_code: '7417',
    k2_excluded: false,
  },
  {
    account_number: '8363',
    account_name: 'Övriga ränteintäkter från andra koncernföretag',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Övriga ränteintäkter från andra koncernföretag',
    sru_code: '7417',
    k2_excluded: false,
  },
  {
    account_number: '8370',
    account_name: 'Nedskrivningar av kortfristiga placeringar',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Nedskrivningar av kortfristiga placeringar',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8380',
    account_name: 'Återföringar av nedskrivningar av kortfristiga placeringar',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföringar av nedskrivningar av kortfristiga placeringar',
    sru_code: '7521',
    k2_excluded: false,
  },
  {
    account_number: '8390',
    account_name: 'Övriga finansiella intäkter',
    account_class: 8,
    account_group: '83',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Övriga finansiella intäkter',
    sru_code: '7417',
    k2_excluded: false,
  },
  {
    account_number: '8400',
    account_name: 'Räntekostnader (gruppkonto)',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Räntekostnader (gruppkonto)',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8410',
    account_name: 'Räntekostnader för långfristiga skulder',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Ränta på lån, krediter och övriga skulder till kreditgivare.',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8411',
    account_name: 'Räntekostnader för obligations-, förlags- och konvertibla lån',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Räntekostnader för obligations-, förlags- och konvertibla lån',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8412',
    account_name: 'Räntedel i årets pensionskostnad',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Räntedel i årets pensionskostnad',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8413',
    account_name: 'Räntekostnader för kontokredit',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Räntekostnader för kontokredit',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8415',
    account_name: 'Räntekostnader för andra skulder till kreditinstitut',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Räntekostnader för andra skulder till kreditinstitut',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8417',
    account_name: 'Räntekostnader för dold räntekompensation m.m.',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Räntekostnader för dold räntekompensation m.m.',
    sru_code: '7522',
    k2_excluded: true,
  },
  {
    account_number: '8418',
    account_name: 'Avdragspost för räntesubventioner',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avdragspost för räntesubventioner',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8419',
    account_name: 'Övriga räntekostnader för långfristiga skulder',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga räntekostnader för långfristiga skulder',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8420',
    account_name: 'Räntekostnader för kortfristiga skulder',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Räntekostnader för kortfristiga skulder',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8421',
    account_name: 'Räntekostnader till kreditinstitut',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Räntekostnader till kreditinstitut',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8422',
    account_name: 'Dröjsmålsräntor för leverantörsskulder',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Dröjsmålsräntor för leverantörsskulder',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8423',
    account_name: 'Räntekostnader för skatter och avgifter',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Räntekostnader för skatter och avgifter',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8424',
    account_name: 'Räntekostnader byggnadskreditiv',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Räntekostnader byggnadskreditiv',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8429',
    account_name: 'Övriga räntekostnader för kortfristiga skulder',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga räntekostnader för kortfristiga skulder',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8430',
    account_name: 'Valutakursdifferenser på skulder',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Valutakursdifferenser på skulder',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8431',
    account_name: 'Valutakursvinster på skulder',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Valutakursvinster på skulder',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8436',
    account_name: 'Valutakursförluster på skulder',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Valutakursförluster på skulder',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8440',
    account_name: 'Erhållna räntebidrag',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Erhållna räntebidrag',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8450',
    account_name: 'Orealiserade värdeförändringar på skulder',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Orealiserade värdeförändringar på skulder',
    sru_code: '7522',
    k2_excluded: true,
  },
  {
    account_number: '8451',
    account_name: 'Orealiserade värdeförändringar på skulder',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Orealiserade värdeförändringar på skulder',
    sru_code: '7522',
    k2_excluded: true,
  },
  {
    account_number: '8455',
    account_name: 'Orealiserade värdeförändringar på säkringsinstrument',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Orealiserade värdeförändringar på säkringsinstrument',
    sru_code: '7522',
    k2_excluded: true,
  },
  {
    account_number: '8460',
    account_name: 'Räntekostnader till koncernföretag',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Räntekostnader till koncernföretag',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8461',
    account_name: 'Räntekostnader till moderföretag',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Räntekostnader till moderföretag',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8462',
    account_name: 'Räntekostnader till dotterföretag',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Räntekostnader till dotterföretag',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8463',
    account_name: 'Räntekostnader till andra koncernföretag',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Räntekostnader till andra koncernföretag',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8480',
    account_name: 'Aktiverade ränteutgifter',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Aktiverade ränteutgifter',
    sru_code: '7522',
    k2_excluded: true,
  },
  {
    account_number: '8490',
    account_name: 'Övriga skuldrelaterade poster',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga skuldrelaterade poster',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8491',
    account_name: 'Erhållet ackord på skulder till kreditinstitut m.m.',
    account_class: 8,
    account_group: '84',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Erhållet ackord på skulder till kreditinstitut m.m.',
    sru_code: '7522',
    k2_excluded: false,
  },
  {
    account_number: '8810',
    account_name: 'Förändring av periodiseringsfond',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Förändring av periodiseringsfond.',
    sru_code: '7420',
    k2_excluded: false,
  },
  {
    account_number: '8811',
    account_name: 'Avsättning till periodiseringsfond',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Avsättning till periodiseringsfond',
    sru_code: '7525',
    k2_excluded: false,
  },
  {
    account_number: '8819',
    account_name: 'Återföring från periodiseringsfond',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföring från periodiseringsfond',
    sru_code: '7420',
    k2_excluded: false,
  },
  {
    account_number: '8820',
    account_name: 'Mottagna koncernbidrag',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Mottagna koncernbidrag',
    sru_code: '7419',
    k2_excluded: false,
  },
  {
    account_number: '8830',
    account_name: 'Lämnade koncernbidrag',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Lämnade koncernbidrag',
    sru_code: '7524',
    k2_excluded: false,
  },
  {
    account_number: '8840',
    account_name: 'Lämnade gottgörelser',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Lämnade gottgörelser',
    sru_code: '7422',
    k2_excluded: false,
  },
  {
    account_number: '8850',
    account_name: 'Förändring av överavskrivningar',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Förändring av överavskrivningar.',
    sru_code: '7421',
    k2_excluded: false,
  },
  {
    account_number: '8851',
    account_name: 'Förändring av överavskrivningar, immateriella anläggningstillgångar',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Förändring av överavskrivningar, immateriella anläggningstillgångar',
    sru_code: '7421',
    k2_excluded: false,
  },
  {
    account_number: '8852',
    account_name: 'Förändring av överavskrivningar, byggnader och markanläggningar',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Förändring av överavskrivningar, byggnader och markanläggningar',
    sru_code: '7421',
    k2_excluded: false,
  },
  {
    account_number: '8853',
    account_name: 'Förändring av överavskrivningar, maskiner respektive inventarier',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Förändring av överavskrivningar, maskiner respektive inventarier',
    sru_code: '7421',
    k2_excluded: false,
  },
  {
    account_number: '8860',
    account_name: 'Förändring av ersättningsfond',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Förändring av ersättningsfond',
    sru_code: '7422',
    k2_excluded: false,
  },
  {
    account_number: '8861',
    account_name: 'Avsättning till ersättningsfond för inventarier',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Avsättning till ersättningsfond för inventarier',
    sru_code: '7422',
    k2_excluded: false,
  },
  {
    account_number: '8862',
    account_name: 'Avsättning till ersättningsfond för byggnader och markanläggningar',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Avsättning till ersättningsfond för byggnader och markanläggningar',
    sru_code: '7422',
    k2_excluded: false,
  },
  {
    account_number: '8864',
    account_name: 'Avsättning till ersättningsfond för djurlager i jordbruk och renskötsel',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'debit',
    description: 'Avsättning till ersättningsfond för djurlager i jordbruk och renskötsel',
    sru_code: '7422',
    k2_excluded: false,
  },
  {
    account_number: '8865',
    account_name: 'Ianspråktagande av ersättningsfond för avskrivningar',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Ianspråktagande av ersättningsfond för avskrivningar',
    sru_code: '7422',
    k2_excluded: false,
  },
  {
    account_number: '8866',
    account_name: 'Ianspråktagande av ersättningsfond för annat än avskrivningar',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Ianspråktagande av ersättningsfond för annat än avskrivningar',
    sru_code: '7422',
    k2_excluded: false,
  },
  {
    account_number: '8869',
    account_name: 'Återföring från ersättningsfond',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Återföring från ersättningsfond',
    sru_code: '7422',
    k2_excluded: false,
  },
  {
    account_number: '8890',
    account_name: 'Övriga bokslutsdispositioner',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Övriga bokslutsdispositioner',
    sru_code: '7422',
    k2_excluded: false,
  },
  {
    account_number: '8892',
    account_name: 'Nedskrivningar av konsolideringskaraktär av anläggningstillgångar',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Nedskrivningar av konsolideringskaraktär av anläggningstillgångar',
    sru_code: '7422',
    k2_excluded: false,
  },
  {
    account_number: '8896',
    account_name: 'Förändring av lagerreserv',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Förändring av lagerreserv',
    sru_code: '7422',
    k2_excluded: false,
  },
  {
    account_number: '8899',
    account_name: 'Övriga bokslutsdispositioner',
    account_class: 8,
    account_group: '88',
    account_type: 'revenue',
    normal_balance: 'credit',
    description: 'Övriga bokslutsdispositioner',
    sru_code: '7422',
    k2_excluded: false,
  },
  {
    account_number: '8910',
    account_name: 'Skatt som belastar årets resultat',
    account_class: 8,
    account_group: '89',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Beräknad inkomstskatt på det skattepliktiga resultatet för räkenskapsåret.',
    sru_code: '7528',
    k2_excluded: false,
  },
  {
    account_number: '8920',
    account_name: 'Skatt på grund av ändrad beskattning',
    account_class: 8,
    account_group: '89',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Skatt på grund av ändrad beskattning',
    sru_code: '7528',
    k2_excluded: false,
  },
  {
    account_number: '8930',
    account_name: 'Restituerad skatt',
    account_class: 8,
    account_group: '89',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Restituerad skatt',
    sru_code: '7528',
    k2_excluded: false,
  },
  {
    account_number: '8940',
    account_name: 'Uppskjuten skatt',
    account_class: 8,
    account_group: '89',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Uppskjuten skatt',
    sru_code: '7528',
    k2_excluded: true,
  },
  {
    account_number: '8980',
    account_name: 'Övriga skatter',
    account_class: 8,
    account_group: '89',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga skatter',
    sru_code: '7528',
    k2_excluded: false,
  },
  {
    account_number: '8990',
    account_name: 'Resultat',
    account_class: 8,
    account_group: '89',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Resultat',
    sru_code: '7450',
    k2_excluded: false,
  },
  {
    account_number: '8999',
    account_name: 'Årets resultat',
    account_class: 8,
    account_group: '89',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Slutresultatkonto som visar vinst eller förlust efter alla intäkter och kostnader.',
    sru_code: '7450',
    k2_excluded: false,
  },
]
