import type { BASReferenceAccount } from '../bas-reference'

export const CLASS_1_ACCOUNTS: BASReferenceAccount[] = [
  {
    account_number: '1010',
    account_name: 'Utvecklingsutgifter',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Aktiverade utgifter för utvecklingsarbete, t.ex. mjukvaruutveckling eller produktutveckling.',
    sru_code: '7201',
    k2_excluded: true,
  },
  {
    account_number: '1011',
    account_name: 'Balanserade utgifter för forskning och utveckling',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Balanserade utgifter för forskning och utveckling',
    sru_code: '7201',
    k2_excluded: true,
  },
  {
    account_number: '1012',
    account_name: 'Balanserade utgifter för programvaror',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Balanserade utgifter för programvaror',
    sru_code: '7201',
    k2_excluded: true,
  },
  {
    account_number: '1018',
    account_name: 'Ackumulerade nedskrivningar på balanserade utgifter',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Ackumulerade nedskrivningar på balanserade utgifter',
    sru_code: '7201',
    k2_excluded: true,
  },
  {
    account_number: '1019',
    account_name: 'Ackumulerade avskrivningar på balanserade utgifter',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Ackumulerade avskrivningar på balanserade utgifter',
    sru_code: '7201',
    k2_excluded: true,
  },
  {
    account_number: '1020',
    account_name: 'Koncessioner m.m.',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Koncessioner m.m.',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1028',
    account_name: 'Ackumulerade nedskrivningar på koncessioner m.m.',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Ackumulerade nedskrivningar på koncessioner m.m.',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1029',
    account_name: 'Ackumulerade avskrivningar på koncessioner m.m.',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Ackumulerade avskrivningar på koncessioner m.m.',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1030',
    account_name: 'Patent',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Aktiverade kostnader för patent och liknande rättigheter.',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1038',
    account_name: 'Ackumulerade nedskrivningar på patent',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade nedskrivningar på patent',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1039',
    account_name: 'Ackumulerade avskrivningar på patent',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade avskrivningar på patent',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1040',
    account_name: 'Licenser',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Licenser',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1048',
    account_name: 'Ackumulerade nedskrivningar på licenser',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade nedskrivningar på licenser',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1049',
    account_name: 'Ackumulerade avskrivningar på licenser',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade avskrivningar på licenser',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1050',
    account_name: 'Varumärken',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Goodwill som uppkommer vid forvrav av rörelse eller inkråmsförvärv.',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1058',
    account_name: 'Ackumulerade nedskrivningar på varumärken',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade nedskrivningar på varumärken',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1059',
    account_name: 'Ackumulerade avskrivningar på varumärken',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade avskrivningar på varumärken',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1060',
    account_name: 'Hyresrätter och liknande',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Hyresrätter och liknande',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1068',
    account_name: 'Ackumulerade nedskrivningar på hyresrätter och liknande',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade nedskrivningar på hyresrätter och liknande',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1069',
    account_name: 'Ackumulerade avskrivningar på hyresrätter och liknande',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade avskrivningar på hyresrätter och liknande',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1070',
    account_name: 'Goodwill',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Goodwill',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1078',
    account_name: 'Ackumulerade nedskrivningar på goodwill',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade nedskrivningar på goodwill',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1079',
    account_name: 'Ackumulerade avskrivningar på goodwill',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade avskrivningar på goodwill',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1080',
    account_name: 'Pågående projekt och förskott för immateriella anläggningstillgångar',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Pågående projekt och förskott för immateriella anläggningstillgångar',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1081',
    account_name: 'Pågående projekt för immateriella anläggningstillgångar',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Pågående projekt för immateriella anläggningstillgångar',
    sru_code: '7201',
    // Ej K2: pagaende egenupparbetade immateriella projekt ar forbjudna under
    // BFNAR 2016:10 punkt 10.4 (egenupparbetade immateriella far inte aktiveras).
    // Saknades i 20260225103139-backfillen; DB-raderna rattas i 20260805112000.
    k2_excluded: true,
  },
  {
    account_number: '1088',
    account_name: 'Förskott för immateriella anläggningstillgångar',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Förskott för immateriella anläggningstillgångar',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1090',
    account_name: 'Övriga immateriella anläggningstillgångar',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Övriga immateriella anläggningstillgångar',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1092',
    account_name: 'Tomträtter',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Tomträtter',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1098',
    account_name: 'Ackumulerade nedskrivningar på övriga immateriella anläggningstillgångar',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade nedskrivningar på övriga immateriella anläggningstillgångar',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1099',
    account_name: 'Ackumulerade avskrivningar på övriga immateriella anläggningstillgångar',
    account_class: 1,
    account_group: '10',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade avskrivningar på övriga immateriella anläggningstillgångar',
    sru_code: '7201',
    k2_excluded: false,
  },
  {
    account_number: '1110',
    account_name: 'Byggnader',
    account_class: 1,
    account_group: '11',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Anskaffningsvärde för byggnader som ägs av företaget.',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1111',
    account_name: 'Byggnader på egen mark',
    account_class: 1,
    account_group: '11',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Byggnader på egen mark',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1112',
    account_name: 'Byggnader på annans mark',
    account_class: 1,
    account_group: '11',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Byggnader på annans mark',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1118',
    account_name: 'Ackumulerade nedskrivningar på byggnader',
    account_class: 1,
    account_group: '11',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Ackumulerade nedskrivningar på byggnader',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1119',
    account_name: 'Ackumulerade avskrivningar på byggnader',
    account_class: 1,
    account_group: '11',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Ackumulerad värdeminskning på byggnader sedan anskaffningstidpunkten.',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1120',
    account_name: 'Förbättringsutgifter på annans fastighet',
    account_class: 1,
    account_group: '11',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Förbättringsutgifter på annans fastighet',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1129',
    account_name: 'Ackumulerade avskrivningar på förbättringsutgifter på annans fastighet',
    account_class: 1,
    account_group: '11',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Ackumulerade avskrivningar på förbättringsutgifter på annans fastighet',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1130',
    account_name: 'Mark',
    account_class: 1,
    account_group: '11',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Anskaffningsvärde för mark som ägs av företaget. Mark skrivs inte av.',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1140',
    account_name: 'Tomter och obebyggda markområden',
    account_class: 1,
    account_group: '11',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Tomter och obebyggda markområden',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1150',
    account_name: 'Markanläggningar',
    account_class: 1,
    account_group: '11',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Aktiverade utgifter för markanläggningar som parkering, dränering och brunnar.',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1158',
    account_name: 'Ackumulerade nedskrivningar på markanläggningar',
    account_class: 1,
    account_group: '11',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade nedskrivningar på markanläggningar',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1159',
    account_name: 'Ackumulerade avskrivningar på markanläggningar',
    account_class: 1,
    account_group: '11',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade avskrivningar på markanläggningar',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1180',
    account_name: 'Pågående nyanläggningar och förskott för byggnader och mark',
    account_class: 1,
    account_group: '11',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Pågående nyanläggningar och förskott för byggnader och mark',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1181',
    account_name: 'Pågående ny-, till- och ombyggnad',
    account_class: 1,
    account_group: '11',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Pågående ny-, till- och ombyggnad',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1188',
    account_name: 'Förskott för byggnader och mark',
    account_class: 1,
    account_group: '11',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Förskott för byggnader och mark',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1210',
    account_name: 'Maskiner och andra tekniska anläggningar',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Maskiner, produktionsutrustning och andra tekniska anlaggningar.',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1211',
    account_name: 'Maskiner och andra tekniska anläggningar i övrigt',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Maskiner och andra tekniska anläggningar i övrigt',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1212',
    account_name: 'Byggnads- och markinventarier (för produktion)',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Byggnads- och markinventarier (för produktion)',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1214',
    account_name: 'Datorer (för produktion)',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Datorer (för produktion)',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1216',
    account_name: 'Arbetsfordon',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Arbetsfordon',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1217',
    account_name: 'Finansiellt leasade maskiner',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Finansiellt leasade maskiner',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1218',
    account_name: 'Ackumulerade nedskrivningar på maskiner och andra tekniska anläggningar',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Ackumulerade nedskrivningar på maskiner och andra tekniska anläggningar',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1219',
    account_name: 'Ackumulerade avskrivningar på maskiner och andra tekniska anläggningar',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Ackumulerade avskrivningar på maskiner och andra tekniska anläggningar',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1220',
    account_name: 'Inventarier, verktyg och installationer',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kontorsinventarier, datorer, mobler och verktyg over halva prisbasbeloppet.',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1221',
    account_name: 'Inventarier, verktyg och installationer i övrigt',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Inventarier, verktyg och installationer i övrigt',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1222',
    account_name: 'Byggnads- och markinventarier (ej för produktion)',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Byggnads- och markinventarier (ej för produktion)',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1224',
    account_name: 'Datorer (ej för produktion)',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Datorer (ej för produktion)',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1226',
    account_name: 'Bilar och transportmedel (ej för produktion)',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Bilar och transportmedel (ej för produktion)',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1227',
    account_name: 'Finansiellt leasade inventarier',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Finansiellt leasade inventarier',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1228',
    account_name: 'Ackumulerade nedskrivningar på inventarier, verktyg och installationer',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Ackumulerade nedskrivningar på inventarier, verktyg och installationer',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1229',
    account_name: 'Ackumulerade avskrivningar på inventarier, verktyg och installationer',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Ackumulerad värdeminskning på inventarier och verktyg sedan anskaffning.',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1230',
    account_name: '(Fritt konto för Maskiner och andra tekniska anläggningar)',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: '(Fritt konto för Maskiner och andra tekniska anläggningar)',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1240',
    account_name: '(Fritt konto för Maskiner och andra tekniska anläggningar)',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: '(Fritt konto för Maskiner och andra tekniska anläggningar)',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1249',
    account_name: 'Ackumulerade avskrivningar (fritt konto för Maskiner och andra tekniska anläggningar)',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Ackumulerade avskrivningar på det fria maskinkontot 1240 (kontra-tillgång). BAS 2026 har inga bilkonton i 124x; bilar är 1216 eller 1226.',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1250',
    account_name: '(Fritt konto för Inventarier, verktyg och installationer)',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Fritt konto för Inventarier, verktyg och installationer (BAS 2026)',
    sru_code: '7215',
    k2_excluded: false,
  },
  {
    account_number: '1259',
    account_name: 'Ackumulerade avskrivningar (fritt konto för Inventarier, verktyg och installationer)',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Ackumulerade avskrivningar på det fria inventariekontot 1250 (kontra-tillgång). BAS 2026 har inga datorkonton i 125x; datorer är 1214 eller 1224.',
    sru_code: '7215',
    k2_excluded: false,
  },
  {
    account_number: '1260',
    account_name: '(Fritt konto för Inventarier, verktyg och installationer)',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Fritt konto för Inventarier, verktyg och installationer (BAS 2026)',
    sru_code: '7215',
    k2_excluded: false,
  },
  {
    account_number: '1269',
    account_name: 'Ackumulerade avskrivningar (fritt konto för Inventarier, verktyg och installationer)',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Ackumulerade avskrivningar på det fria inventariekontot 1260 (kontra-tillgång). BAS 2026 har inga leasingkonton i 126x; leasade tillgångar är 1217 eller 1227.',
    sru_code: '7215',
    k2_excluded: false,
  },
  {
    account_number: '1280',
    account_name: 'Pågående nyanläggningar och förskott för maskiner respektive inventarier',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Pågående nyanläggningar och förskott för maskiner respektive inventarier',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1281',
    account_name: 'Pågående nyanläggningar, maskiner respektive inventarier',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Pågående nyanläggningar, maskiner respektive inventarier',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1288',
    account_name: 'Förskott för maskiner respektive inventarier',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Förskott för maskiner respektive inventarier',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1290',
    account_name: 'Övriga materiella anläggningstillgångar',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Materiella anläggningstillgångar som inte passar i övriga underkategorier.',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1291',
    account_name: 'Konst och liknande tillgångar',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Konst och liknande tillgångar',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1292',
    account_name: 'Djur som klassificeras som anläggningstillgång',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Djur som klassificeras som anläggningstillgång',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1298',
    account_name: 'Ackumulerade nedskrivningar på övriga materiella anläggningstillgångar',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade nedskrivningar på övriga materiella anläggningstillgångar',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1299',
    account_name: 'Ackumulerade avskrivningar på övriga materiella anläggningstillgångar',
    account_class: 1,
    account_group: '12',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade avskrivningar på övriga materiella anläggningstillgångar',
    sru_code: '7202',
    k2_excluded: false,
  },
  {
    account_number: '1310',
    account_name: 'Andelar i koncernföretag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Aktier och andelar i dotterbolag och koncernföretag.',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1311',
    account_name: 'Aktier i noterade svenska koncernföretag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Aktier i noterade svenska koncernföretag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1312',
    account_name: 'Aktier i onoterade svenska koncernföretag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Aktier i onoterade svenska koncernföretag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1313',
    account_name: 'Aktier i noterade utländska koncernföretag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Aktier i noterade utländska koncernföretag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1314',
    account_name: 'Aktier i onoterade utländska koncernföretag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Aktier i onoterade utländska koncernföretag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1316',
    account_name: 'Andra andelar i svenska koncernföretag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Andra andelar i svenska koncernföretag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1317',
    account_name: 'Andra andelar i utländska koncernförertag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Andra andelar i utländska koncernförertag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1318',
    account_name: 'Ackumulerade nedskrivningar av andelar i koncernföretag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Ackumulerade nedskrivningar av andelar i koncernföretag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1320',
    account_name: 'Långfristiga fordringar hos koncernföretag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Långfristiga fordringar hos koncernföretag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1321',
    account_name: 'Långfristiga fordringar hos moderföretag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Långfristiga fordringar hos moderföretag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1322',
    account_name: 'Långfristiga fordringar hos dotterföretag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Långfristiga fordringar hos dotterföretag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1323',
    account_name: 'Långfristiga fordringar hos andra koncernföretag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Långfristiga fordringar hos andra koncernföretag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1328',
    account_name: 'Ackumulerade nedskrivningar av långfristiga fordringar hos koncernföretag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Ackumulerade nedskrivningar av långfristiga fordringar hos koncernföretag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1330',
    account_name: 'Andelar i intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Andelar i intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1331',
    account_name: 'Andelar i intresseföretag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Andelar i intresseföretag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1332',
    account_name: 'Ackumulerade nedskrivningar av andelar i intresseföretag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade nedskrivningar av andelar i intresseföretag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1333',
    account_name: 'Andelar i gemensamt styrda företag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Andelar i gemensamt styrda företag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1334',
    account_name: 'Ackumulerade nedskrivningar av andelar i gemensamt styrda företag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade nedskrivningar av andelar i gemensamt styrda företag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1336',
    account_name: 'Andelar i övriga företag som det finns ett ägarintresse i',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Andelar i övriga företag som det finns ett ägarintresse i',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1337',
    account_name: 'Ackumulerade nedskrivningar av andelar i övriga företag som det finns ett ägarintresse i',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade nedskrivningar av andelar i övriga företag som det finns ett ägarintresse i',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1340',
    account_name: 'Långfristiga fordringar hos intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Långfristiga fordringar hos intresseföretag och gemensamt styrda företag samt övriga företag som det finns ett ägarintresse i',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1341',
    account_name: 'Långfristiga fordringar hos intresseföretag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Långfristiga fordringar hos intresseföretag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1342',
    account_name: 'Ackumulerade nedskrivningar av långfristiga fordringar hos intresseföretag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade nedskrivningar av långfristiga fordringar hos intresseföretag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1343',
    account_name: 'Långfristiga fordringar hos gemensamt styrda företag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Långfristiga fordringar hos gemensamt styrda företag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1344',
    account_name: 'Ackumulerade nedskrivningar av långfristiga fordringar hos gemensamt styrda företag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade nedskrivningar av långfristiga fordringar hos gemensamt styrda företag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1346',
    account_name: 'Långfristiga fordringar hos övriga företag som det finns ett ägarintresse i',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Långfristiga fordringar hos övriga företag som det finns ett ägarintresse i',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1347',
    account_name: 'Ackumulerade nedskrivningar av långfristiga fordringar hos övriga företag som det finns ett ägarintresse i',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade nedskrivningar av långfristiga fordringar hos övriga företag som det finns ett ägarintresse i',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1350',
    account_name: 'Andra långfristiga värdepappersinnehav',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Andra långfristiga värdepappersinnehav',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1351',
    account_name: 'Andelar i noterade företag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Andelar i noterade företag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1352',
    account_name: 'Andra andelar',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Andra andelar',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1353',
    account_name: 'Andelar i bostadsrättsföreningar',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Andelar i bostadsrättsföreningar',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1354',
    account_name: 'Obligationer',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Obligationer',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1356',
    account_name: 'Andelar i ekonomiska föreningar',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Andelar i ekonomiska föreningar',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1357',
    account_name: 'Andelar i handelsbolag',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Andelar i handelsbolag',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1358',
    account_name: 'Ackumulerade nedskrivningar av andra långfristiga värdepappersinnehav',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade nedskrivningar av andra långfristiga värdepappersinnehav',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1360',
    account_name: 'Lån till delägare eller närstående, långfristig del',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Lån till delägare eller närstående, långfristig del',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1369',
    account_name: 'Ackumulerade nedskrivningar av lån till delägare eller närstående, långfristig del',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade nedskrivningar av lån till delägare eller närstående, långfristig del',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1370',
    account_name: 'Uppskjuten skattefordran',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Uppskjuten skattefordran',
    sru_code: '7203',
    k2_excluded: true,
  },
  {
    account_number: '1380',
    account_name: 'Andra långfristiga fordringar',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Långfristiga fordringar som inte faller under andra kategorier, t.ex. deposition.',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1381',
    account_name: 'Långfristiga reversfordringar',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Långfristiga reversfordringar',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1382',
    account_name: 'Långfristiga fordringar hos anställda',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Långfristiga fordringar hos anställda',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1383',
    account_name: 'Lämnade depositioner, långfristiga',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Lämnade depositioner, långfristiga',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1384',
    account_name: 'Derivat',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Derivat',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1385',
    account_name: 'Kapitalförsäkring',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kapitalförsäkring',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1387',
    account_name: 'Långfristiga kontraktsfordringar',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Långfristiga kontraktsfordringar',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1388',
    account_name: 'Långfristiga kundfordringar',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Långfristiga kundfordringar',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1389',
    account_name: 'Ackumulerade nedskrivningar av andra långfristiga fordringar',
    account_class: 1,
    account_group: '13',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ackumulerade nedskrivningar av andra långfristiga fordringar',
    sru_code: '7203',
    k2_excluded: false,
  },
  {
    account_number: '1410',
    account_name: 'Lager av råvaror',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ravaror och material som används i produktion men inte är färdiga produkter.',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1419',
    account_name: 'Förändring av lager av råvaror',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Förändring av lager av råvaror',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1420',
    account_name: 'Lager av tillsatsmaterial och förnödenheter',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Lager av tillsatsmaterial och förnödenheter',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1429',
    account_name: 'Förändring av lager av tillsatsmaterial och förnödenheter',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Förändring av lager av tillsatsmaterial och förnödenheter',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1440',
    account_name: 'Produkter i arbete',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Produkter i arbete',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1449',
    account_name: 'Förändring av produkter i arbete',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Förändring av produkter i arbete',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1450',
    account_name: 'Lager av färdiga varor',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Lager av färdiga varor',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1459',
    account_name: 'Förändring av lager av färdiga varor',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Förändring av lager av färdiga varor',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1460',
    account_name: 'Lager av handelsvaror',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Fardiga varor klara att levereras till kund.',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1465',
    account_name: 'Lager av varor VMB',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Lager av varor VMB',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1466',
    account_name: 'Nedskrivning av varor VMB',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Nedskrivning av varor VMB',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1467',
    account_name: 'Lager av varor VMB förenklad',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Lager av varor VMB förenklad',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1469',
    account_name: 'Förändring av lager av handelsvaror',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Förändring av lager av handelsvaror',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1470',
    account_name: 'Pågående arbeten',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Halvfabrikat och arbeten under tillverkning som ännu inte slutförts.',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1471',
    account_name: 'Pågående arbeten, nedlagda kostnader',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Pågående arbeten, nedlagda kostnader',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1478',
    account_name: 'Pågående arbeten, fakturering',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Pågående arbeten, fakturering',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1479',
    account_name: 'Förändring av pågående arbeten',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Förändring av pågående arbeten',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1480',
    account_name: 'Förskott för varor och tjänster',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Förskott för varor och tjänster',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1481',
    account_name: 'Remburser',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Remburser',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1489',
    account_name: 'Övriga förskott till leverantörer',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Övriga förskott till leverantörer',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1490',
    account_name: 'Övriga lagertillgångar',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Övriga lagertillgångar',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1491',
    account_name: 'Lager av värdepapper',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Lager av värdepapper',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1492',
    account_name: 'Lager av fastigheter',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Lager av fastigheter',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1493',
    account_name: 'Djur som klassificeras som omsättningstillgång',
    account_class: 1,
    account_group: '14',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Djur som klassificeras som omsättningstillgång',
    sru_code: '7210',
    k2_excluded: false,
  },
  {
    account_number: '1510',
    account_name: 'Kundfordringar',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Pengar som kunder är skyldiga företaget för skickade fakturor som inte betalats ännu.',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1511',
    account_name: 'Kundfordringar',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kundfordringar',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1512',
    account_name: 'Belånade kundfordringar (factoring)',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Belånade kundfordringar (factoring)',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1513',
    account_name: 'Kundfordringar: delad faktura',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kundfordringar: delad faktura',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1516',
    account_name: 'Tvistiga kundfordringar',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Tvistiga kundfordringar',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1518',
    account_name: 'Ej reskontraförda kundfordringar',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ej reskontraförda kundfordringar',
    sru_code: '7211',
    k2_excluded: true,
  },
  {
    account_number: '1519',
    account_name: 'Nedskrivning av kundfordringar',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Värdering av befarade kundförluster, minskar kundfordringsbalansen.',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1520',
    account_name: 'Växelfordringar',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Växelfordringar',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1525',
    account_name: 'Osäkra växelfordringar',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Osäkra växelfordringar',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1529',
    account_name: 'Nedskrivning av växelfordringar',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'credit',
    description: 'Nedskrivning av växelfordringar',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1530',
    account_name: 'Kontraktsfordringar',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kontraktsfordringar',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1531',
    account_name: 'Kontraktsfordringar',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kontraktsfordringar',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1532',
    account_name: 'Belånade kontraktsfordringar',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Belånade kontraktsfordringar',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1536',
    account_name: 'Tvistiga kontraktsfordringar',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Tvistiga kontraktsfordringar',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1539',
    account_name: 'Nedskrivning av kontraktsfordringar',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Nedskrivning av kontraktsfordringar',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1550',
    account_name: 'Konsignationsfordringar',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Konsignationsfordringar',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1560',
    account_name: 'Kundfordringar hos koncernföretag',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kundfordringar hos koncernföretag',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1561',
    account_name: 'Kundfordringar hos moderföretag',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kundfordringar hos moderföretag',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1562',
    account_name: 'Kundfordringar hos dotterföretag',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kundfordringar hos dotterföretag',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1563',
    account_name: 'Kundfordringar hos andra koncernföretag',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kundfordringar hos andra koncernföretag',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1568',
    account_name: 'Ej reskontraförda kundfordringar hos koncernföretag',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ej reskontraförda kundfordringar hos koncernföretag',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1569',
    account_name: 'Nedskrivning av kundfordringar hos koncernföretag',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Nedskrivning av kundfordringar hos koncernföretag',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1570',
    account_name: 'Kundfordringar hos intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kundfordringar hos intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1571',
    account_name: 'Kundfordringar hos intresseföretag',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kundfordringar hos intresseföretag',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1572',
    account_name: 'Kundfordringar hos gemensamt styrda företag',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kundfordringar hos gemensamt styrda företag',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1573',
    account_name: 'Kundfordringar hos övriga företag som det finns ett ägarintresse i',
    account_class: 1,
    account_group: '15',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kundfordringar hos övriga företag som det finns ett ägarintresse i',
    sru_code: '7211',
    k2_excluded: false,
  },
  {
    account_number: '1610',
    account_name: 'Kortfristiga fordringar hos anställda',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Utlägg eller förskott till anställda som ska återbetalas.',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1611',
    account_name: 'Reseförskott',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Reseförskott',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1612',
    account_name: 'Kassaförskott',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kassaförskott',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1613',
    account_name: 'Övriga förskott',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Övriga förskott',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1614',
    account_name: 'Tillfälliga lån till anställda',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Tillfälliga lån till anställda',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1619',
    account_name: 'Övriga fordringar hos anställda',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Övriga fordringar hos anställda',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1620',
    account_name: 'Upparbetad men ej fakturerad intäkt',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Upparbetad men ej fakturerad intäkt',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1630',
    account_name: 'Avräkning för skatter och avgifter (skattekonto)',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Företagets skattekonto hos Skatteverket. Visar saldo för inbetalda skatter och avgifter.',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1640',
    account_name: 'Skattefordringar',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Skattefordringar',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1650',
    account_name: 'Momsfordran',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Fordran på Skatteverket när ingående moms överstiger utgående moms.',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1660',
    account_name: 'Kortfristiga fordringar hos koncernföretag',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kortfristiga fordringar hos koncernföretag',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1661',
    account_name: 'Kortfristiga fordringar hos moderföretag',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kortfristiga fordringar hos moderföretag',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1662',
    account_name: 'Kortfristiga fordringar hos dotterföretag',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kortfristiga fordringar hos dotterföretag',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1663',
    account_name: 'Kortfristiga fordringar hos andra koncernföretag',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kortfristiga fordringar hos andra koncernföretag',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1670',
    account_name: 'Kortfristiga fordringar hos intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kortfristiga fordringar hos intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1671',
    account_name: 'Kortfristiga fordringar hos intresseföretag',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kortfristiga fordringar hos intresseföretag',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1672',
    account_name: 'Kortfristiga fordringar hos gemensamt styrda företag',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kortfristiga fordringar hos gemensamt styrda företag',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1673',
    account_name: 'Kortfristiga fordringar hos övriga företag som det finns ett ägarintresse i',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kortfristiga fordringar hos övriga företag som det finns ett ägarintresse i',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1680',
    account_name: 'Andra kortfristiga fordringar',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Andra kortfristiga fordringar',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1681',
    account_name: 'Utlägg för kunder',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Utlägg för kunder',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1682',
    account_name: 'Kortfristiga lånefordringar',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kortfristiga lånefordringar',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1683',
    account_name: 'Derivat',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Derivat',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1684',
    account_name: 'Kortfristiga fordringar hos leverantörer',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kortfristiga fordringar hos leverantörer',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1685',
    account_name: 'Kortfristiga fordringar hos delägare eller närstående',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kortfristiga fordringar hos delägare eller närstående',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1686',
    account_name: 'Fordringar för kontokort och kuponger',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Fordringar för kontokort och kuponger',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1687',
    account_name: 'Kortfristig del av långfristiga fordringar',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kortfristig del av långfristiga fordringar',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1688',
    account_name: 'Fordran arbetsmarknadsförsäkringar',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Fordran arbetsmarknadsförsäkringar',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1689',
    account_name: 'Övriga kortfristiga fordringar',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Övriga kortfristiga fordringar',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1690',
    account_name: 'Fordringar för tecknat men ej inbetalt aktiekapital',
    account_class: 1,
    account_group: '16',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Fordringar för tecknat men ej inbetalt aktiekapital',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1710',
    account_name: 'Förutbetalda hyreskostnader',
    account_class: 1,
    account_group: '17',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Hyra som betalats i förskott men avser kommande perioder.',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1720',
    account_name: 'Förutbetalda leasingavgifter',
    account_class: 1,
    account_group: '17',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Leasingavgifter betalade i förskott som avser framtida perioder.',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1730',
    account_name: 'Förutbetalda försäkringspremier',
    account_class: 1,
    account_group: '17',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Förutbetalda försäkringspremier',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1740',
    account_name: 'Förutbetalda räntekostnader',
    account_class: 1,
    account_group: '17',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Förutbetalda räntekostnader',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1750',
    account_name: 'Upplupna hyresintäkter',
    account_class: 1,
    account_group: '17',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Upplupna hyresintäkter',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1760',
    account_name: 'Upplupna ränteintäkter',
    account_class: 1,
    account_group: '17',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Upplupna ränteintäkter',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1770',
    account_name: 'Tillgångar av kostnadsnatur',
    account_class: 1,
    account_group: '17',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Tillgångar av kostnadsnatur',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1780',
    account_name: 'Upplupna avtalsintäkter',
    account_class: 1,
    account_group: '17',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Upplupna avtalsintäkter',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1790',
    account_name: 'Övriga förutbetalda kostnader och upplupna intäkter',
    account_class: 1,
    account_group: '17',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Förutbetalda kostnader och upplupna intäkter som inte ryms i andra underkonton.',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1810',
    account_name: 'Andelar i börsnoterade företag',
    account_class: 1,
    account_group: '18',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kortfristiga aktieinnehav i börsnoterade företag avsedda att säljas inom 12 månader.',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1820',
    account_name: 'Obligationer',
    account_class: 1,
    account_group: '18',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Obligationer',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1830',
    account_name: 'Konvertibla skuldebrev',
    account_class: 1,
    account_group: '18',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Konvertibla skuldebrev',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1860',
    account_name: 'Andelar i koncernföretag, kortfristigt',
    account_class: 1,
    account_group: '18',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Andelar i koncernföretag, kortfristigt',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1880',
    account_name: 'Andra kortfristiga placeringar',
    account_class: 1,
    account_group: '18',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Andra kortfristiga placeringar',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1886',
    account_name: 'Derivat',
    account_class: 1,
    account_group: '18',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Derivat',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1889',
    account_name: 'Andelar i övriga företag',
    account_class: 1,
    account_group: '18',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Andelar i övriga företag',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1890',
    account_name: 'Nedskrivning av kortfristiga placeringar',
    account_class: 1,
    account_group: '18',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Nedskrivning av kortfristiga placeringar',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1910',
    account_name: 'Kassa',
    account_class: 1,
    account_group: '19',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kontanta pengar i företagets kassa.',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1911',
    account_name: 'Huvudkassa',
    account_class: 1,
    account_group: '19',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Huvudkassa',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1912',
    account_name: 'Kassa 2',
    account_class: 1,
    account_group: '19',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kassa 2',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1913',
    account_name: 'Kassa 3',
    account_class: 1,
    account_group: '19',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Kassa 3',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1920',
    account_name: 'PlusGiro',
    account_class: 1,
    account_group: '19',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Pengar på företagets PlusGiro-konto.',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1930',
    account_name: 'Företagskonto',
    account_class: 1,
    account_group: '19',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Företagets huvudsakliga bankkonto för dagliga in- och utbetalningar.',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1940',
    account_name: 'Övriga bankkonton',
    account_class: 1,
    account_group: '19',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Ytterligare bankkonton utöver huvudkontot, t.ex. sparkonto.',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1950',
    account_name: 'Bankcertifikat',
    account_class: 1,
    account_group: '19',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Bankcertifikat och liknande kortfristiga vardepapper.',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1960',
    account_name: 'Koncernkonto moderföretag',
    account_class: 1,
    account_group: '19',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Koncernkonto moderföretag',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1970',
    account_name: 'Särskilda bankkonton',
    account_class: 1,
    account_group: '19',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Särskilda bankkonton',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1972',
    account_name: 'Upphovsmannakonto',
    account_class: 1,
    account_group: '19',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Upphovsmannakonto',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1973',
    account_name: 'Skogskonto',
    account_class: 1,
    account_group: '19',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Skogskonto',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1974',
    account_name: 'Spärrade bankmedel',
    account_class: 1,
    account_group: '19',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Spärrade bankmedel',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1979',
    account_name: 'Övriga särskilda bankkonton',
    account_class: 1,
    account_group: '19',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Övriga särskilda bankkonton',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1980',
    account_name: 'Valutakonton',
    account_class: 1,
    account_group: '19',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Valutakonton',
    sru_code: '7212',
    k2_excluded: false,
  },
  {
    account_number: '1990',
    account_name: 'Redovisningsmedel',
    account_class: 1,
    account_group: '19',
    account_type: 'asset',
    normal_balance: 'debit',
    description: 'Redovisningsmedel',
    sru_code: '7212',
    k2_excluded: false,
  },
]
