import type { BASReferenceAccount } from '../bas-reference'

export const CLASS_7_ACCOUNTS: BASReferenceAccount[] = [
  {
    account_number: '7000',
    account_name: 'Löner till kollektivanställda (gruppkonto)',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Löner till kollektivanställda (gruppkonto)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7010',
    account_name: 'Löner till kollektivanställda',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Bruttolöner (före skatt) till kollektivanställda.',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7011',
    account_name: 'Löner till kollektivanställda',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Löner till kollektivanställda',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7012',
    account_name: 'Vinstandelar till kollektivanställda',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Vinstandelar till kollektivanställda',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7013',
    account_name: 'Lön växa-stöd kollektivanställda 10,21 %',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Lön växa-stöd kollektivanställda 10,21 %',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7017',
    account_name: 'Avgångsvederlag till kollektivanställda',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avgångsvederlag till kollektivanställda',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7018',
    account_name: 'Bruttolöneavdrag, kollektivanställda',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Bruttolöneavdrag, kollektivanställda',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7019',
    account_name: 'Upplupna löner och vinstandelar till kollektivanställda',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Upplupna löner och vinstandelar till kollektivanställda',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7030',
    account_name: 'Löner till kollektivanställda (utlandsanställda)',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Löner till kollektivanställda (utlandsanställda)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7031',
    account_name: 'Löner till kollektivanställda (utlandsanställda)',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Löner till kollektivanställda (utlandsanställda)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7032',
    account_name: 'Vinstandelar till kollektivanställda (utlandsanställda)',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Vinstandelar till kollektivanställda (utlandsanställda)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7037',
    account_name: 'Avgångsvederlag till kollektivanställda (utlandsanställda)',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avgångsvederlag till kollektivanställda (utlandsanställda)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7038',
    account_name: 'Bruttolöneavdrag, kollektivanställda (utlandsanställda)',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Bruttolöneavdrag, kollektivanställda (utlandsanställda)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7039',
    account_name: 'Upplupna löner och vinstandelar till kollektivanställda (utlandsanställda)',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Upplupna löner och vinstandelar till kollektivanställda (utlandsanställda)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7080',
    account_name: 'Löner till kollektivanställda för ej arbetad tid',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Löner till kollektivanställda för ej arbetad tid',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7081',
    account_name: 'Sjuklöner till kollektivanställda',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Sjuklöner till kollektivanställda',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7082',
    account_name: 'Semesterlöner till kollektivanställda',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Semesterlöner till kollektivanställda.',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7083',
    account_name: 'Föräldraersättning till kollektivanställda',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Föräldraersättning till kollektivanställda',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7089',
    account_name: 'Övriga löner till kollektivanställda för ej arbetad tid',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga löner till kollektivanställda för ej arbetad tid',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7090',
    account_name: 'Förändring av semesterlöneskuld',
    account_class: 7,
    account_group: '70',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Justering av skuld för intjänade semesterdagar som ännu inte tagits ut.',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7200',
    account_name: 'Löner till tjänstemän och företagsledare (gruppkonto)',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Löner till tjänstemän och företagsledare (gruppkonto)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7210',
    account_name: 'Löner till tjänstemän',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Bruttolöner till tjänstemän.',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7211',
    account_name: 'Löner till tjänstemän',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Löner till tjänstemän',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7212',
    account_name: 'Vinstandelar till tjänstemän',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Vinstandelar till tjänstemän',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7213',
    account_name: 'Lön växa-stöd tjänstemän 10,21 %',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Lön växa-stöd tjänstemän 10,21 %',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7217',
    account_name: 'Avgångsvederlag till tjänstemän',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avgångsvederlag till tjänstemän',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7218',
    account_name: 'Bruttolöneavdrag, tjänstemän',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Bruttolöneavdrag, tjänstemän',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7219',
    account_name: 'Upplupna löner och vinstandelar till tjänstemän',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Upplupna löner och vinstandelar till tjänstemän',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7220',
    account_name: 'Löner till företagsledare',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Löner till företagsledare',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7221',
    account_name: 'Löner till företagsledare',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Löner till företagsledare',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7222',
    account_name: 'Tantiem till företagsledare',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Tantiem till företagsledare',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7227',
    account_name: 'Avgångsvederlag till företagsledare',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avgångsvederlag till företagsledare',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7228',
    account_name: 'Bruttolöneavdrag, företagsledare',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Bruttolöneavdrag, företagsledare',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7229',
    account_name: 'Upplupna löner och tantiem till företagsledare',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Upplupna löner och tantiem till företagsledare',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7230',
    account_name: 'Löner till tjänstemän och ftgsledare (utlandsanställda)',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Löner till tjänstemän och ftgsledare (utlandsanställda)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7231',
    account_name: 'Löner till tjänstemän och ftgsledare (utlandsanställda)',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Löner till tjänstemän och ftgsledare (utlandsanställda)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7232',
    account_name: 'Vinstandelar till tjänstemän och ftgsledare (utlandsanställda)',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Vinstandelar till tjänstemän och ftgsledare (utlandsanställda)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7237',
    account_name: 'Avgångsvederlag till tjänstemän och ftgsledare (utlandsanställda)',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avgångsvederlag till tjänstemän och ftgsledare (utlandsanställda)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7238',
    account_name: 'Bruttolöneavdrag, tjänstemän och ftgsledare (utlandsanställda)',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Bruttolöneavdrag, tjänstemän och ftgsledare (utlandsanställda)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7239',
    account_name: 'Upplupna löner och vinstandelar till tjänstemän och ftgsledare (utlandsanställda)',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Upplupna löner och vinstandelar till tjänstemän och ftgsledare (utlandsanställda)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7240',
    account_name: 'Styrelsearvoden',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Styrelsearvoden',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7280',
    account_name: 'Löner till tjänstemän och företagsledare för ej arbetad tid',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Löner till tjänstemän och företagsledare för ej arbetad tid',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7281',
    account_name: 'Sjuklöner till tjänstemän',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Sjuklöner till tjänstemän',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7282',
    account_name: 'Sjuklöner till företagsledare',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Sjuklöner till företagsledare',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7283',
    account_name: 'Föräldraersättning till tjänstemän',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Föräldraersättning till tjänstemän',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7284',
    account_name: 'Föräldraersättning till företagsledare',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Föräldraersättning till företagsledare',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7285',
    account_name: 'Semesterlöner till tjänstemän',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Semesterlöner till tjänstemän',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7286',
    account_name: 'Semesterlöner till företagsledare',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Semesterlöner till företagsledare',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7288',
    account_name: 'Övriga löner till tjänstemän för ej arbetad tid',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga löner till tjänstemän för ej arbetad tid',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7289',
    account_name: 'Övriga löner till företagsledare för ej arbetad tid',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga löner till företagsledare för ej arbetad tid',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7290',
    account_name: 'Förändring av semesterlöneskuld',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Justering av semesterlöneskuld för tjänstemän.',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7291',
    account_name: 'Förändring av semesterlöneskuld till tjänstemän',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förändring av semesterlöneskuld till tjänstemän',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7292',
    account_name: 'Förändring av semesterlöneskuld till företagsledare',
    account_class: 7,
    account_group: '72',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förändring av semesterlöneskuld till företagsledare',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7300',
    account_name: 'Kostnadsersättningar och förmåner (gruppkonto)',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnadsersättningar och förmåner (gruppkonto)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7310',
    account_name: 'Kontanta extraersättningar',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnadsersättningar till anställda, t.ex. milersättning och traktamente.',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7311',
    account_name: 'Ersättningar för sammanträden m.m.',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Ersättningar för sammanträden m.m.',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7312',
    account_name: 'Ersättningar för förslagsverksamhet och uppfinningar',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Ersättningar för förslagsverksamhet och uppfinningar',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7313',
    account_name: 'Ersättningar för/bidrag till bostadskostnader',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Ersättningar för/bidrag till bostadskostnader',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7314',
    account_name: 'Ersättningar för/bidrag till måltidskostnader',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Ersättningar för/bidrag till måltidskostnader',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7315',
    account_name: 'Ersättningar för/bidrag till resor till och från arbetsplatsen',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Ersättningar för/bidrag till resor till och från arbetsplatsen',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7316',
    account_name: 'Ersättningar för/bidrag till arbetskläder',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Ersättningar för/bidrag till arbetskläder',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7317',
    account_name: 'Ersättningar för/bidrag till arbetsmaterial och arbetsverktyg',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Ersättningar för/bidrag till arbetsmaterial och arbetsverktyg',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7318',
    account_name: 'Felräkningspengar',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Felräkningspengar',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7319',
    account_name: 'Övriga kontanta extraersättningar',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kontanta extraersättningar',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7320',
    account_name: 'Traktamenten vid tjänsteresa',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Traktamenten vid tjänsteresa',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7321',
    account_name: 'Skattefria traktamenten, Sverige',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Skattefria traktamenten, Sverige',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7322',
    account_name: 'Skattepliktiga traktamenten, Sverige',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Skattepliktiga traktamenten, Sverige',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7323',
    account_name: 'Skattefria traktamenten, utlandet',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Skattefria traktamenten, utlandet',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7324',
    account_name: 'Skattepliktiga traktamenten, utlandet',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Skattepliktiga traktamenten, utlandet',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7330',
    account_name: 'Bilersättningar',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Bilersättningar',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7331',
    account_name: 'Skattefria bilersättningar',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Skattefria bilersättningar',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7332',
    account_name: 'Skattepliktiga bilersättningar',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Skattepliktiga bilersättningar',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7333',
    account_name: 'Ersättning för trängselskatt, skattefri',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Ersättning för trängselskatt, skattefri',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7350',
    account_name: 'Ersättningar för föreskrivna arbetskläder',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Ersättningar för föreskrivna arbetskläder',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7370',
    account_name: 'Representationsersättningar',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Representationsersättningar',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7380',
    account_name: 'Kostnader för förmåner till anställda',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för förmåner till anställda',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7381',
    account_name: 'Kostnader för fri bostad',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för fri bostad',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7382',
    account_name: 'Kostnader för fria eller subventionerade måltider',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för fria eller subventionerade måltider',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7383',
    account_name: 'Kostnader för fria resor till och från arbetsplatsen',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för fria resor till och från arbetsplatsen',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7384',
    account_name: 'Kostnader för fria eller subventionerade arbetskläder',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för fria eller subventionerade arbetskläder',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7385',
    account_name: 'Kostnader för fri bil',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för fri bil',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7386',
    account_name: 'Subventionerad ränta',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Subventionerad ränta',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7387',
    account_name: 'Kostnader för lånedatorer',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för lånedatorer',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7388',
    account_name: 'Anställdas ersättning för erhållna förmåner',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Anställdas ersättning för erhållna förmåner',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7389',
    account_name: 'Övriga kostnader för förmåner',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kostnader för förmåner',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7390',
    account_name: 'Övriga kostnadsersättningar och förmåner',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kostnadsersättningar och förmåner',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7391',
    account_name: 'Kostnad för trängselskatteförmån',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnad för trängselskatteförmån',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7392',
    account_name: 'Kostnad för förmån av hushållsnära tjänster',
    account_class: 7,
    account_group: '73',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnad för förmån av hushållsnära tjänster',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7400',
    account_name: 'Pensionskostnader (gruppkonto)',
    account_class: 7,
    account_group: '74',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Pensionskostnader (gruppkonto)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7410',
    account_name: 'Pensionsförsäkringspremier',
    account_class: 7,
    account_group: '74',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Premiebetalningar för tjänstepension till anställda.',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7411',
    account_name: 'Premier för kollektiva pensionsförsäkringar',
    account_class: 7,
    account_group: '74',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Premier för kollektiva pensionsförsäkringar',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7412',
    account_name: 'Premier för individuella pensionsförsäkringar',
    account_class: 7,
    account_group: '74',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Premier för individuella pensionsförsäkringar',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7420',
    account_name: 'Förändring av pensionsskuld',
    account_class: 7,
    account_group: '74',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förändring av pensionsskuld',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7430',
    account_name: 'Avdrag för räntedel i pensionskostnad',
    account_class: 7,
    account_group: '74',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avdrag för räntedel i pensionskostnad',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7440',
    account_name: 'Förändring av pensionsstiftelsekapital',
    account_class: 7,
    account_group: '74',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förändring av pensionsstiftelsekapital',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7441',
    account_name: 'Överföring av medel till pensionsstiftelse',
    account_class: 7,
    account_group: '74',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Överföring av medel till pensionsstiftelse',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7448',
    account_name: 'Gottgörelse från pensionsstiftelse',
    account_class: 7,
    account_group: '74',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Gottgörelse från pensionsstiftelse',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7460',
    account_name: 'Pensionsutbetalningar',
    account_class: 7,
    account_group: '74',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Pensionsutbetalningar',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7461',
    account_name: 'Pensionsutbetalningar till f.d. kollektivanställda',
    account_class: 7,
    account_group: '74',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Pensionsutbetalningar till f.d. kollektivanställda',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7462',
    account_name: 'Pensionsutbetalningar till f.d. tjänstemän',
    account_class: 7,
    account_group: '74',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Pensionsutbetalningar till f.d. tjänstemän',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7463',
    account_name: 'Pensionsutbetalningar till f.d. företagsledare',
    account_class: 7,
    account_group: '74',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Pensionsutbetalningar till f.d. företagsledare',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7470',
    account_name: 'Förvaltnings- och kreditförsäkringsavgifter',
    account_class: 7,
    account_group: '74',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förvaltnings- och kreditförsäkringsavgifter',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7490',
    account_name: 'Övriga pensionskostnader',
    account_class: 7,
    account_group: '74',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga pensionskostnader',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7500',
    account_name: 'Sociala och andra avgifter enligt lag och avtal (gruppkonto)',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Sociala och andra avgifter enligt lag och avtal (gruppkonto)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7510',
    account_name: 'Arbetsgivaravgifter 31,42 %',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Lagstadgade sociala avgifter (ca 31,42% av bruttolonen) till Skatteverket.',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7511',
    account_name: 'Arbetsgivaravgifter för löner och ersättningar',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Arbetsgivaravgifter för löner och ersättningar',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7512',
    account_name: 'Arbetsgivaravgifter för förmånsvärden',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Arbetsgivaravgifter för förmånsvärden',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7515',
    account_name: 'Arbetsgivaravgifter på skattepliktiga kostnadsersättningar',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Arbetsgivaravgifter på skattepliktiga kostnadsersättningar',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7516',
    account_name: 'Arbetsgivaravgifter på arvoden',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Arbetsgivaravgifter på arvoden',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7518',
    account_name: 'Arbetsgivaravgifter på bruttolöneavdrag m.m.',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Arbetsgivaravgifter på bruttolöneavdrag m.m.',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7519',
    account_name: 'Arbetsgivaravgifter för semester- och löneskulder',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Beräknade sociala avgifter på upplupna semesterlöner och andra löneskulder.',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7530',
    account_name: 'Särskild löneskatt',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Särskild löneskatt',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7531',
    account_name: 'Särskild löneskatt för vissa försäkringsersättningar m.m.',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Särskild löneskatt för vissa försäkringsersättningar m.m.',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7532',
    account_name: 'Särskild löneskatt pensionskostnader, deklarationspost',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Särskild löneskatt pensionskostnader, deklarationspost',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7533',
    account_name: 'Särskild löneskatt för pensionskostnader',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Särskild löneskatt på pensionskostnader (24,26%).',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7550',
    account_name: 'Avkastningsskatt på pensionsmedel',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avkastningsskatt på pensionsmedel',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7551',
    account_name: 'Avkastningsskatt 15 % försäkringsföretag m.fl. samt avsatt till pensioner',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avkastningsskatt 15 % försäkringsföretag m.fl. samt avsatt till pensioner',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7552',
    account_name: 'Avkastningsskatt 15 % utländska pensionsförsäkringar',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avkastningsskatt 15 % utländska pensionsförsäkringar',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7553',
    account_name: 'Avkastningsskatt 30 % utländska försäkringsföretag m.fl.',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avkastningsskatt 30 % utländska försäkringsföretag m.fl.',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7554',
    account_name: 'Avkastningsskatt 30 % utländska kapitalförsäkringar',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avkastningsskatt 30 % utländska kapitalförsäkringar',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7570',
    account_name: 'Premier för arbetsmarknadsförsäkringar',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Premier för arbetsmarknadsförsäkringar',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7571',
    account_name: 'Arbetsmarknadsförsäkringar',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Arbetsmarknadsförsäkringar',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7572',
    account_name: 'Arbetsmarknadsförsäkringar pensionsförsäkringspremier, deklarationspost',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Arbetsmarknadsförsäkringar pensionsförsäkringspremier, deklarationspost',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7580',
    account_name: 'Gruppförsäkringspremier',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Gruppförsäkringspremier',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7581',
    account_name: 'Grupplivförsäkringspremier',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Grupplivförsäkringspremier',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7582',
    account_name: 'Gruppsjukförsäkringspremier',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Gruppsjukförsäkringspremier',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7583',
    account_name: 'Gruppolycksfallsförsäkringspremier',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Gruppolycksfallsförsäkringspremier',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7589',
    account_name: 'Övriga gruppförsäkringspremier',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga gruppförsäkringspremier',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7590',
    account_name: 'Övriga sociala och andra avgifter enligt lag och avtal',
    account_class: 7,
    account_group: '75',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga sociala och andra avgifter enligt lag och avtal',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7600',
    account_name: 'Övriga personalkostnader (gruppkonto)',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga personalkostnader (gruppkonto)',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7610',
    account_name: 'Utbildning',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för utbildning, kurser och konferenser för anställda.',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7620',
    account_name: 'Sjuk- och hälsovård',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Sjuk- och hälsovård',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7621',
    account_name: 'Sjuk- och hälsovård, avdragsgill',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Sjuk- och hälsovård, avdragsgill',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7622',
    account_name: 'Sjuk- och hälsovård, ej avdragsgill',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Sjuk- och hälsovård, ej avdragsgill',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7623',
    account_name: 'Sjukvårdsförsäkring, ej avdragsgill',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Sjukvårdsförsäkring, ej avdragsgill',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7630',
    account_name: 'Personalrepresentation',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Personalrepresentation',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7631',
    account_name: 'Personalrepresentation, avdragsgill',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avdragsgill intern representation, t.ex. personalfester och jullunch.',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7632',
    account_name: 'Personalrepresentation, ej avdragsgill',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Personalrepresentation, ej avdragsgill',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7650',
    account_name: 'Sjuklöneförsäkring',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Sjuklöneförsäkring',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7670',
    account_name: 'Förändring av personalstiftelsekapital',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förändring av personalstiftelsekapital',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7671',
    account_name: 'Avsättning till personalstiftelse',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avsättning till personalstiftelse',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7678',
    account_name: 'Gottgörelse från personalstiftelse',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Gottgörelse från personalstiftelse',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7690',
    account_name: 'Övriga personalkostnader',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Diverse personalkostnader som inte ryms i andra underkonton.',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7691',
    account_name: 'Personalrekrytering',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Personalrekrytering',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7692',
    account_name: 'Begravningshjälp',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Begravningshjälp',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7693',
    account_name: 'Fritidsverksamhet',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Fritidsverksamhet',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7699',
    account_name: 'Övriga personalkostnader',
    account_class: 7,
    account_group: '76',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga personalkostnader',
    sru_code: '7514',
    k2_excluded: false,
  },
  {
    account_number: '7710',
    account_name: 'Nedskrivningar av immateriella anläggningstillgångar',
    account_class: 7,
    account_group: '77',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Nedskrivningar av immateriella anläggningstillgångar',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7720',
    account_name: 'Nedskrivningar av byggnader och mark',
    account_class: 7,
    account_group: '77',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Nedskrivningar av byggnader och mark',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7730',
    account_name: 'Nedskrivningar av maskiner respektive inventarier',
    account_class: 7,
    account_group: '77',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Nedskrivningar av maskiner respektive inventarier',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7731',
    account_name: 'Nedskrivningar av maskiner och andra tekniska anläggningar',
    account_class: 7,
    account_group: '77',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Nedskrivningar av maskiner och andra tekniska anläggningar',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7732',
    account_name: 'Nedskrivningar av inventarier, verktyg och installationer',
    account_class: 7,
    account_group: '77',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Nedskrivningar av inventarier, verktyg och installationer',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7733',
    account_name: 'Nedskrivningar av övriga materiella anläggningstillgångar',
    account_class: 7,
    account_group: '77',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Nedskrivningar av övriga materiella anläggningstillgångar',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7740',
    account_name: 'Nedskrivningar av vissa omsättningstillgångar',
    account_class: 7,
    account_group: '77',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Nedskrivningar av vissa omsättningstillgångar',
    sru_code: '7516',
    k2_excluded: false,
  },
  {
    account_number: '7760',
    account_name: 'Återföring av nedskrivningar av immateriella anläggningstillgångar',
    account_class: 7,
    account_group: '77',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Återföring av nedskrivningar av immateriella anläggningstillgångar',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7770',
    account_name: 'Återföring av nedskrivningar av byggnader och mark',
    account_class: 7,
    account_group: '77',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Återföring av nedskrivningar av byggnader och mark',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7780',
    account_name: 'Återföring av nedskrivningar av maskiner respektive inventarier',
    account_class: 7,
    account_group: '77',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Återföring av nedskrivningar av maskiner respektive inventarier',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7781',
    account_name: 'Återföring av nedskrivningar av maskiner och andra tekniska anläggningar',
    account_class: 7,
    account_group: '77',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Återföring av nedskrivningar av maskiner och andra tekniska anläggningar',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7782',
    account_name: 'Återföring av nedskrivningar av inventarier, verktyg och installationer',
    account_class: 7,
    account_group: '77',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Återföring av nedskrivningar av inventarier, verktyg och installationer',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7783',
    account_name: 'Återföring av nedskrivningar av övriga materiella anläggningstillgångar',
    account_class: 7,
    account_group: '77',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Återföring av nedskrivningar av övriga materiella anläggningstillgångar',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7790',
    account_name: 'Återföring av nedskrivningar av vissa omsättningstillgångar',
    account_class: 7,
    account_group: '77',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Återföring av nedskrivningar av vissa omsättningstillgångar',
    sru_code: '7516',
    k2_excluded: false,
  },
  {
    account_number: '7810',
    account_name: 'Avskrivningar på immateriella anläggningstillgångar',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Planmässig avskrivning av goodwill, patent och andra immateriella tillgångar.',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7811',
    account_name: 'Avskrivningar på balanserade utgifter',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avskrivningar på balanserade utgifter',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7812',
    account_name: 'Avskrivningar på koncessioner m.m.',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avskrivningar på koncessioner m.m.',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7813',
    account_name: 'Avskrivningar på patent',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avskrivningar på patent',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7814',
    account_name: 'Avskrivningar på licenser',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avskrivningar på licenser',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7815',
    account_name: 'Avskrivningar på varumärken',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avskrivningar på varumärken',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7816',
    account_name: 'Avskrivningar på hyresrätter',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avskrivningar på hyresrätter',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7817',
    account_name: 'Avskrivningar på goodwill',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avskrivningar på goodwill',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7819',
    account_name: 'Avskrivningar på övriga immateriella anläggningstillgångar',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avskrivningar på övriga immateriella anläggningstillgångar',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7820',
    account_name: 'Avskrivningar på byggnader och markanläggningar',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Årlig värdeminskning på byggnader. Typiskt 2-5% per är beroende på byggnadstyp.',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7821',
    account_name: 'Avskrivningar på byggnader',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avskrivningar på byggnader',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7824',
    account_name: 'Avskrivningar på markanläggningar',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avskrivningar på markanläggningar',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7829',
    account_name: 'Avskrivningar på övriga byggnader',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avskrivningar på övriga byggnader',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7830',
    account_name: 'Avskrivningar på maskiner respektive inventarier',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avskrivningar på maskiner respektive inventarier',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7831',
    account_name: 'Avskrivningar på maskiner och andra tekniska anläggningar',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avskrivningar på maskiner och andra tekniska anläggningar',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7832',
    account_name: 'Avskrivningar på inventarier, verktyg och installationer',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Årlig värdeminskning på inventarier, maskiner och verktyg.',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7836',
    account_name: 'Avskrivningar på leasade tillgångar',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avskrivningar på leasade tillgångar',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7839',
    account_name: 'Avskrivningar på övriga materiella anläggningstillgångar',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avskrivningar på övriga materiella anläggningstillgångar',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7840',
    account_name: 'Avskrivningar på förbättringsutgifter på annans fastighet',
    account_class: 7,
    account_group: '78',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avskrivningar på förbättringsutgifter på annans fastighet',
    sru_code: '7515',
    k2_excluded: false,
  },
  {
    account_number: '7940',
    account_name: 'Orealiserade positiva/negativa värdeförändringar på säkringsinstrument',
    account_class: 7,
    account_group: '79',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Orealiserade positiva/negativa värdeförändringar på säkringsinstrument',
    sru_code: '7517',
    k2_excluded: true,
  },
  {
    account_number: '7960',
    account_name: 'Valutakursförluster på fordringar och skulder av rörelsekaraktär',
    account_class: 7,
    account_group: '79',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förluster som uppstår vid valutaväxling eller betalningar i utländsk valuta.',
    sru_code: '7517',
    k2_excluded: false,
  },
  {
    account_number: '7970',
    account_name: 'Förlust vid avyttring av immateriella och materiella anläggningstillgångar',
    account_class: 7,
    account_group: '79',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förlust vid avyttring av immateriella och materiella anläggningstillgångar.',
    sru_code: '7517',
    k2_excluded: false,
  },
  {
    account_number: '7971',
    account_name: 'Förlust vid avyttring av immateriella anläggningstillgångar',
    account_class: 7,
    account_group: '79',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förlust vid avyttring av immateriella anläggningstillgångar',
    sru_code: '7517',
    k2_excluded: false,
  },
  {
    account_number: '7972',
    account_name: 'Förlust vid avyttring av byggnader och mark',
    account_class: 7,
    account_group: '79',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förlust vid avyttring av byggnader och mark',
    sru_code: '7517',
    k2_excluded: false,
  },
  {
    account_number: '7973',
    account_name: 'Förlust vid avyttring av maskiner och inventarier',
    account_class: 7,
    account_group: '79',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förlust vid avyttring av maskiner och inventarier',
    sru_code: '7517',
    k2_excluded: false,
  },
  {
    account_number: '7990',
    account_name: 'Övriga rörelsekostnader',
    account_class: 7,
    account_group: '79',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga rörelsekostnader',
    sru_code: '7517',
    k2_excluded: false,
  },
]
