/**
 * Company settings (company_settings): the one implementation of "save these
 * settings" behind the dashboard's PUT /api/settings, the v1 operations
 * settings.update / settings.update-tax-profile / settings.update-bookkeeping-lock
 * and their MCP tools. Every door gets the same rules and the same side
 * effects:
 *
 *   - owner/admin only. company_settings is written under the RLS predicate
 *     user_is_company_admin; the dashboard checks it in withRouteContext
 *     ({ requireAdmin }) and passes `adminVerified`, the API-key and MCP doors
 *     run as the service role (auth.uid() is null there, so the predicate
 *     cannot be asked) and this service reads the caller's company_members
 *     role instead. The invoice-recipient and payment-instruction fields are
 *     re-checked the same way on every door;
 *   - reminder thresholds strictly increasing;
 *   - org_number is fixed once onboarding is complete (legal identifier);
 *   - enskild firma keeps a calendar fiscal year (BFL 3 kap.);
 *   - aktiekapital and antal aktier are set together (ÅRL 5 kap 34 §);
 *   - the vacation-year basis cannot move while open vacation balances exist;
 *   - VAT coherence: turning VAT registration off retires the VAT-dependent
 *     flags, a registered company needs a VAT number and a moms period, a
 *     taxable base over SEK 40 million means monthly moms, periodisk
 *     sammanställning needs registration and EU trade;
 *   - kontantmetoden has no deferred invoice booking (#967, accrual only);
 *   - payment instructions are written through to the default payee cash
 *     account FIRST (migration 20260904010000), so a failure writes nothing;
 *   - tax deadlines are regenerated when a tax-relevant field is saved, or
 *     when the company has no system tax deadlines at all (self-heal). A
 *     failed regeneration never fails the save;
 *   - turning dimensions on (dimensions_enabled from off to on) registers the
 *     dimension codes already on journal lines as archived values
 *     (lib/dimensions/import-existing.ts), so the registry is complete for
 *     the history on whichever door flipped the flag. A failed registration
 *     never fails the save; it comes back as a warning.
 *
 * A dry run performs every read and every check and writes nothing: no payee
 * write-through, no settings update, no deadline regeneration, no code
 * registration.
 */
import type { z } from 'zod'
import type { UpdateSettingsSchema } from '@/lib/api/schemas'
import {
  hasTaxRelevantFields,
  regenerateTaxDeadlinesForUser,
  shouldRegenerateTaxDeadlines,
  toDeadlineSettings,
} from '@/lib/tax/deadline-generator'
import { propagateLegacyPayeeWrite } from '@/lib/cash-accounts/invoice-payee'
import { importExistingDimensionCodes } from '@/lib/dimensions/import-existing'
import type { OperationContext, OperationOutcome, OperationWarning } from '@/lib/operations/types'
import { requireCompanyAdmin } from '@/lib/operations/access'

/** The dashboard's settings body after validation: column names, all optional. */
export type CompanySettingsChanges = z.output<typeof UpdateSettingsSchema>

type SettingsRow = Record<string, unknown>

export interface UpdateCompanySettingsOptions {
  dryRun?: boolean
  /**
   * The door already asked the database whether the caller is owner/admin
   * (withRouteContext requireAdmin). Doors without a cookie session (API
   * key, MCP) leave this false and the service reads the membership role.
   */
  adminVerified?: boolean
}

export interface UpdateCompanySettingsResult {
  /** The stored row after the update (every column). */
  settings: SettingsRow
  /** Whether the tax deadlines were regenerated by this save. */
  deadlines_regenerated: boolean
  /**
   * How many codes already on journal lines were registered because this
   * save turned dimensions on; null when it did not (or the registration
   * failed, which the warnings say).
   */
  dimension_codes_imported: number | null
}


/** Every column the settings body can write, as an object literal. */
function toUpdatePayload(c: CompanySettingsChanges) {
  return {
    entity_type: c.entity_type,
    company_name: c.company_name,
    org_number: c.org_number,
    address_line1: c.address_line1,
    address_line2: c.address_line2,
    postal_code: c.postal_code,
    city: c.city,
    registered_office: c.registered_office,
    country: c.country,
    f_skatt: c.f_skatt,
    vat_registered: c.vat_registered,
    vat_number: c.vat_number,
    moms_period: c.moms_period,
    vat_taxable_base_over_40m: c.vat_taxable_base_over_40m,
    vat_has_eu_trade: c.vat_has_eu_trade,
    vat_filing_method: c.vat_filing_method,
    periodisk_sammanstallning_enabled: c.periodisk_sammanstallning_enabled,
    periodisk_sammanstallning_period: c.periodisk_sammanstallning_period,
    periodisk_sammanstallning_filing_method: c.periodisk_sammanstallning_filing_method,
    kontrolluppgifter_enabled: c.kontrolluppgifter_enabled,
    rot_rut_enabled: c.rot_rut_enabled,
    oss_enabled: c.oss_enabled,
    ioss_enabled: c.ioss_enabled,
    intrastat_enabled: c.intrastat_enabled,
    punktskatt_enabled: c.punktskatt_enabled,
    fyllnadsinbetalning_enabled: c.fyllnadsinbetalning_enabled,
    tax_contact_name: c.tax_contact_name,
    tax_contact_phone: c.tax_contact_phone,
    tax_contact_email: c.tax_contact_email,
    fiscal_year_start_month: c.fiscal_year_start_month,
    preliminary_tax_monthly: c.preliminary_tax_monthly,
    aktiekapital: c.aktiekapital,
    antal_aktier: c.antal_aktier,
    employer_registered: c.employer_registered,
    employer_seasonal: c.employer_seasonal,
    bank_name: c.bank_name,
    clearing_number: c.clearing_number,
    account_number: c.account_number,
    bankgiro: c.bankgiro,
    plusgiro: c.plusgiro,
    swish: c.swish,
    iban: c.iban,
    bic: c.bic,
    invoice_payment_accounts: c.invoice_payment_accounts,
    accounting_method: c.accounting_method,
    defer_invoice_booking: c.defer_invoice_booking,
    invoice_prefix: c.invoice_prefix,
    next_invoice_number: c.next_invoice_number,
    next_arrival_number: c.next_arrival_number,
    invoice_default_days: c.invoice_default_days,
    invoice_default_notes: c.invoice_default_notes,
    default_our_reference: c.default_our_reference,
    phone: c.phone,
    email: c.email,
    website: c.website,
    pays_salaries: c.pays_salaries,
    sector_slug: c.sector_slug,
    bookkeeping_locked_through: c.bookkeeping_locked_through,
    auto_lock_period_days: c.auto_lock_period_days,
    default_voucher_series: c.default_voucher_series,
    default_voucher_series_per_source_type: c.default_voucher_series_per_source_type,
    voucher_series_labels: c.voucher_series_labels,
    ore_rounding: c.ore_rounding,
    invoice_show_ocr: c.invoice_show_ocr,
    invoice_show_bankgiro: c.invoice_show_bankgiro,
    invoice_show_plusgiro: c.invoice_show_plusgiro,
    invoice_show_swish: c.invoice_show_swish,
    invoice_show_payment_qr: c.invoice_show_payment_qr,
    invoice_qr_mode: c.invoice_qr_mode,
    invoice_show_logo: c.invoice_show_logo,
    invoice_show_company_name: c.invoice_show_company_name,
    invoice_company_name_position: c.invoice_company_name_position,
    invoice_late_fee_text: c.invoice_late_fee_text,
    invoice_credit_terms_text: c.invoice_credit_terms_text,
    invoice_payment_links_enabled: c.invoice_payment_links_enabled,
    invoice_email_texts: c.invoice_email_texts,
    invoice_email_cc_addresses: c.invoice_email_cc_addresses,
    invoice_email_bcc_addresses: c.invoice_email_bcc_addresses,
    invoice_email_reply_to: c.invoice_email_reply_to,
    invoice_primary_color: c.invoice_primary_color,
    invoice_accent_color: c.invoice_accent_color,
    invoice_font_family: c.invoice_font_family,
    invoice_header_text: c.invoice_header_text,
    invoice_footer_text: c.invoice_footer_text,
    send_invoice_reminders: c.send_invoice_reminders,
    reminder_days_level_1: c.reminder_days_level_1,
    reminder_days_level_2: c.reminder_days_level_2,
    reminder_days_level_3: c.reminder_days_level_3,
    reminder_text_overrides: c.reminder_text_overrides,
    reminder_fee_enabled: c.reminder_fee_enabled,
    reminder_fee_amount: c.reminder_fee_amount,
    reminder_interest_rate_override: c.reminder_interest_rate_override,
    ai_flow_enabled: c.ai_flow_enabled,
    dimensions_enabled: c.dimensions_enabled,
    mileage_enabled: c.mileage_enabled,
    sales_orders_enabled: c.sales_orders_enabled,
    quotes_enabled: c.quotes_enabled,
    proforma_enabled: c.proforma_enabled,
    recurring_invoices_enabled: c.recurring_invoices_enabled,
    self_billing_enabled: c.self_billing_enabled,
    preferred_payment_format: c.preferred_payment_format,
    salary_pay_day: c.salary_pay_day,
    salary_default_bank: c.salary_default_bank,
    salary_net_rounding: c.salary_net_rounding,
    salary_payslip_show_employer_cost: c.salary_payslip_show_employer_cost,
    salary_payslip_show_breakdown: c.salary_payslip_show_breakdown,
    salary_calculation_policy: c.salary_calculation_policy,
    salary_deviation_period: c.salary_deviation_period,
    salary_vacation_year_basis: c.salary_vacation_year_basis,
  }
}

/** The supplied keys only: what the save actually changes. */
function suppliedChanges(payload: Record<string, unknown>): Record<string, unknown> {
  return Object.fromEntries(Object.entries(payload).filter(([, value]) => value !== undefined))
}

function refuse(code: string, messageSv?: string, details?: Record<string, unknown>) {
  return {
    ok: false as const,
    code,
    ...(messageSv ? { messageSv } : {}),
    ...(details ? { details } : {}),
  }
}

/** Why the semesterår basis cannot change right now; the one place that rule lives. */
export type VacationBasisChangeCheck =
  | { changeable: true }
  | { changeable: false; code: 'SETTINGS_VACATION_BASIS_OPEN_BALANCES' }
  | { changeable: false; code: 'UNKNOWN_ERROR'; error: unknown }

/**
 * Whether the vacation-year basis (salary_vacation_year_basis) may move.
 * Changing the boundary while OPEN vacation-ledger rows exist would orphan
 * them (rows are keyed by vacation_year_start), so it is refused until the
 * current year is closed. A failed check fails closed. The save below asks
 * this; the salary settings page asks it too, to lock the choice up front
 * with the same reason instead of letting a save fail.
 */
export async function checkVacationBasisChange(
  ctx: Pick<OperationContext, 'supabase' | 'companyId'>,
): Promise<VacationBasisChangeCheck> {
  const { count: openRows, error } = await ctx.supabase
    .from('employee_vacation_balances')
    .select('id', { count: 'exact', head: true })
    .eq('company_id', ctx.companyId)
    .eq('status', 'open')
  if (error) return { changeable: false, code: 'UNKNOWN_ERROR', error }
  if ((openRows ?? 0) > 0) return { changeable: false, code: 'SETTINGS_VACATION_BASIS_OPEN_BALANCES' }
  return { changeable: true }
}

export async function updateCompanySettings(
  ctx: OperationContext,
  input: CompanySettingsChanges,
  options: UpdateCompanySettingsOptions = {},
): Promise<OperationOutcome<UpdateCompanySettingsResult>> {
  const { supabase, companyId, log } = ctx
  const body: CompanySettingsChanges = { ...input }

  // The stored row: the fallback for every cross-field rule below, and the
  // "before" side of a dry-run preview.
  const { data: oldRow, error: oldError } = await supabase
    .from('company_settings')
    .select('*')
    .eq('company_id', companyId)
    .maybeSingle()
  if (oldError) {
    log.error('failed to read company settings before update', oldError)
    return { ok: false, code: 'UNKNOWN_ERROR', error: oldError }
  }
  const oldSettings = (oldRow ?? null) as SettingsRow | null

  const changesInvoiceEmailRecipients =
    body.invoice_email_cc_addresses !== undefined
    || body.invoice_email_bcc_addresses !== undefined
    || body.invoice_email_reply_to !== undefined
  const changesInvoicePaymentInstructions =
    body.invoice_payment_accounts !== undefined
    || body.bank_name !== undefined
    || body.clearing_number !== undefined
    || body.account_number !== undefined
    || body.bankgiro !== undefined
    || body.plusgiro !== undefined
    || body.swish !== undefined
    || body.iban !== undefined
    || body.bic !== undefined
  if (!options.adminVerified || changesInvoiceEmailRecipients || changesInvoicePaymentInstructions) {
    const denied = await requireCompanyAdmin(
      ctx,
      'Bara företagets ägare eller en administratör kan ändra företagsinställningarna.',
    )
    if (denied) return denied
  }

  const reminderDays = [
    body.reminder_days_level_1 ?? (oldSettings?.reminder_days_level_1 as number | undefined) ?? 15,
    body.reminder_days_level_2 ?? (oldSettings?.reminder_days_level_2 as number | undefined) ?? 30,
    body.reminder_days_level_3 ?? (oldSettings?.reminder_days_level_3 as number | undefined) ?? 45,
  ]
  if (!(reminderDays[0] < reminderDays[1] && reminderDays[1] < reminderDays[2])) {
    return refuse('SETTINGS_REMINDER_DAYS_ORDER')
  }

  // Lock org_number after onboarding is complete (legal identifier: changing it
  // would orphan vouchers, SIE history, and tax filings). company_name remains
  // editable so users can update their display/brand name (e.g. särskilt företagsnamn).
  if (oldSettings?.onboarding_complete === true) {
    delete body.org_number
  }

  // Enskild firma must use calendar year (BFL 3 kap.)
  const effectiveEntityType = body.entity_type || oldSettings?.entity_type
  const effectiveFYStartMonth = body.fiscal_year_start_month ?? oldSettings?.fiscal_year_start_month
  if (effectiveEntityType === 'enskild_firma' && effectiveFYStartMonth && effectiveFYStartMonth !== 1) {
    return refuse('SETTINGS_EF_CALENDAR_YEAR')
  }

  // Share capital is all-or-nothing: the antal aktier/kvotvärde note (ÅRL 5 kap 34 §)
  // needs both the registered amount and the share count, and the DB pair
  // constraint enforces it. Validate against the effective (body-or-stored)
  // values so the caller gets a clear message instead of a raw constraint 500.
  if (body.aktiekapital !== undefined || body.antal_aktier !== undefined) {
    const effectiveAktiekapital =
      body.aktiekapital !== undefined ? body.aktiekapital : (oldSettings?.aktiekapital ?? null)
    const effectiveAntalAktier =
      body.antal_aktier !== undefined ? body.antal_aktier : (oldSettings?.antal_aktier ?? null)
    if ((effectiveAktiekapital === null) !== (effectiveAntalAktier === null)) {
      return refuse('SETTINGS_SHARE_CAPITAL_PAIR')
    }
  }

  // Vacation year basis (payroll gap-closure 3.1): not while open
  // vacation-ledger rows exist (checkVacationBasisChange).
  if (
    body.salary_vacation_year_basis !== undefined &&
    body.salary_vacation_year_basis !== oldSettings?.salary_vacation_year_basis
  ) {
    const basisCheck = await checkVacationBasisChange({ supabase, companyId })
    if (!basisCheck.changeable) {
      // Fail closed: a failed check must not let the basis change through
      // and orphan open vacation-ledger rows.
      if (basisCheck.code === 'UNKNOWN_ERROR') return { ok: false, code: 'UNKNOWN_ERROR', error: basisCheck.error }
      return refuse(basisCheck.code)
    }
  }

  // Turning VAT registration off retires the VAT-dependent flags, and
  // dropping EU trade retires the EU sales list: stale true values would
  // otherwise block the save below or silently resurrect wrong deadlines
  // when registration is re-enabled later. Same coherence rule as the
  // 20260717070000 migration and the tax settings form.
  if (body.vat_registered === false) {
    body.vat_taxable_base_over_40m = false
    body.vat_has_eu_trade = false
    body.periodisk_sammanstallning_enabled = false
  }
  if (body.vat_has_eu_trade === false) {
    body.periodisk_sammanstallning_enabled = false
  }
  // Seasonal registration is a mode of being a registered employer; an
  // unregistered company cannot be sasongsregistrerad.
  if (body.employer_registered === false) {
    body.employer_seasonal = false
  }
  // Deferred booking is an accrual-only concept (#967): kontantmetoden books
  // on payment, so a stale true flag must not survive a switch to it (the
  // bookkeeping settings form sends false in that case too).
  if (body.accounting_method === 'cash') {
    body.defer_invoice_booking = false
  }

  // VAT-registered must have VAT number (ML 17 kap. 24 §, the invoice needs
  // it) and moms period (SFL 26 kap.). Each cross-field check runs only when
  // the request touches a field in its group: a partial save of unrelated
  // settings (e.g. the invoice bank-details dialog) must not be rejected for a
  // pre-existing inconsistency it cannot fix from that surface. Explicit null
  // counts as touched, it clears a value, so it must not fall back to the
  // stored one during validation. PS/EU-trade edits are in the completeness
  // group: enabling the EU sales list on an incomplete VAT registration must
  // keep failing like it did when the check ran on every save.
  const effectiveVatRegistered = body.vat_registered ?? oldSettings?.vat_registered
  const effectiveMomsPeriod = body.moms_period !== undefined ? body.moms_period : oldSettings?.moms_period
  const touchesVatCompleteness =
    body.vat_registered !== undefined ||
    body.vat_number !== undefined ||
    body.moms_period !== undefined ||
    body.vat_has_eu_trade !== undefined ||
    body.periodisk_sammanstallning_enabled !== undefined
  if (touchesVatCompleteness && effectiveVatRegistered === true) {
    const effectiveVatNumber = body.vat_number !== undefined ? body.vat_number : oldSettings?.vat_number
    if (!effectiveVatNumber) return refuse('SETTINGS_VAT_NUMBER_REQUIRED')
    if (!effectiveMomsPeriod) return refuse('SETTINGS_MOMS_PERIOD_REQUIRED')
  }

  const touchesVat40m =
    body.vat_registered !== undefined ||
    body.vat_taxable_base_over_40m !== undefined ||
    body.moms_period !== undefined
  const effectiveVatTaxableBaseOver40m =
    body.vat_taxable_base_over_40m ?? oldSettings?.vat_taxable_base_over_40m ?? false
  if (touchesVat40m && effectiveVatRegistered && effectiveVatTaxableBaseOver40m && effectiveMomsPeriod !== 'monthly') {
    return refuse('SETTINGS_VAT_40M_REQUIRES_MONTHLY')
  }

  const touchesPs =
    body.periodisk_sammanstallning_enabled !== undefined ||
    body.vat_registered !== undefined ||
    body.vat_has_eu_trade !== undefined
  const effectivePsEnabled =
    body.periodisk_sammanstallning_enabled ?? oldSettings?.periodisk_sammanstallning_enabled ?? false
  const effectiveEuTrade = body.vat_has_eu_trade ?? oldSettings?.vat_has_eu_trade ?? false
  if (touchesPs && effectivePsEnabled && (!effectiveVatRegistered || !effectiveEuTrade)) {
    return refuse('SETTINGS_PS_REQUIRES_VAT_AND_EU_TRADE')
  }

  const payload = toUpdatePayload(body)

  // Regenerate when the save touches tax-relevant fields: the statutory
  // dates are derived from them, and re-running also repairs rows created
  // by older schedule logic or lost to an earlier generation failure. The
  // generator preserves completed rows, so filing progress survives.
  // Additionally self-heal when the company has no system deadlines at all:
  // tax settings are filled at onboarding, so an unrelated later save may be
  // the first chance to backfill an empty set. Counted before the write in a
  // dry run (the preview says whether the save will regenerate) and after it
  // otherwise, exactly where the dashboard always counted.
  const taxFieldsInBody = hasTaxRelevantFields(body as Record<string, unknown>)
  const countSystemDeadlines = async (): Promise<number> => {
    if (taxFieldsInBody) return 0
    const { count, error: countError } = await supabase
      .from('deadlines')
      .select('id', { count: 'exact', head: true })
      .eq('company_id', companyId)
      .eq('source', 'system')
      .eq('deadline_type', 'tax')
    // Fail safe: on a count error, assume deadlines already exist so we do
    // NOT delete+regenerate on a transient failure (regeneration would reset
    // the status of pending rows). A non-zero placeholder keeps the
    // self-heal off.
    return countError ? 1 : (count ?? 0)
  }

  // Turning dimensions on means the registry must hold the codes the history
  // already carries. It used to happen only when the settings page's toggle
  // called the scan itself, so a v1 or MCP save turned dimensions on without it.
  const turnsDimensionsOn = body.dimensions_enabled === true && oldSettings?.dimensions_enabled !== true

  if (options.dryRun) {
    if (!oldSettings) {
      return refuse('NOT_FOUND', 'Inställningarna hittades inte.', { resource: 'company_settings' })
    }
    const changes = suppliedChanges(payload)
    const previous = Object.fromEntries(Object.keys(changes).map((key) => [key, oldSettings[key] ?? null]))
    const willRegenerate = shouldRegenerateTaxDeadlines(taxFieldsInBody, await countSystemDeadlines())
    return {
      ok: true,
      dryRun: true,
      preview: {
        changes,
        previous,
        proposed: { ...oldSettings, ...changes },
        deadlines_will_regenerate: willRegenerate,
        dimension_codes_will_import: turnsDimensionsOn,
        warnings: lockWarnings(oldSettings, body),
      },
    }
  }

  // Payment instructions live on cash_accounts since migration
  // 20260904010000; the bank columns are a mirror of the default payee
  // account per currency. Write the change through to the account FIRST: if
  // that fails nothing has been written and the caller gets an error, instead
  // of a settings row that the next mirror would undo.
  if (changesInvoicePaymentInstructions) {
    try {
      await propagateLegacyPayeeWrite(supabase, companyId, body)
    } catch (err) {
      log.error('failed to write payment instructions through to cash accounts', err as Error)
      return { ok: false, code: 'UNKNOWN_ERROR', error: err }
    }
  }

  const { data, error } = await supabase
    .from('company_settings')
    .update(payload)
    .eq('company_id', companyId)
    .select('*')
    .single()

  if (error) {
    if (error.code === 'PGRST116') {
      return refuse('NOT_FOUND', 'Inställningarna hittades inte.', { resource: 'company_settings' })
    }
    return { ok: false, code: 'UNKNOWN_ERROR', error }
  }

  let deadlinesRegenerated = false
  if (shouldRegenerateTaxDeadlines(taxFieldsInBody, await countSystemDeadlines())) {
    try {
      await regenerateTaxDeadlinesForUser(supabase, companyId, toDeadlineSettings(data))
      deadlinesRegenerated = true
      log.info('tax deadlines regenerated after settings change')
    } catch (err) {
      log.error('failed to regenerate tax deadlines', err as Error)
      // Don't fail the settings update if deadline generation fails
    }
  }

  const warnings = lockWarnings(oldSettings, body)

  let dimensionCodesImported: number | null = null
  if (turnsDimensionsOn) {
    const imported = await importExistingDimensionCodes(ctx)
    if (imported.ok && !imported.dryRun) {
      dimensionCodesImported = imported.data.created
      if (imported.data.created > 0) warnings.push(dimensionCodesImportedWarning(imported.data.created))
    } else {
      // Dimensions are on either way: the settings page's toggle, or turning
      // the flag off and on again, runs the registration once more.
      log.error('registering the dimension codes already on journal lines failed', undefined, {
        code: imported.ok ? 'UNEXPECTED_DRY_RUN' : imported.code,
      })
      warnings.push(DIMENSION_CODES_IMPORT_FAILED)
    }
  }

  return {
    ok: true,
    data: {
      settings: data as SettingsRow,
      deadlines_regenerated: deadlinesRegenerated,
      dimension_codes_imported: dimensionCodesImported,
    },
    ...(warnings.length > 0 ? { warnings } : {}),
  }
}

function dimensionCodesImportedWarning(count: number): OperationWarning {
  return {
    code: 'DIMENSION_CODES_IMPORTED',
    message_sv: `${count} dimensionskoder som redan fanns på verifikationsrader lades in i registret som arkiverade värden.`,
    message_en: `${count} dimension codes already on journal lines were added to the registry as archived values.`,
  }
}

const DIMENSION_CODES_IMPORT_FAILED: OperationWarning = {
  code: 'DIMENSION_CODES_IMPORT_FAILED',
  message_sv:
    'Dimensionerna slogs på, men koderna som redan finns på verifikationsrader kunde inte läggas in i registret. Slå av och på dimensionerna igen för att försöka på nytt.',
  message_en:
    'Dimensions were turned on, but the codes already on journal lines could not be added to the registry. Turn dimensions off and on again to retry.',
}

/**
 * Moving bookkeeping_locked_through earlier (or clearing it) reopens dates
 * that were closed for writes. The dashboard allows it, so every door does;
 * the save goes through and says so, because it re-exposes booked periods to
 * change (BFL 5 kap: the audit trigger records the old and new date).
 */
function lockWarnings(oldSettings: SettingsRow | null, body: CompanySettingsChanges): OperationWarning[] {
  if (body.bookkeeping_locked_through === undefined) return []
  const before = (oldSettings?.bookkeeping_locked_through as string | null | undefined) ?? null
  const after = body.bookkeeping_locked_through
  if (before === null || (after !== null && after >= before)) return []
  return [
    {
      code: 'BOOKKEEPING_LOCK_MOVED_BACKWARDS',
      message_sv: after === null
        ? `Bokföringslåset (låst till och med ${before}) togs bort: tidigare låsta datum kan ändras igen.`
        : `Bokföringslåset flyttades bakåt från ${before} till ${after}: datumen däremellan kan ändras igen.`,
      message_en: after === null
        ? `The bookkeeping lock (locked through ${before}) was removed: previously locked dates are writable again.`
        : `The bookkeeping lock moved back from ${before} to ${after}: the dates in between are writable again.`,
    },
  ]
}

/**
 * GET-side rule shared by the dashboard and the settings.get operation:
 * legacy rows may carry a null company_settings.entity_type; the company row
 * is the source of truth then.
 */
export async function withEntityTypeFallback<T extends SettingsRow>(
  ctx: Pick<OperationContext, 'supabase' | 'companyId'>,
  row: T,
): Promise<T> {
  if (row.entity_type) return row
  const { data: company } = await ctx.supabase
    .from('companies')
    .select('entity_type')
    .eq('id', ctx.companyId)
    .single()
  const entityType = (company as { entity_type?: string } | null)?.entity_type
  return entityType ? { ...row, entity_type: entityType } : row
}

/**
 * The settings row for the API read (settings.get): every column a settings
 * operation can write plus the fixed identity. Literal select so the schema
 * guard can check each column; never '*', which would also hand an API
 * caller internal bookkeeping columns.
 */
export async function getCompanySettings(ctx: OperationContext): Promise<OperationOutcome<SettingsRow>> {
  const { data, error } = await ctx.supabase
    .from('company_settings')
    .select(
      'entity_type, company_name, org_number, address_line1, address_line2, postal_code, city, registered_office, country, phone, email, website, default_our_reference, tax_contact_name, tax_contact_phone, tax_contact_email, bank_name, clearing_number, account_number, bankgiro, plusgiro, swish, iban, bic, invoice_payment_accounts, invoice_prefix, next_invoice_number, next_arrival_number, invoice_default_days, invoice_default_notes, ore_rounding, invoice_show_ocr, invoice_show_bankgiro, invoice_show_plusgiro, invoice_show_swish, invoice_show_payment_qr, invoice_qr_mode, invoice_show_logo, invoice_show_company_name, invoice_company_name_position, invoice_late_fee_text, invoice_credit_terms_text, invoice_payment_links_enabled, invoice_email_texts, invoice_email_cc_addresses, invoice_email_bcc_addresses, invoice_email_reply_to, invoice_primary_color, invoice_accent_color, invoice_font_family, invoice_header_text, invoice_footer_text, send_invoice_reminders, reminder_days_level_1, reminder_days_level_2, reminder_days_level_3, reminder_text_overrides, reminder_fee_enabled, reminder_fee_amount, reminder_interest_rate_override, default_voucher_series, default_voucher_series_per_source_type, voucher_series_labels, sector_slug, dimensions_enabled, mileage_enabled, sales_orders_enabled, quotes_enabled, proforma_enabled, recurring_invoices_enabled, self_billing_enabled, salary_vacation_year_basis, f_skatt, vat_registered, vat_number, moms_period, vat_taxable_base_over_40m, vat_has_eu_trade, vat_filing_method, periodisk_sammanstallning_enabled, periodisk_sammanstallning_period, periodisk_sammanstallning_filing_method, kontrolluppgifter_enabled, rot_rut_enabled, oss_enabled, ioss_enabled, intrastat_enabled, punktskatt_enabled, fyllnadsinbetalning_enabled, fiscal_year_start_month, preliminary_tax_monthly, pays_salaries, employer_registered, employer_seasonal, accounting_method, defer_invoice_booking, aktiekapital, antal_aktier, bookkeeping_locked_through, auto_lock_period_days, onboarding_complete',
    )
    .eq('company_id', ctx.companyId)
    .maybeSingle()
  if (error) {
    ctx.log.error('company settings read failed', error)
    return { ok: false, code: 'UNKNOWN_ERROR', error }
  }
  if (!data) return refuse('NOT_FOUND', 'Inställningarna hittades inte.', { resource: 'company_settings' })
  return { ok: true, data: await withEntityTypeFallback(ctx, data as SettingsRow) }
}
