import type { BASReferenceAccount } from '../bas-reference'

export const CLASS_5_ACCOUNTS: BASReferenceAccount[] = [
  {
    account_number: '5000',
    account_name: 'Lokalkostnader (gruppkonto)',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Lokalkostnader (gruppkonto)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5010',
    account_name: 'Lokalhyra',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Månadshyra för kontorslokal, lager eller annan arbetsplats.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5011',
    account_name: 'Hyra för kontorslokaler',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Hyra för kontorslokaler',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5012',
    account_name: 'Hyra för garage',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Hyra för garage',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5013',
    account_name: 'Hyra för lagerlokaler',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Hyra för lagerlokaler',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5019',
    account_name: 'Övriga kostnader för lokalhyra',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kostnader för lokalhyra',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5020',
    account_name: 'El',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Elkostnader för företagets lokaler.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5030',
    account_name: 'Värme',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Värme',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5040',
    account_name: 'Vatten och avlopp',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Vatten och avlopp',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5050',
    account_name: 'Lokaltillbehör',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Lokaltillbehör',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5060',
    account_name: 'Städning och renhållning',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för städning och rengöring av företagets lokaler.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5061',
    account_name: 'Städning',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Städning',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5062',
    account_name: 'Sophämtning',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Sophämtning',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5064',
    account_name: 'Snöröjning',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Snöröjning',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5065',
    account_name: 'Trädgårdsskötsel',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Trädgårdsskötsel',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5069',
    account_name: 'Övriga kostnader för städning och underhåll',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kostnader för städning och underhåll',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5070',
    account_name: 'Reparation och underhåll av lokaler',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Reparation och underhåll av lokaler',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5090',
    account_name: 'Övriga lokalkostnader',
    account_class: 5,
    account_group: '50',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Lokalkostnader som inte passar i andra underkonton, t.ex. vatten och varme.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5100',
    account_name: 'Fastighetskostnader (gruppkonto)',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Fastighetskostnader (gruppkonto)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5110',
    account_name: 'Tomträttsavgäld/arrende',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Tomträttsavgäld/arrende',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5120',
    account_name: 'El',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'El',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5130',
    account_name: 'Värme',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Värme',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5131',
    account_name: 'Uppvärmning',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Uppvärmning',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5132',
    account_name: 'Sotning',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Sotning',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5139',
    account_name: 'Övriga kostnader för värme',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kostnader för värme',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5140',
    account_name: 'Vatten och avlopp',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Vatten och avlopp',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5160',
    account_name: 'Städning och renhållning',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Städning och renhållning',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5161',
    account_name: 'Städning',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Städning',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5162',
    account_name: 'Sophämtning',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Sophämtning',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5164',
    account_name: 'Snöröjning',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Snöröjning',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5165',
    account_name: 'Trädgårdsskötsel',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Trädgårdsskötsel',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5169',
    account_name: 'Övriga kostnader för städning och renhållning',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kostnader för städning och renhållning',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5170',
    account_name: 'Reparation och underhåll av fastighet',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Reparation och underhåll av fastighet',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5190',
    account_name: 'Övriga fastighetskostnader',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga fastighetskostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5191',
    account_name: 'Fastighetsskatt/fastighetsavgift',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Fastighetsskatt/fastighetsavgift',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5192',
    account_name: 'Fastighetsförsäkringspremier',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Fastighetsförsäkringspremier',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5193',
    account_name: 'Fastighetsskötsel och förvaltning',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Fastighetsskötsel och förvaltning',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5198',
    account_name: 'Övriga fastighetskostnader',
    account_class: 5,
    account_group: '51',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga fastighetskostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5200',
    account_name: 'Hyra av anläggningstillgångar (gruppkonto)',
    account_class: 5,
    account_group: '52',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för leasing eller hyra av maskiner, bilar och annan utrustning.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5210',
    account_name: 'Hyra av maskiner och andra tekniska anläggningar, ej datorer och fordon',
    account_class: 5,
    account_group: '52',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Hyra av maskiner och andra tekniska anläggningar, ej datorer och fordon',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5220',
    account_name: 'Hyra av inventarier och verktyg, ej datorer och fordon',
    account_class: 5,
    account_group: '52',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Hyra av inventarier och verktyg, ej datorer och fordon',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5250',
    account_name: 'Hyra av datorer',
    account_class: 5,
    account_group: '52',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Hyra av datorer',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5290',
    account_name: 'Hyra av övriga anläggningstillgångar, ej datorer och fordon',
    account_class: 5,
    account_group: '52',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Hyra av övriga anläggningstillgångar, ej datorer och fordon',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5300',
    account_name: 'Energikostnader för drift (gruppkonto) (ej råvaror och förnödenheter)',
    account_class: 5,
    account_group: '53',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Energikostnader för drift (gruppkonto) (ej råvaror och förnödenheter)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5310',
    account_name: 'El för drift (ej råvaror och förnödenheter)',
    account_class: 5,
    account_group: '53',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Energikostnader för drift, t.ex. el för produktion.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5320',
    account_name: 'Gas för drift (ej råvaror och förnödenheter)',
    account_class: 5,
    account_group: '53',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Gas för drift (ej råvaror och förnödenheter)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5330',
    account_name: 'Eldningsolja för drift (ej råvaror och förnödenheter)',
    account_class: 5,
    account_group: '53',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Eldningsolja för drift (ej råvaror och förnödenheter)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5340',
    account_name: 'Stenkol och koks för drift (ej råvaror och förnödenheter)',
    account_class: 5,
    account_group: '53',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Stenkol och koks för drift (ej råvaror och förnödenheter)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5350',
    account_name: 'Torv, träkol, ved, m.m. för drift (ej råvaror och förnödenheter)',
    account_class: 5,
    account_group: '53',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Torv, träkol, ved, m.m. för drift (ej råvaror och förnödenheter)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5360',
    account_name: 'Bensin, fotogen och motorbrännolja för drift (ej råvaror och förnödenheter)',
    account_class: 5,
    account_group: '53',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Bensin, fotogen och motorbrännolja för drift (ej råvaror och förnödenheter)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5370',
    account_name: 'Fjärrvärme, kyla och ånga för drift (ej råvaror och förnödenheter)',
    account_class: 5,
    account_group: '53',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Fjärrvärme, kyla och ånga för drift (ej råvaror och förnödenheter)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5380',
    account_name: 'Vatten för drift (ej råvaror och förnödenheter)',
    account_class: 5,
    account_group: '53',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Vatten för drift (ej råvaror och förnödenheter)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5390',
    account_name: 'Övriga energikostnader för drift (ej råvaror och förnödenheter)',
    account_class: 5,
    account_group: '53',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga energikostnader för drift (ej råvaror och förnödenheter)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5400',
    account_name: 'Förbrukningsinventarier och förbrukningsmaterial (gruppkonto)',
    account_class: 5,
    account_group: '54',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förbrukningsinventarier och förbrukningsmaterial (gruppkonto)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5410',
    account_name: 'Förbrukningsinventarier',
    account_class: 5,
    account_group: '54',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inventarier med kort livslangd eller varde under halva prisbasbeloppet.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5411',
    account_name: 'Förbrukningsinv med en livslängd på mer än ett år',
    account_class: 5,
    account_group: '54',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förbrukningsinv med en livslängd på mer än ett år',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5412',
    account_name: 'Förbrukningsinv med en livslängd om högst ett år',
    account_class: 5,
    account_group: '54',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förbrukningsinv med en livslängd om högst ett år',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5420',
    account_name: 'Programvaror',
    account_class: 5,
    account_group: '54',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för mjukvara, prenumerationer och licenser.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5430',
    account_name: 'Transportinventarier',
    account_class: 5,
    account_group: '54',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Transportinventarier',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5440',
    account_name: 'Förbrukningsemballage',
    account_class: 5,
    account_group: '54',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förbrukningsemballage',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5460',
    account_name: 'Förbrukningsmaterial',
    account_class: 5,
    account_group: '54',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förbrukningsmaterial som inte är kontorsmaterial, t.ex. förpackningsmaterial.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5480',
    account_name: 'Arbetskläder och skyddsmaterial',
    account_class: 5,
    account_group: '54',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Arbetskläder och skyddsmaterial',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5500',
    account_name: 'Reparation och underhåll (gruppkonto)',
    account_class: 5,
    account_group: '55',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för reparation och underhåll av maskiner, inventarier och lokaler.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5510',
    account_name: 'Reparation och underhåll av maskiner och andra tekniska anläggningar',
    account_class: 5,
    account_group: '55',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Reparation och underhåll av maskiner och andra tekniska anläggningar',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5520',
    account_name: 'Reparation och underhåll av inventarier, verktyg och datorer m.m.',
    account_class: 5,
    account_group: '55',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Reparation och underhåll av inventarier, verktyg och datorer m.m.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5530',
    account_name: 'Reparation och underhåll byggnads- och markinventarier',
    account_class: 5,
    account_group: '55',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Reparation och underhåll byggnads- och markinventarier',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5550',
    account_name: 'Reparation och underhåll av förbrukningsinventarier',
    account_class: 5,
    account_group: '55',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Reparation och underhåll av förbrukningsinventarier',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5580',
    account_name: 'Underhåll och tvätt av arbetskläder',
    account_class: 5,
    account_group: '55',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Underhåll och tvätt av arbetskläder',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5590',
    account_name: 'Övriga kostnader för reparation och underhåll',
    account_class: 5,
    account_group: '55',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kostnader för reparation och underhåll',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5600',
    account_name: 'Kostnader för transportmedel (gruppkonto)',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för transportmedel (gruppkonto)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5610',
    account_name: 'Personbils- och mc-kostnader, m.m.',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Drivmedel, försäkring, reparation och övriga kostnader för företagsbilar.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5611',
    account_name: 'Drivmedel för personbilar, mc, m.m.',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Drivmedel för personbilar, mc, m.m.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5612',
    account_name: 'Försäkring och skatt för personbilar, mc, m.m.',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Försäkring och skatt för personbilar, mc, m.m.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5613',
    account_name: 'Reparation och underhåll av personbilar, mc, m.m.',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Reparation och underhåll av personbilar, mc, m.m.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5615',
    account_name: 'Leasing av personbilar, mc, m.m.',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Leasing av personbilar, mc, m.m.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5616',
    account_name: 'Trängselskatt personbilar',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Trängselskatt personbilar',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5619',
    account_name: 'Övriga kostnader för personbilar och mc, m.m.',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kostnader för personbilar och mc, m.m.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5620',
    account_name: 'Lastbils- och busskostnader, m.m.',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Lastbils- och busskostnader, m.m.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5621',
    account_name: 'Drivmedel lastbilar och bussar',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Drivmedel lastbilar och bussar',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5622',
    account_name: 'Försäkring och skatt lastbilar och bussar',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Försäkring och skatt lastbilar och bussar',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5623',
    account_name: 'Reparation och underhåll lastbilar och bussar',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Reparation och underhåll lastbilar och bussar',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5625',
    account_name: 'Leasing lastbilar och bussar',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Leasing lastbilar och bussar',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5626',
    account_name: 'Trängselskatt lastbilar och bussar',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Trängselskatt lastbilar och bussar',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5629',
    account_name: 'Övriga lastbils- och busskostnader',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga lastbils- och busskostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5630',
    account_name: 'Truckkostnader',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Truckkostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5631',
    account_name: 'Drivmedel truckar',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Drivmedel truckar',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5632',
    account_name: 'Försäkring och skatt truckar',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Försäkring och skatt truckar',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5633',
    account_name: 'Reparation och underhåll truckar',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Reparation och underhåll truckar',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5635',
    account_name: 'Leasing truckar',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Leasing truckar',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5639',
    account_name: 'Övriga kostnader för truckar',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kostnader för truckar',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5640',
    account_name: 'Kostnader för arbetsmaskiner',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för arbetsmaskiner',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5641',
    account_name: 'Drivmedel arbetsmaskiner',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Drivmedel arbetsmaskiner',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5642',
    account_name: 'Försäkring och skatt arbetsmaskiner',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Försäkring och skatt arbetsmaskiner',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5643',
    account_name: 'Reparation och underhåll arbetsmaskiner',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Reparation och underhåll arbetsmaskiner',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5645',
    account_name: 'Leasing arbetsmaskiner',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Leasing arbetsmaskiner',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5646',
    account_name: 'Trängselskatt arbetsmaskiner',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Trängselskatt arbetsmaskiner',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5649',
    account_name: 'Övriga kostnader för arbetsmaskiner',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kostnader för arbetsmaskiner',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5650',
    account_name: 'Traktorkostnader',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Traktorkostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5651',
    account_name: 'Drivmedel traktorer',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Drivmedel traktorer',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5652',
    account_name: 'Försäkring och skatt traktorer',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Försäkring och skatt traktorer',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5653',
    account_name: 'Reparation och underhåll traktorer',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Reparation och underhåll traktorer',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5655',
    account_name: 'Leasing traktorer',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Leasing traktorer',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5656',
    account_name: 'Trängselskatt traktorer',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Trängselskatt traktorer',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5659',
    account_name: 'Övriga kostnader för traktorer',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kostnader för traktorer',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5670',
    account_name: 'Kostnader för fartyg och luftfartyg',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för fartyg och luftfartyg',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5671',
    account_name: 'Drivmedel fartyg och luftfartyg',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Drivmedel fartyg och luftfartyg',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5672',
    account_name: 'Försäkring och skatt fartyg och luftfartyg',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Försäkring och skatt fartyg och luftfartyg',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5673',
    account_name: 'Reparation och underhåll fartyg och luftfartyg',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Reparation och underhåll fartyg och luftfartyg',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5675',
    account_name: 'Leasing fartyg och luftfartyg',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Leasing fartyg och luftfartyg',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5679',
    account_name: 'Övriga kostnader för fartyg och luftfartyg',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kostnader för fartyg och luftfartyg',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5680',
    account_name: 'Kostnader för rälsfordon',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för rälsfordon',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5681',
    account_name: 'Drivmedel rälsfordon',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Drivmedel rälsfordon',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5682',
    account_name: 'Försäkring och skatt rälsfordon',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Försäkring och skatt rälsfordon',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5683',
    account_name: 'Reparation och underhåll rälsfordon',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Reparation och underhåll rälsfordon',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5685',
    account_name: 'Leasing rälsfordon',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Leasing rälsfordon',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5689',
    account_name: 'Övriga kostnader för rälsfordon',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kostnader för rälsfordon',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5690',
    account_name: 'Kostnader för övriga transportmedel',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för övriga transportmedel',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5691',
    account_name: 'Drivmedel övriga transportmedel',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Drivmedel övriga transportmedel',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5692',
    account_name: 'Försäkring och skatt övriga transportmedel',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Försäkring och skatt övriga transportmedel',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5693',
    account_name: 'Reparation och underhåll övriga transportmedel',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Reparation och underhåll övriga transportmedel',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5695',
    account_name: 'Leasing övriga transportmedel',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Leasing övriga transportmedel',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5696',
    account_name: 'Trängselskatt övriga transportmedel',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Trängselskatt övriga transportmedel',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5699',
    account_name: 'Övriga kostnader för övriga transportmedel',
    account_class: 5,
    account_group: '56',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kostnader för övriga transportmedel',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5700',
    account_name: 'Frakter och transporter (gruppkonto)',
    account_class: 5,
    account_group: '57',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Frakter och transporter (gruppkonto)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5710',
    account_name: 'Frakter och försäkringar vid varudistribution',
    account_class: 5,
    account_group: '57',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för frakt och transport av varor till och från företaget.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5711',
    account_name: 'Fraktkostnader',
    account_class: 5,
    account_group: '57',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Fraktkostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5712',
    account_name: 'Försäkringar vid frakter',
    account_class: 5,
    account_group: '57',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Försäkringar vid frakter',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5720',
    account_name: 'Tull- och speditionskostnader m.m.',
    account_class: 5,
    account_group: '57',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Tull- och speditionskostnader m.m.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5721',
    account_name: 'Tullkostnader',
    account_class: 5,
    account_group: '57',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Tullkostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5722',
    account_name: 'Speditionskostnader',
    account_class: 5,
    account_group: '57',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Speditionskostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5729',
    account_name: 'Övriga tull- och speditionskostnader m.m.',
    account_class: 5,
    account_group: '57',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga tull- och speditionskostnader m.m.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5730',
    account_name: 'Arbetstransporter',
    account_class: 5,
    account_group: '57',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Arbetstransporter',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5790',
    account_name: 'Övriga kostnader för frakter och transporter',
    account_class: 5,
    account_group: '57',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kostnader för frakter och transporter',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5800',
    account_name: 'Resekostnader (gruppkonto)',
    account_class: 5,
    account_group: '58',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Tjänsteresor: tåg, flyg, taxi och övriga resekostnader.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5810',
    account_name: 'Biljetter',
    account_class: 5,
    account_group: '58',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Rese- och transportbiljetter för tjänsteresor (tåg, flyg, buss).',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5820',
    account_name: 'Hyrbilskostnader',
    account_class: 5,
    account_group: '58',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Hyrbilskostnader vid tjänsteresor.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5830',
    account_name: 'Kost och logi',
    account_class: 5,
    account_group: '58',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kost och logi',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5831',
    account_name: 'Kost och logi i Sverige',
    account_class: 5,
    account_group: '58',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kost och logi i Sverige',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5832',
    account_name: 'Kost och logi i utlandet',
    account_class: 5,
    account_group: '58',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kost och logi i utlandet',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5890',
    account_name: 'Övriga resekostnader',
    account_class: 5,
    account_group: '58',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga resekostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5900',
    account_name: 'Reklam och PR (gruppkonto)',
    account_class: 5,
    account_group: '59',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Reklam och PR (gruppkonto)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5910',
    account_name: 'Annonsering',
    account_class: 5,
    account_group: '59',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för marknadsföring, annonser, Google Ads, sociala medier och reklamkampanjer.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5920',
    account_name: 'Utomhus- och trafikreklam',
    account_class: 5,
    account_group: '59',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Utomhus- och trafikreklam',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5930',
    account_name: 'Reklamtrycksaker och direktreklam',
    account_class: 5,
    account_group: '59',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Trycksaker för marknadsföringsändamål, t.ex. broschyrer och visitkort.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5940',
    account_name: 'Utställningar och mässor',
    account_class: 5,
    account_group: '59',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Utställningar och mässor',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5950',
    account_name: 'Butiksreklam och återförsäljarreklam',
    account_class: 5,
    account_group: '59',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Butiksreklam och återförsäljarreklam',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5960',
    account_name: 'Varuprover, reklamgåvor, presentreklam och tävlingar',
    account_class: 5,
    account_group: '59',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Varuprover, reklamgåvor, presentreklam och tävlingar',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5970',
    account_name: 'Film-, radio-, TV- och Internetreklam',
    account_class: 5,
    account_group: '59',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Film-, radio-, TV- och Internetreklam',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5980',
    account_name: 'Sponsring',
    account_class: 5,
    account_group: '59',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Sponsring',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5981',
    account_name: 'Avdragsgill sponsring',
    account_class: 5,
    account_group: '59',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avdragsgill sponsring',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5982',
    account_name: 'Ej avdragsgill sponsring',
    account_class: 5,
    account_group: '59',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Ej avdragsgill sponsring',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '5990',
    account_name: 'Övriga kostnader för reklam och PR',
    account_class: 5,
    account_group: '59',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kostnader för reklam och PR',
    sru_code: '7513',
    k2_excluded: false,
  },
]
