import type { BASReferenceAccount } from '../bas-reference'

export const CLASS_4_ACCOUNTS: BASReferenceAccount[] = [
  {
    account_number: '4000',
    account_name: 'Inköp av handelsvaror (gruppkonto)',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av handelsvaror (gruppkonto)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4010',
    account_name: 'Inköp av handelsvaror i Sverige',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för inköp av varor avsedda för vidareförsäljning.',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4060',
    account_name: 'Inköp av handelsvaror i Sverige, omvänd betalningsskyldighet',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av handelsvaror i Sverige, omvänd betalningsskyldighet',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4065',
    account_name: 'Inköp av handelsvaror i Sverige, omvänd betalningsskyldighet, 25 % moms',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av handelsvaror i Sverige, omvänd betalningsskyldighet, 25 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4066',
    account_name: 'Inköp av handelsvaror i Sverige, omvänd betalningsskyldighet, 12 % moms',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av handelsvaror i Sverige, omvänd betalningsskyldighet, 12 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4067',
    account_name: 'Inköp av handelsvaror i Sverige, omvänd betalningsskyldighet, 6 % moms',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av handelsvaror i Sverige, omvänd betalningsskyldighet, 6 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4070',
    account_name: 'Inköp av handelsvaror från annat EU-land',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av handelsvaror från annat EU-land',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4075',
    account_name: 'Inköp av handelsvaror från annat EU-land, 25 % moms',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av handelsvaror från annat EU-land, 25 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4076',
    account_name: 'Inköp av handelsvaror från annat EU-land, 12 % moms',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av handelsvaror från annat EU-land, 12 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4077',
    account_name: 'Inköp av handelsvaror från annat EU-land, 6 % moms',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av handelsvaror från annat EU-land, 6 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4078',
    account_name: 'Inköp av handelsvaror från annat EU-land, momsfri',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av handelsvaror från annat EU-land, momsfri',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4080',
    account_name: 'Import av handelsvaror',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Import av handelsvaror',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4085',
    account_name: 'Import av handelsvaror, 25 % moms',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Import av handelsvaror, 25 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4086',
    account_name: 'Import av handelsvaror, 12 % moms',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Import av handelsvaror, 12 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4087',
    account_name: 'Import av handelsvaror, 6 % moms',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Import av handelsvaror, 6 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4090',
    account_name: 'Erhållna rabatter (Handelsvaror)',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Erhållna rabatter (Handelsvaror)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4091',
    account_name: 'Erhållna kassarabatter (Handelsvaror)',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Erhållna kassarabatter (Handelsvaror)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4092',
    account_name: 'Erhållna mängdrabatter (inkl. bonus) (Handelsvaror)',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Erhållna mängdrabatter (inkl. bonus) (Handelsvaror)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4099',
    account_name: 'Övriga reduktioner av inköpspriser (Handelsvaror)',
    account_class: 4,
    account_group: '40',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Övriga reduktioner av inköpspriser (Handelsvaror)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4200',
    account_name: 'Sålda handelsvaror VMB (gruppkonto)',
    account_class: 4,
    account_group: '42',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Sålda handelsvaror VMB (gruppkonto)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4210',
    account_name: 'Sålda handelsvaror VMB',
    account_class: 4,
    account_group: '42',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Sålda handelsvaror VMB',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4211',
    account_name: 'Sålda handelsvaror positiv VMB 25 %',
    account_class: 4,
    account_group: '42',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Sålda handelsvaror positiv VMB 25 %',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4212',
    account_name: 'Sålda handelsvaror negativ VMB 25 %',
    account_class: 4,
    account_group: '42',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Sålda handelsvaror negativ VMB 25 %',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4300',
    account_name: 'Inköp av råvaror och material i Sverige (gruppkonto)',
    account_class: 4,
    account_group: '43',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av råvaror och material i Sverige (gruppkonto)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4310',
    account_name: 'Inköp av råvaror och material i Sverige',
    account_class: 4,
    account_group: '43',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av råvaror och material i Sverige',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4400',
    account_name: 'Inköp av råvaror och material, tjänster m.m. i Sverige, omvänd betalningsskyldighet (gruppkonto)',
    account_class: 4,
    account_group: '44',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av råvaror och material, tjänster m.m. i Sverige, omvänd betalningsskyldighet (gruppkonto)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4410',
    account_name: 'Inköp av råvaror och material i Sverige, omvänd betalningsskyldighet',
    account_class: 4,
    account_group: '44',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av råvaror och material i Sverige, omvänd betalningsskyldighet',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4415',
    account_name: 'Inköp av råvaror och material i Sverige, omvänd betalningsskyldighet, 25 % moms',
    account_class: 4,
    account_group: '44',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av råvaror och material i Sverige, omvänd betalningsskyldighet, 25 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4416',
    account_name: 'Inköp av råvaror och material i Sverige, omvänd betalningsskyldighet, 12 % moms',
    account_class: 4,
    account_group: '44',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av råvaror och material i Sverige, omvänd betalningsskyldighet, 12 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4417',
    account_name: 'Inköp av råvaror och material i Sverige, omvänd betalningsskyldighet, 6 % moms',
    account_class: 4,
    account_group: '44',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av råvaror och material i Sverige, omvänd betalningsskyldighet, 6 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4420',
    account_name: 'Inköp av tjänster i Sverige, omvänd betalningsskyldighet',
    account_class: 4,
    account_group: '44',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av tjänster i Sverige, omvänd betalningsskyldighet',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4425',
    account_name: 'Inköp av tjänster i Sverige, omvänd betalningsskyldighet, 25 % moms',
    account_class: 4,
    account_group: '44',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av tjänster i Sverige, omvänd betalningsskyldighet, 25 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4426',
    account_name: 'Inköp av tjänster i Sverige, omvänd betalningsskyldighet, 12 % moms',
    account_class: 4,
    account_group: '44',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av tjänster i Sverige, omvänd betalningsskyldighet, 12 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4427',
    account_name: 'Inköp av tjänster i Sverige, omvänd betalningsskyldighet, 6 % moms',
    account_class: 4,
    account_group: '44',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av tjänster i Sverige, omvänd betalningsskyldighet, 6 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4500',
    account_name: 'Inköp av råvaror och material, tjänster m.m. från utlandet (gruppkonto)',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Varuinköp från utlandet (råvaror och förnödenheter).',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4510',
    account_name: 'Inköp av råvaror och material från annat EU-land',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av råvaror och material från annat EU-land',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4515',
    account_name: 'Inköp av råvaror och material från annat EU-land, 25 %',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av råvaror och material från annat EU-land, 25 %',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4516',
    account_name: 'Inköp av råvaror och material från annat EU-land, 12 %',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av råvaror och material från annat EU-land, 12 %',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4517',
    account_name: 'Inköp av råvaror och material från annat EU-land, 6 %',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av råvaror och material från annat EU-land, 6 %',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4518',
    account_name: 'Inköp av råvaror och material från annat EU-land, momsfri',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av råvaror och material från annat EU-land, momsfri',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4530',
    account_name: 'Inköp av tjänster m.m. från utlandet',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av tjänster m.m. från utlandet',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4531',
    account_name: 'Inköp av tjänster från ett land utanför EU, 25 % moms',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av tjänster från ett land utanför EU, 25 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4532',
    account_name: 'Inköp av tjänster från ett land utanför EU, 12 % moms',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av tjänster från ett land utanför EU, 12 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4533',
    account_name: 'Inköp av tjänster från ett land utanför EU, 6 % moms',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av tjänster från ett land utanför EU, 6 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4535',
    account_name: 'Inköp av tjänster från annat EU-land, 25 %',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av tjänster från annat EU-land, 25 %',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4536',
    account_name: 'Inköp av tjänster från annat EU-land, 12 %',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av tjänster från annat EU-land, 12 %',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4537',
    account_name: 'Inköp av tjänster från annat EU-land, 6 %',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av tjänster från annat EU-land, 6 %',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4538',
    account_name: 'Inköp av tjänster från annat EU-land, momsfri',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av tjänster från annat EU-land, momsfri',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4540',
    account_name: 'Import av råvaror och material',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Import av råvaror och material',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4545',
    account_name: 'Import av råvaror och material, 25 % moms',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Import av råvaror och material, 25 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4546',
    account_name: 'Import av råvaror och material, 12 % moms',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Import av råvaror och material, 12 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4547',
    account_name: 'Import av råvaror och material, 6 % moms',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Import av råvaror och material, 6 % moms',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4598',
    account_name: 'Motkonto beräknad omvänd moms',
    account_class: 4,
    account_group: '45',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Tekniskt motkonto till beräknad omvänd skattskyldighet (4415-4427, 4515-4537). Nettar ut basbeloppet i resultatrapporten samtidigt som 45xx-konton synliggör underlaget för momsdeklarationens ruta 20-24.',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4600',
    account_name: 'Inköp av tjänster, underentreprenader och legoarbeten i Sverige (gruppkonto)',
    account_class: 4,
    account_group: '46',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för arbete utfört av underleverantörer som del av leverans till kund.',
    sru_code: '7512',
    k2_excluded: false,
  },
  {
    account_number: '4610',
    account_name: 'Inköp av tjänster och underentreprenader',
    account_class: 4,
    account_group: '46',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av tjänster och underentreprenader',
    sru_code: '7512',
    k2_excluded: false,
  },
  {
    account_number: '4670',
    account_name: 'Inköp av legoarbeten',
    account_class: 4,
    account_group: '46',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inköp av legoarbeten',
    sru_code: '7512',
    k2_excluded: false,
  },
  {
    account_number: '4700',
    account_name: 'Reduktion av inköpspriser (gruppkonto)',
    account_class: 4,
    account_group: '47',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Reduktion av inköpspriser (gruppkonto)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4730',
    account_name: 'Erhållna rabatter (Råvaror och förnödenheter)',
    account_class: 4,
    account_group: '47',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Erhållna rabatter (Råvaror och förnödenheter)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4731',
    account_name: 'Erhållna kassarabatter (Råvaror och förnödenheter)',
    account_class: 4,
    account_group: '47',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Erhållna kassarabatter (Råvaror och förnödenheter)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4732',
    account_name: 'Erhållna mängdrabatter (inkl. bonus) (Råvaror och förnödenheter)',
    account_class: 4,
    account_group: '47',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Erhållna mängdrabatter (inkl. bonus) (Råvaror och förnödenheter)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4739',
    account_name: 'Övriga reduktioner av inköpspriser (Råvaror och förnödenheter)',
    account_class: 4,
    account_group: '47',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Övriga reduktioner av inköpspriser (Råvaror och förnödenheter)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4800',
    account_name: 'Andra produktionskostnader (gruppkonto)',
    account_class: 4,
    account_group: '48',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Andra produktionskostnader (gruppkonto)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4810',
    account_name: 'Kostnader för energi (Råvaror och förnödenheter)',
    account_class: 4,
    account_group: '48',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för energi (Råvaror och förnödenheter)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4820',
    account_name: 'Kostnader för drivmedel (Råvaror och förnödenheter)',
    account_class: 4,
    account_group: '48',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för drivmedel (Råvaror och förnödenheter)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4830',
    account_name: 'Kostnader för resor (Råvaror och förnödenheter)',
    account_class: 4,
    account_group: '48',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för resor (Råvaror och förnödenheter)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4840',
    account_name: 'Kostnader för hyra av utrustning (Råvaror och förnödenheter)',
    account_class: 4,
    account_group: '48',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för hyra av utrustning (Råvaror och förnödenheter)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4890',
    account_name: 'Övriga produktionskostnader (Råvaror och förnödenheter)',
    account_class: 4,
    account_group: '48',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga produktionskostnader (Råvaror och förnödenheter)',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4900',
    account_name: 'Förändring av lager (gruppkonto)',
    account_class: 4,
    account_group: '49',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Förändring av lager (gruppkonto)',
    sru_code: '7411',
    k2_excluded: false,
  },
  {
    account_number: '4910',
    account_name: 'Förändring av lager av råvaror',
    account_class: 4,
    account_group: '49',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Förändring av lager av råvaror',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4920',
    account_name: 'Förändring av lager av tillsatsmaterial och förnödenheter',
    account_class: 4,
    account_group: '49',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Förändring av lager av tillsatsmaterial och förnödenheter',
    sru_code: '7511',
    k2_excluded: false,
  },
  {
    account_number: '4940',
    account_name: 'Förändring av produkter i arbete',
    account_class: 4,
    account_group: '49',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Förändring av produkter i arbete',
    sru_code: '7411',
    k2_excluded: false,
  },
  {
    account_number: '4944',
    account_name: 'Förändring av produkter i arbete, material och utlägg',
    account_class: 4,
    account_group: '49',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Förändring av produkter i arbete, material och utlägg',
    sru_code: '7411',
    k2_excluded: false,
  },
  {
    account_number: '4945',
    account_name: 'Förändring av produkter i arbete, omkostnader',
    account_class: 4,
    account_group: '49',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Förändring av produkter i arbete, omkostnader',
    sru_code: '7411',
    k2_excluded: false,
  },
  {
    account_number: '4947',
    account_name: 'Förändring av produkter i arbete, personalkostnader',
    account_class: 4,
    account_group: '49',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Förändring av produkter i arbete, personalkostnader',
    sru_code: '7411',
    k2_excluded: false,
  },
  {
    account_number: '4950',
    account_name: 'Förändring av lager av färdiga varor',
    account_class: 4,
    account_group: '49',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Förändring av lager av färdiga varor',
    sru_code: '7411',
    k2_excluded: false,
  },
  {
    account_number: '4960',
    account_name: 'Förändring av lager av handelsvaror',
    account_class: 4,
    account_group: '49',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Förändring av lager av handelsvaror',
    sru_code: '7512',
    k2_excluded: false,
  },
  {
    account_number: '4970',
    account_name: 'Förändring av pågående arbeten, nedlagda kostnader',
    account_class: 4,
    account_group: '49',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Förändring av pågående arbeten, nedlagda kostnader',
    sru_code: '7411',
    k2_excluded: false,
  },
  {
    account_number: '4974',
    account_name: 'Förändring av pågående arbeten, material och utlägg',
    account_class: 4,
    account_group: '49',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Förändring av pågående arbeten, material och utlägg',
    sru_code: '7411',
    k2_excluded: false,
  },
  {
    account_number: '4975',
    account_name: 'Förändring av pågående arbeten, omkostnader',
    account_class: 4,
    account_group: '49',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Förändring av pågående arbeten, omkostnader',
    sru_code: '7411',
    k2_excluded: false,
  },
  {
    account_number: '4977',
    account_name: 'Förändring av pågående arbeten, personalkostnader',
    account_class: 4,
    account_group: '49',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Förändring av pågående arbeten, personalkostnader',
    sru_code: '7411',
    k2_excluded: false,
  },
  {
    account_number: '4980',
    account_name: 'Förändring av lager av värdepapper (Handelsvaror)',
    account_class: 4,
    account_group: '49',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Förändring av lager av värdepapper (Handelsvaror)',
    sru_code: '7512',
    k2_excluded: false,
  },
  {
    account_number: '4981',
    account_name: 'Sålda värdepappers anskaffningsvärde (Handelsvaror)',
    account_class: 4,
    account_group: '49',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Sålda värdepappers anskaffningsvärde (Handelsvaror)',
    sru_code: '7512',
    k2_excluded: false,
  },
  {
    account_number: '4987',
    account_name: 'Nedskrivning av värdepapper (Handelsvaror)',
    account_class: 4,
    account_group: '49',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Nedskrivning av värdepapper (Handelsvaror)',
    sru_code: '7512',
    k2_excluded: false,
  },
  {
    account_number: '4988',
    account_name: 'Återföring av nedskrivning av värdepapper (Handelsvaror)',
    account_class: 4,
    account_group: '49',
    account_type: 'expense',
    normal_balance: 'credit',
    description: 'Återföring av nedskrivning av värdepapper (Handelsvaror)',
    sru_code: '7512',
    k2_excluded: false,
  },
]
