import type { BASReferenceAccount } from '../bas-reference'

export const CLASS_2_ACCOUNTS: BASReferenceAccount[] = [
  {
    account_number: '2010',
    account_name: 'Eget kapital',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Ägarens insatta kapital i enskild firma. Visar vad ägaren har investerat.',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2011',
    account_name: 'Egna varuuttag',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'debit',
    description: 'Egna varuuttag',
    sru_code: '7301',
    k2_excluded: false,
  },
  // 2012 is deliberately absent: the official BAS kontoplan (bas.se, BAS 2026 v2)
  // has no 2012; the enskild firma equity block runs 2010, 2011, 2013, 2017,
  // 2018, 2019. "Avräkning för skatter och avgifter" as 2012 is a program
  // convention (Visma, Bokio, Björn Lundén), not standard BAS; owner taxes are
  // booked as eget uttag on 2013. Verified against the primary source in #1409.
  {
    account_number: '2013',
    account_name: 'Övriga egna uttag',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'debit',
    description: 'Pengar som ägaren av en enskild firma tar ut privat ur företaget.',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2017',
    account_name: 'Årets kapitaltillskott',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Tillskott från ägaren under löpande räkenskapsår i enskild firma.',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2018',
    account_name: 'Övriga egna insättningar',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Pengar som ägaren sätter in privat i företaget (enskild firma).',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2019',
    account_name: 'Årets resultat, delägare 1',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Årets vinst eller förlust i enskild firma.',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2020',
    account_name: 'Eget kapital',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Eget kapital',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2021',
    account_name: 'Egna varuuttag',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'debit',
    description: 'Egna varuuttag',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2023',
    account_name: 'Övriga egna uttag',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'debit',
    description: 'Övriga egna uttag',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2027',
    account_name: 'Årets kapitaltillskott',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Årets kapitaltillskott',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2028',
    account_name: 'Övriga egna insättningar',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Övriga egna insättningar',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2029',
    account_name: 'Årets resultat, delägare 2',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Årets resultat, delägare 2',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2030',
    account_name: 'Eget kapital',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Eget kapital',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2031',
    account_name: 'Egna varuuttag',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'debit',
    description: 'Egna varuuttag',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2033',
    account_name: 'Övriga egna uttag',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'debit',
    description: 'Övriga egna uttag',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2037',
    account_name: 'Årets kapitaltillskott',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Årets kapitaltillskott',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2038',
    account_name: 'Övriga egna insättningar',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Övriga egna insättningar',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2039',
    account_name: 'Årets resultat, delägare 3',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Årets resultat, delägare 3',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2040',
    account_name: 'Eget kapital',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Eget kapital',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2041',
    account_name: 'Egna varuuttag',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'debit',
    description: 'Egna varuuttag',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2043',
    account_name: 'Övriga egna uttag',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'debit',
    description: 'Övriga egna uttag',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2047',
    account_name: 'Årets kapitaltillskott',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Årets kapitaltillskott',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2048',
    account_name: 'Övriga egna insättningar',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Övriga egna insättningar',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2049',
    account_name: 'Årets resultat, delägare 4',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Årets resultat, delägare 4',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2050',
    account_name: 'Avsättning till expansionsfond',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Avsättning till expansionsfond',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2060',
    account_name: 'Eget kapital i ideella föreningar, stiftelser och registrerade trossamfund',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Eget kapital i ideella föreningar, stiftelser och registrerade trossamfund',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2061',
    account_name: 'Kapital/stiftelsekapital/grundkapital',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Kapital/stiftelsekapital/grundkapital',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2064',
    account_name: 'Ackumulerat realisationsresultat',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Ackumulerat realisationsresultat',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2065',
    account_name: 'Fond för verkligt värde',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Fond för verkligt värde',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2066',
    account_name: 'Värdesäkringsfond',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Värdesäkringsfond',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2067',
    account_name: 'Balanserat överskott eller underskott',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Balanserat överskott eller underskott',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2068',
    account_name: 'Överskott eller underskott från föregående år',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Överskott eller underskott från föregående år',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2069',
    account_name: 'Årets resultat',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Årets resultat',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2070',
    account_name: 'Ändamålsbestämda medel',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Ändamålsbestämda medel',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2071',
    account_name: 'Ändamål 1',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Ändamål 1',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2072',
    account_name: 'Ändamål 2',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Ändamål 2',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2080',
    account_name: 'Bundet eget kapital',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Bundet eget kapital',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2081',
    account_name: 'Aktiekapital',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Det registrerade aktiekapitalet i ett aktiebolag.',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2082',
    account_name: 'Ej registrerat aktiekapital',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Ej registrerat aktiekapital',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2083',
    account_name: 'Medlemsinsatser',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Medlemsinsatser',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2084',
    account_name: 'Förlagsinsatser',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Förlagsinsatser',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2085',
    account_name: 'Uppskrivningsfond',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Fond för uppskrivning av anläggningstillgångar i aktiebolag.',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2086',
    account_name: 'Reservfond',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Bundet eget kapital i aktiebolag. Ska vara minst 20% av aktiekapitalet (aldre regler).',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2087',
    account_name: 'Bunden överkursfond',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Bunden överkursfond',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2088',
    account_name: 'Fond för yttre underhåll',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Fond för yttre underhåll',
    sru_code: '7301',
    k2_excluded: false,
  },
  {
    account_number: '2089',
    account_name: 'Fond för utvecklingsutgifter',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Fond för utvecklingsutgifter',
    sru_code: '7301',
    k2_excluded: true,
  },
  {
    account_number: '2090',
    account_name: 'Fritt eget kapital',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Fritt eget kapital',
    sru_code: '7302',
    k2_excluded: false,
  },
  {
    account_number: '2091',
    account_name: 'Balanserad vinst eller förlust',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'debit',
    description: 'Ackumulerade vinster eller förluster från tidigare är som inte delats ut.',
    sru_code: '7302',
    k2_excluded: false,
  },
  {
    account_number: '2092',
    account_name: 'Mottagna/lämnade koncernbidrag',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Mottagna/lämnade koncernbidrag',
    sru_code: '7302',
    k2_excluded: true,
  },
  {
    account_number: '2093',
    account_name: 'Erhållna aktieägartillskott',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Tillskott från aktieägare som inte är lån, ökar fritt eget kapital.',
    sru_code: '7302',
    k2_excluded: false,
  },
  {
    account_number: '2094',
    account_name: 'Egna aktier',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Egna aktier',
    sru_code: '7302',
    k2_excluded: false,
  },
  {
    account_number: '2095',
    account_name: 'Fusionsresultat',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Fusionsresultat',
    sru_code: '7302',
    k2_excluded: false,
  },
  {
    account_number: '2096',
    account_name: 'Fond för verkligt värde',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Fond för verkligt värde',
    sru_code: '7302',
    k2_excluded: true,
  },
  {
    account_number: '2097',
    account_name: 'Fri överkursfond',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Fri överkursfond',
    sru_code: '7302',
    k2_excluded: false,
  },
  {
    account_number: '2098',
    account_name: 'Vinst eller förlust från föregående år',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Föregående års resultat innan det fördelats till balanserat resultat eller utdelning.',
    sru_code: '7302',
    k2_excluded: false,
  },
  {
    account_number: '2099',
    account_name: 'Årets resultat',
    account_class: 2,
    account_group: '20',
    account_type: 'equity',
    normal_balance: 'credit',
    description: 'Vinst eller förlust för innevarande räkenskapsår (aktiebolag).',
    sru_code: '7302',
    k2_excluded: false,
  },
  {
    account_number: '2110',
    account_name: 'Periodiseringsfonder',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfonder',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2120',
    account_name: 'Periodiseringsfond 2020',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2020',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2121',
    account_name: 'Periodiseringsfond 2021',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2021',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2122',
    account_name: 'Periodiseringsfond 2022',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2022',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2123',
    account_name: 'Periodiseringsfond 2023',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2023',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2124',
    account_name: 'Periodiseringsfond 2024',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2024',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2125',
    account_name: 'Periodiseringsfond 2025',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2025',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2126',
    account_name: 'Periodiseringsfond 2026',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2026',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2127',
    account_name: 'Periodiseringsfond 2027',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2027',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2129',
    account_name: 'Periodiseringsfond 2019',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2019',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2130',
    account_name: 'Periodiseringsfond 2020: nr 2',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2020: nr 2',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2131',
    account_name: 'Periodiseringsfond 2021: nr 2',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2021: nr 2',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2132',
    account_name: 'Periodiseringsfond 2022: nr 2',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2022: nr 2',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2133',
    account_name: 'Periodiseringsfond 2023: nr 2',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2023: nr 2',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2134',
    account_name: 'Periodiseringsfond 2024: nr 2',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2024: nr 2',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2135',
    account_name: 'Periodiseringsfond 2025: nr 2',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2025: nr 2',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2136',
    account_name: 'Periodiseringsfond 2026: nr 2',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2026: nr 2',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2137',
    account_name: 'Periodiseringsfond 2027: nr 2',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2027: nr 2',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2139',
    account_name: 'Periodiseringsfond 2019: nr 2',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Periodiseringsfond avsatt taxeringsår 2019: nr 2',
    sru_code: '7321',
    k2_excluded: false,
  },
  {
    account_number: '2150',
    account_name: 'Ackumulerade överavskrivningar',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Skattemässiga överavskrivningar på inventarier utöver plan (periodiseringsfond).',
    sru_code: '7322',
    k2_excluded: false,
  },
  {
    account_number: '2151',
    account_name: 'Ackumulerade överavskrivningar på immateriella anläggningstillgångar',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Ackumulerade överavskrivningar på immateriella anläggningstillgångar',
    sru_code: '7322',
    k2_excluded: false,
  },
  {
    account_number: '2152',
    account_name: 'Ackumulerade överavskrivningar på byggnader och markanläggningar',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Ackumulerade överavskrivningar på byggnader och markanläggningar',
    sru_code: '7322',
    k2_excluded: false,
  },
  {
    account_number: '2153',
    account_name: 'Ackumulerade överavskrivningar på maskiner respektive inventarier',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Ackumulerade överavskrivningar på maskiner respektive inventarier',
    sru_code: '7322',
    k2_excluded: false,
  },
  {
    account_number: '2160',
    account_name: 'Ersättningsfond',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Ersättningsfond',
    sru_code: '7323',
    k2_excluded: false,
  },
  {
    account_number: '2161',
    account_name: 'Ersättningsfond maskiner och inventarier',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Ersättningsfond maskiner och inventarier',
    sru_code: '7323',
    k2_excluded: false,
  },
  {
    account_number: '2162',
    account_name: 'Ersättningsfond byggnader och markanläggningar',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Ersättningsfond byggnader och markanläggningar',
    sru_code: '7323',
    k2_excluded: false,
  },
  {
    account_number: '2164',
    account_name: 'Ersättningsfond för djurlager i jordbruk och renskötsel',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Ersättningsfond för djurlager i jordbruk och renskötsel',
    sru_code: '7323',
    k2_excluded: false,
  },
  {
    account_number: '2190',
    account_name: 'Övriga obeskattade reserver',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Övriga obeskattade reserver',
    sru_code: '7323',
    k2_excluded: false,
  },
  {
    account_number: '2196',
    account_name: 'Lagerreserv',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Lagerreserv',
    sru_code: '7323',
    k2_excluded: false,
  },
  {
    account_number: '2199',
    account_name: 'Övriga obeskattade reserver',
    account_class: 2,
    account_group: '21',
    account_type: 'untaxed_reserves',
    normal_balance: 'credit',
    description: 'Övriga obeskattade reserver',
    sru_code: '7323',
    k2_excluded: false,
  },
  {
    account_number: '2210',
    account_name: 'Avsättningar för pensioner enligt tryggandelagen',
    account_class: 2,
    account_group: '22',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Avsättningar för pensioner enligt tryggandelagen',
    sru_code: '7331',
    k2_excluded: false,
  },
  {
    account_number: '2220',
    account_name: 'Avsättningar för garantier',
    account_class: 2,
    account_group: '22',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Avsättningar för garantier',
    sru_code: '7333',
    k2_excluded: false,
  },
  {
    account_number: '2230',
    account_name: 'Övriga avsättningar för pensioner och liknande förpliktelser',
    account_class: 2,
    account_group: '22',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga avsättningar för pensioner och liknande förpliktelser',
    sru_code: '7332',
    k2_excluded: false,
  },
  {
    account_number: '2240',
    account_name: 'Avsättningar för uppskjutna skatter',
    account_class: 2,
    account_group: '22',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Avsättningar för uppskjutna skatter',
    sru_code: '7333',
    k2_excluded: true,
  },
  {
    account_number: '2250',
    account_name: 'Övriga avsättningar för skatter',
    account_class: 2,
    account_group: '22',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga avsättningar för skatter',
    sru_code: '7333',
    k2_excluded: false,
  },
  {
    account_number: '2252',
    account_name: 'Avsättningar för tvistiga skatter',
    account_class: 2,
    account_group: '22',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Avsättningar för tvistiga skatter',
    sru_code: '7333',
    k2_excluded: false,
  },
  {
    account_number: '2253',
    account_name: 'Avsättningar särskild löneskatt, deklarationspost',
    account_class: 2,
    account_group: '22',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Avsättningar särskild löneskatt, deklarationspost',
    sru_code: '7333',
    k2_excluded: false,
  },
  {
    account_number: '2290',
    account_name: 'Övriga avsättningar',
    account_class: 2,
    account_group: '22',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga avsättningar',
    sru_code: '7333',
    k2_excluded: false,
  },
  {
    account_number: '2310',
    account_name: 'Obligations- och förlagslån',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Långfristiga lån från banker och kreditinstitut.',
    sru_code: '7350',
    k2_excluded: false,
  },
  {
    account_number: '2320',
    account_name: 'Konvertibla lån och liknande',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Konvertibla lån och liknande',
    sru_code: '7350',
    k2_excluded: false,
  },
  {
    account_number: '2321',
    account_name: 'Konvertibla lån',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Konvertibla lån',
    sru_code: '7350',
    k2_excluded: false,
  },
  {
    account_number: '2322',
    account_name: 'Lån förenade med optionsrätt',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Lån förenade med optionsrätt',
    sru_code: '7350',
    k2_excluded: false,
  },
  {
    account_number: '2323',
    account_name: 'Vinstandelslån',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Vinstandelslån',
    sru_code: '7350',
    k2_excluded: false,
  },
  {
    account_number: '2324',
    account_name: 'Kapitalandelslån',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Kapitalandelslån',
    sru_code: '7350',
    k2_excluded: false,
  },
  {
    account_number: '2330',
    account_name: 'Kontokredit',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Kontokredit',
    sru_code: '7351',
    k2_excluded: false,
  },
  {
    account_number: '2340',
    account_name: 'Byggnadskreditiv',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Byggnadskreditiv',
    sru_code: '7352',
    k2_excluded: false,
  },
  {
    account_number: '2350',
    account_name: 'Andra långfristiga skulder till kreditinstitut',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Långfristiga skulder utöver banklån, t.ex. lån från privatpersoner.',
    sru_code: '7352',
    k2_excluded: false,
  },
  {
    account_number: '2351',
    account_name: 'Fastighetslån, långfristig del',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Fastighetslån, långfristig del',
    sru_code: '7352',
    k2_excluded: false,
  },
  {
    account_number: '2355',
    account_name: 'Långfristiga lån i utländsk valuta från kreditinstitut',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Långfristiga lån i utländsk valuta från kreditinstitut',
    sru_code: '7352',
    k2_excluded: false,
  },
  {
    account_number: '2359',
    account_name: 'Övriga långfristiga lån från kreditinstitut',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga långfristiga lån från kreditinstitut',
    sru_code: '7352',
    k2_excluded: false,
  },
  {
    account_number: '2360',
    account_name: 'Långfristiga skulder till koncernföretag',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Långfristiga skulder till koncernföretag',
    sru_code: '7353',
    k2_excluded: false,
  },
  {
    account_number: '2361',
    account_name: 'Långfristiga skulder till moderföretag',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Långfristiga skulder till moderföretag',
    sru_code: '7353',
    k2_excluded: false,
  },
  {
    account_number: '2362',
    account_name: 'Långfristiga skulder till dotterföretag',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Långfristiga skulder till dotterföretag',
    sru_code: '7353',
    k2_excluded: false,
  },
  {
    account_number: '2363',
    account_name: 'Långfristiga skulder till andra koncernföretag',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Långfristiga skulder till andra koncernföretag',
    sru_code: '7353',
    k2_excluded: false,
  },
  {
    account_number: '2370',
    account_name: 'Långfristiga skulder till intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Långfristiga skulder till intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i',
    sru_code: '7353',
    k2_excluded: false,
  },
  {
    account_number: '2371',
    account_name: 'Långfristiga skulder till intresseföretag',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Långfristiga skulder till intresseföretag',
    sru_code: '7353',
    k2_excluded: false,
  },
  {
    account_number: '2372',
    account_name: 'Långfristiga skulder till gemensamt styrda företag',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Långfristiga skulder till gemensamt styrda företag',
    sru_code: '7353',
    k2_excluded: false,
  },
  {
    account_number: '2373',
    account_name: 'Långfristiga skulder till övriga företag som det finns ett ägarintresse i',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Långfristiga skulder till övriga företag som det finns ett ägarintresse i',
    sru_code: '7354',
    k2_excluded: false,
  },
  {
    account_number: '2390',
    account_name: 'Övriga långfristiga skulder',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga långfristiga skulder',
    sru_code: '7354',
    k2_excluded: false,
  },
  {
    account_number: '2391',
    account_name: 'Avbetalningskontrakt, långfristig del',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Avbetalningskontrakt, långfristig del',
    sru_code: '7354',
    k2_excluded: false,
  },
  {
    account_number: '2392',
    account_name: 'Villkorliga långfristiga skulder',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Villkorliga långfristiga skulder',
    sru_code: '7354',
    k2_excluded: false,
  },
  {
    account_number: '2393',
    account_name: 'Lån från närstående personer, långfristig del',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Lån från närstående personer, långfristig del',
    sru_code: '7354',
    k2_excluded: false,
  },
  {
    account_number: '2394',
    account_name: 'Långfristiga leverantörskrediter',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Långfristiga leverantörskrediter',
    sru_code: '7354',
    k2_excluded: false,
  },
  {
    account_number: '2395',
    account_name: 'Andra långfristiga lån i utländsk valuta',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Andra långfristiga lån i utländsk valuta',
    sru_code: '7354',
    k2_excluded: false,
  },
  {
    account_number: '2396',
    account_name: 'Derivat',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Derivat',
    sru_code: '7354',
    k2_excluded: false,
  },
  {
    account_number: '2397',
    account_name: 'Mottagna depositioner, långfristiga',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Mottagna depositioner, långfristiga',
    sru_code: '7354',
    k2_excluded: false,
  },
  {
    account_number: '2399',
    account_name: 'Övriga långfristiga skulder',
    account_class: 2,
    account_group: '23',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga långfristiga skulder',
    sru_code: '7354',
    k2_excluded: false,
  },
  {
    account_number: '2410',
    account_name: 'Andra kortfristiga låneskulder till kreditinstitut',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Banklån och checkkrediter med återbetalningstid under 12 månader.',
    sru_code: '7361',
    k2_excluded: false,
  },
  {
    account_number: '2411',
    account_name: 'Kortfristiga lån från kreditinstitut',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Kortfristiga lån från kreditinstitut',
    sru_code: '7361',
    k2_excluded: false,
  },
  {
    account_number: '2412',
    account_name: 'Byggnadskreditiv, kortfristig del',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Byggnadskreditiv, kortfristig del',
    sru_code: '7361',
    k2_excluded: false,
  },
  {
    account_number: '2417',
    account_name: 'Kortfristig del av långfristiga skulder till kreditinstitut',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Kortfristig del av långfristiga skulder till kreditinstitut',
    sru_code: '7361',
    k2_excluded: false,
  },
  {
    account_number: '2419',
    account_name: 'Övriga kortfristiga skulder till kreditinstitut',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga kortfristiga skulder till kreditinstitut',
    sru_code: '7361',
    k2_excluded: false,
  },
  {
    account_number: '2420',
    account_name: 'Förskott från kunder',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Förskott från kunder',
    sru_code: '7362',
    k2_excluded: false,
  },
  {
    account_number: '2421',
    account_name: 'Ej inlösta presentkort',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Ej inlösta presentkort',
    sru_code: '7362',
    k2_excluded: false,
  },
  {
    account_number: '2429',
    account_name: 'Övriga förskott från kunder',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga förskott från kunder',
    sru_code: '7362',
    k2_excluded: false,
  },
  {
    account_number: '2430',
    account_name: 'Pågående arbeten',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Pågående arbeten',
    sru_code: '7363',
    k2_excluded: false,
  },
  {
    account_number: '2431',
    account_name: 'Pågående arbeten, fakturering',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Pågående arbeten, fakturering',
    sru_code: '7363',
    k2_excluded: false,
  },
  {
    account_number: '2438',
    account_name: 'Pågående arbeten, nedlagda kostnader',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Pågående arbeten, nedlagda kostnader',
    sru_code: '7363',
    k2_excluded: false,
  },
  {
    account_number: '2439',
    account_name: 'Beräknad förändring av pågående arbeten',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Beräknad förändring av pågående arbeten',
    sru_code: '7363',
    k2_excluded: false,
  },
  {
    account_number: '2440',
    account_name: 'Leverantörsskulder',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Pengar som företaget är skyldigt leverantörer för mottagna fakturor.',
    sru_code: '7365',
    k2_excluded: false,
  },
  {
    account_number: '2441',
    account_name: 'Leverantörsskulder',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Leverantörsskulder',
    sru_code: '7365',
    k2_excluded: false,
  },
  {
    account_number: '2443',
    account_name: 'Konsignationsskulder',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Konsignationsskulder',
    sru_code: '7365',
    k2_excluded: false,
  },
  {
    account_number: '2445',
    account_name: 'Tvistiga leverantörsskulder',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Tvistiga leverantörsskulder',
    sru_code: '7365',
    k2_excluded: false,
  },
  {
    account_number: '2448',
    account_name: 'Ej reskontraförda leverantörsskulder',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Ej reskontraförda leverantörsskulder',
    sru_code: '7365',
    k2_excluded: true,
  },
  {
    account_number: '2450',
    account_name: 'Fakturerad men ej upparbetad intäkt',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Fakturerad men ej upparbetad intäkt',
    sru_code: '7364',
    k2_excluded: false,
  },
  {
    account_number: '2460',
    account_name: 'Leverantörsskulder till koncernföretag',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Leverantörsskulder till koncernföretag',
    sru_code: '7367',
    k2_excluded: false,
  },
  {
    account_number: '2461',
    account_name: 'Leverantörsskulder till moderföretag',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Leverantörsskulder till moderföretag',
    sru_code: '7367',
    k2_excluded: false,
  },
  {
    account_number: '2462',
    account_name: 'Leverantörsskulder till dotterföretag',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Leverantörsskulder till dotterföretag',
    sru_code: '7367',
    k2_excluded: false,
  },
  {
    account_number: '2463',
    account_name: 'Leverantörsskulder till andra koncernföretag',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Leverantörsskulder till andra koncernföretag',
    sru_code: '7367',
    k2_excluded: false,
  },
  {
    account_number: '2470',
    account_name: 'Leverantörsskulder till intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Leverantörsskulder till intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i',
    sru_code: '7367',
    k2_excluded: false,
  },
  {
    account_number: '2471',
    account_name: 'Leverantörsskulder till intresseföretag',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Leverantörsskulder till intresseföretag',
    sru_code: '7367',
    k2_excluded: false,
  },
  {
    account_number: '2472',
    account_name: 'Leverantörsskulder till gemensamt styrda företag',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Leverantörsskulder till gemensamt styrda företag',
    sru_code: '7367',
    k2_excluded: false,
  },
  {
    account_number: '2473',
    account_name: 'Leverantörsskulder till övriga företag som det finns ett ägarintresse i',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Leverantörsskulder till övriga företag som det finns ett ägarintresse i',
    sru_code: '7367',
    k2_excluded: false,
  },
  {
    account_number: '2480',
    account_name: 'Kontokredit, kortfristig',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Kontokredit, kortfristig',
    sru_code: '7360',
    k2_excluded: false,
  },
  {
    account_number: '2490',
    account_name: 'Övriga kortfristiga skulder till kreditinstitut, kunder och leverantörer',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga kortfristiga skulder till kreditinstitut, kunder och leverantörer',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2491',
    account_name: 'Avräkning spelarrangörer',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Avräkning spelarrangörer',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2492',
    account_name: 'Växelskulder',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Växelskulder',
    sru_code: '7366',
    k2_excluded: false,
  },
  {
    account_number: '2499',
    account_name: 'Andra övriga kortfristiga skulder',
    account_class: 2,
    account_group: '24',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Andra övriga kortfristiga skulder',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2510',
    account_name: 'Skatteskulder',
    account_class: 2,
    account_group: '25',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Skulder till Skatteverket för preliminär skatt och andra skattebetalningar.',
    sru_code: '7368',
    k2_excluded: false,
  },
  {
    account_number: '2512',
    account_name: 'Beräknad inkomstskatt',
    account_class: 2,
    account_group: '25',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Beräknad inkomstskatt',
    sru_code: '7368',
    k2_excluded: false,
  },
  {
    account_number: '2513',
    account_name: 'Beräknad fastighetsskatt/fastighetsavgift',
    account_class: 2,
    account_group: '25',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Beräknad fastighetsskatt/fastighetsavgift',
    sru_code: '7368',
    k2_excluded: false,
  },
  {
    account_number: '2514',
    account_name: 'Beräknad särskild löneskatt på pensionskostnader',
    account_class: 2,
    account_group: '25',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Beräknad särskild löneskatt på pensionskostnader',
    sru_code: '7368',
    k2_excluded: false,
  },
  {
    account_number: '2515',
    account_name: 'Beräknad avkastningsskatt',
    account_class: 2,
    account_group: '25',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Beräknad avkastningsskatt',
    sru_code: '7368',
    k2_excluded: false,
  },
  {
    account_number: '2517',
    account_name: 'Beräknad utländsk skatt',
    account_class: 2,
    account_group: '25',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Beräknad utländsk skatt',
    sru_code: '7368',
    k2_excluded: false,
  },
  {
    account_number: '2518',
    account_name: 'Betald F-skatt',
    account_class: 2,
    account_group: '25',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Betald F-skatt',
    sru_code: '7368',
    k2_excluded: false,
  },
  {
    account_number: '2610',
    account_name: 'Utgående moms, 25 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms, 25 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2611',
    account_name: 'Utgående moms på försäljning inom Sverige, 25 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Moms du tar ut på försäljning med 25% momssats. Ska betalas in till Skatteverket.',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2612',
    account_name: 'Utgående moms på egna uttag, 25 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms på egna uttag, 25 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2613',
    account_name: 'Utgående moms för uthyrning, 25 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms för uthyrning, 25 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2614',
    account_name: 'Utgående moms omvänd betalskyldighet, 25 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms vid omvänd skattskyldighet (reverse charge) med 25% momssats.',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2615',
    account_name: 'Utgående moms import av varor, 25 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms import av varor, 25 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2616',
    account_name: 'Utgående moms VMB 25 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms VMB 25 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2618',
    account_name: 'Vilande utgående moms, 25 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Vilande utgående moms, 25 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2620',
    account_name: 'Utgående moms, 12 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms, 12 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2621',
    account_name: 'Utgående moms på försäljning inom Sverige, 12 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Moms på försäljning med 12% momssats, t.ex. livsmedel och hotell.',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2622',
    account_name: 'Utgående moms på egna uttag, 12 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms på egna uttag, 12 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2623',
    account_name: 'Utgående moms för uthyrning, 12 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms för uthyrning, 12 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2624',
    account_name: 'Utgående moms omvänd betalningsskyldighet 12 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms vid omvänd skattskyldighet (reverse charge) med 12% momssats.',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2625',
    account_name: 'Utgående moms import av varor, 12 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms import av varor, 12 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2626',
    account_name: 'Utgående moms VMB 12 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms VMB 12 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2628',
    account_name: 'Vilande utgående moms, 12 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Vilande utgående moms, 12 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2630',
    account_name: 'Utgående moms, 6 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms, 6 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2631',
    account_name: 'Utgående moms på försäljning inom Sverige, 6 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Moms på försäljning med 6% momssats, t.ex. böcker och tidningar.',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2632',
    account_name: 'Utgående moms på egna uttag, 6 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms på egna uttag, 6 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2633',
    account_name: 'Utgående moms för uthyrning, 6 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms för uthyrning, 6 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2634',
    account_name: 'Utgående moms omvänd betalningsskyldighet, 6 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms vid omvänd skattskyldighet (reverse charge) med 6% momssats.',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2635',
    account_name: 'Utgående moms import av varor, 6 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms import av varor, 6 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2636',
    account_name: 'Utgående moms VMB 6 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms VMB 6 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2638',
    account_name: 'Vilande utgående moms, 6 %',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Vilande utgående moms, 6 %',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2640',
    account_name: 'Ingående moms',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Ingående moms',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2641',
    account_name: 'Debiterad ingående moms',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Moms på inköp som företaget har ratt att dra av. Minskar momsskulden.',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2642',
    account_name: 'Debiterad ingående moms i anslutning till frivillig betalningsskyldighet',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Debiterad ingående moms i anslutning till frivillig betalningsskyldighet',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2645',
    account_name: 'Beräknad ingående moms på förvärv från utlandet',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Ingående moms som beräknas själv vid inköp från andra EU-länder (omvänd skattskyldighet).',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2646',
    account_name: 'Ingående moms på uthyrning',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Ingående moms på uthyrning',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2647',
    account_name: 'Ingående moms omvänd betalningsskyldighet varor och tjänster i Sverige',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Ingående moms omvänd betalningsskyldighet varor och tjänster i Sverige',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2648',
    account_name: 'Vilande ingående moms',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Vilande ingående moms',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2649',
    account_name: 'Ingående moms, blandad verksamhet',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Ingående moms, blandad verksamhet',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2650',
    account_name: 'Redovisningskonto för moms',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Samlingskonto dit moms bokfors efter varje momsperiod, utgor nettot att betala till Skatteverket.',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2660',
    account_name: 'Punktskatter',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Punktskatter',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2670',
    account_name: 'Utgående moms på försäljning inom EU, OSS',
    account_class: 2,
    account_group: '26',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utgående moms på försäljning inom EU, OSS',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2710',
    account_name: 'Personalskatt',
    account_class: 2,
    account_group: '27',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Innehållen preliminärskatt på anställda löner som ska betalas till Skatteverket.',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2730',
    account_name: 'Lagstadgade sociala avgifter och särskild löneskatt',
    account_class: 2,
    account_group: '27',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Lagstadgade sociala avgifter och särskild löneskatt',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2731',
    account_name: 'Avräkning lagstadgade sociala avgifter',
    account_class: 2,
    account_group: '27',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Arbetsgivaravgifter redovisade men ännu inte inbetalda till Skatteverket.',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2732',
    account_name: 'Avräkning särskild löneskatt',
    account_class: 2,
    account_group: '27',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Avräkning särskild löneskatt',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2740',
    account_name: 'Avtalade sociala avgifter',
    account_class: 2,
    account_group: '27',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Avtalade sociala avgifter',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2750',
    account_name: 'Utmätning i lön m.m.',
    account_class: 2,
    account_group: '27',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Utmätning i lön m.m.',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2760',
    account_name: 'Semestermedel',
    account_class: 2,
    account_group: '27',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Semestermedel',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2761',
    account_name: 'Avräkning semesterlöner',
    account_class: 2,
    account_group: '27',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Avräkning semesterlöner',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2762',
    account_name: 'Semesterlönekassa',
    account_class: 2,
    account_group: '27',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Semesterlönekassa',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2790',
    account_name: 'Övriga löneavdrag',
    account_class: 2,
    account_group: '27',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga löneavdrag',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2791',
    account_name: 'Personalens intressekonto',
    account_class: 2,
    account_group: '27',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Personalens intressekonto',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2792',
    account_name: 'Lönsparande',
    account_class: 2,
    account_group: '27',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Lönsparande',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2793',
    account_name: 'försäkringspremier',
    account_class: 2,
    account_group: '27',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'försäkringspremier',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2794',
    account_name: 'Fackföreningsavgifter',
    account_class: 2,
    account_group: '27',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Fackföreningsavgifter',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2795',
    account_name: 'Mätnings- och granskningsarvoden',
    account_class: 2,
    account_group: '27',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Mätnings- och granskningsarvoden',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2799',
    account_name: 'Övriga löneavdrag',
    account_class: 2,
    account_group: '27',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga löneavdrag',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2810',
    account_name: 'Avräkning för factoring och belånade kontraktsfordringar',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Avräkning för factoring och belånade kontraktsfordringar',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2811',
    account_name: 'Avräkning för factoring',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Avräkning för factoring',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2812',
    account_name: 'Avräkning för belånade kontraktsfordringar',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Avräkning för belånade kontraktsfordringar',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2820',
    account_name: 'Kortfristiga skulder till anställda',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Skulder till anställda för t.ex. reseförskott eller utlägg.',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2821',
    account_name: 'Löneskulder',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Löneskulder',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2822',
    account_name: 'Reseräkningar',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Reseräkningar',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2823',
    account_name: 'Tantiem, gratifikationer',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Tantiem, gratifikationer',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2829',
    account_name: 'Övriga kortfristiga skulder till anställda',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga kortfristiga skulder till anställda',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2830',
    account_name: 'Avräkning för annans räkning',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Avräkning för annans räkning',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2840',
    account_name: 'Kortfristiga låneskulder',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Kortfristiga låneskulder',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2841',
    account_name: 'Kortfristig del av långfristiga skulder',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Kortfristig del av långfristiga skulder',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2849',
    account_name: 'Övriga kortfristiga låneskulder',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga kortfristiga låneskulder',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2850',
    account_name: 'Avräkning för skatter och avgifter (skattekonto)',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Avräkning för skatter och avgifter (skattekonto)',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2852',
    account_name: 'Anståndsbelopp för moms, arbetsgivaravgifter och personalskatt',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Anståndsbelopp för moms, arbetsgivaravgifter och personalskatt',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2860',
    account_name: 'Kortfristiga skulder till koncernföretag',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Kortfristiga skulder till koncernföretag',
    sru_code: '7367',
    k2_excluded: false,
  },
  {
    account_number: '2861',
    account_name: 'Kortfristiga skulder till moderföretag',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Kortfristiga skulder till moderföretag',
    sru_code: '7367',
    k2_excluded: false,
  },
  {
    account_number: '2862',
    account_name: 'Kortfristiga skulder till dotterföretag',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Kortfristiga skulder till dotterföretag',
    sru_code: '7367',
    k2_excluded: false,
  },
  {
    account_number: '2863',
    account_name: 'Kortfristiga skulder till andra koncernföretag',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Kortfristiga skulder till andra koncernföretag',
    sru_code: '7367',
    k2_excluded: false,
  },
  {
    account_number: '2870',
    account_name: 'Kortfristiga skulder till intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Kortfristiga skulder till intresseföretag, gemensamt styrda företag och övriga företag som det finns ett ägarintresse i',
    sru_code: '7367',
    k2_excluded: false,
  },
  {
    account_number: '2871',
    account_name: 'Kortfristiga skulder till intresseföretag',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Kortfristiga skulder till intresseföretag',
    sru_code: '7367',
    k2_excluded: false,
  },
  {
    account_number: '2872',
    account_name: 'Kortfristiga skulder till gemensamt styrda företag',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Kortfristiga skulder till gemensamt styrda företag',
    sru_code: '7367',
    k2_excluded: false,
  },
  {
    account_number: '2873',
    account_name: 'Kortfristiga skulder till övriga företag som det finns ett ägarintresse i',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Kortfristiga skulder till övriga företag som det finns ett ägarintresse i',
    sru_code: '7367',
    k2_excluded: false,
  },
  {
    account_number: '2880',
    account_name: 'Skuld erhållna bidrag',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Skuld erhållna bidrag',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2890',
    account_name: 'Övriga kortfristiga skulder',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga kortfristiga skulder',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2891',
    account_name: 'Skulder under indrivning',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Skulder under indrivning',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2892',
    account_name: 'Inre reparationsfond/underhållsfond',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Inre reparationsfond/underhållsfond',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2893',
    account_name: 'Skulder till närstående personer, kortfristig del',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Pengar som aktiebolaget lånat av sina ägare. Vanligt i mindre AB.',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2895',
    account_name: 'Derivat (kortfristiga skulder)',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Derivat (kortfristiga skulder)',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2897',
    account_name: 'Mottagna depositioner, kortfristiga',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Mottagna depositioner, kortfristiga',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2898',
    account_name: 'Outtagen vinstutdelning',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Beslutad men ännu ej utbetald aktieutdelning.',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2899',
    account_name: 'Övriga kortfristiga skulder',
    account_class: 2,
    account_group: '28',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga kortfristiga skulder',
    sru_code: '7369',
    k2_excluded: false,
  },
  {
    account_number: '2910',
    account_name: 'Upplupna löner',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Löner som intjänats men ännu inte utbetalats vid periodens slut.',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2911',
    account_name: 'Löneskulder',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Löneskulder',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2912',
    account_name: 'Ackordsöverskott',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Ackordsöverskott',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2919',
    account_name: 'Övriga upplupna löner',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga upplupna löner',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2920',
    account_name: 'Upplupna semesterlöner',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Skuld för intjänade men inte uttagna semesterdagar.',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2930',
    account_name: 'Upplupna pensionskostnader',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Upplupna pensionskostnader',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2931',
    account_name: 'Upplupna pensionsutbetalningar',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Upplupna pensionsutbetalningar',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2940',
    account_name: 'Upplupna lagstadgade sociala och andra avgifter',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Arbetsgivaravgifter som hänför sig till redovisade löner men ännu inte betalats.',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2941',
    account_name: 'Beräknade upplupna lagstadgade sociala avgifter',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Beräknade upplupna lagstadgade sociala avgifter',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2942',
    account_name: 'Beräknad upplupen särskild löneskatt',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Beräknad upplupen särskild löneskatt',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2943',
    account_name: 'Beräknad upplupen särskild löneskatt på pensionskostnader, deklarationspost',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Beräknad upplupen särskild löneskatt på pensionskostnader, deklarationspost',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2944',
    account_name: 'Beräknad upplupen avkastningsskatt på pensionskostnader',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Beräknad upplupen avkastningsskatt på pensionskostnader',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2950',
    account_name: 'Upplupna avtalade sociala avgifter',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Upplupna avtalade sociala avgifter',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2951',
    account_name: 'Upplupna avtalade arbetsmarknadsförsäkringar',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Upplupna avtalade arbetsmarknadsförsäkringar',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2959',
    account_name: 'Upplupna avtalade pensionsförsäkringsavgifter, deklarationspost',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Upplupna avtalade pensionsförsäkringsavgifter, deklarationspost',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2960',
    account_name: 'Upplupna räntekostnader',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Räntekostnader som upplupit men inte fakturerats eller betalats ännu.',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2970',
    account_name: 'Förutbetalda intäkter',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Förutbetalda intäkter',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2971',
    account_name: 'Förutbetalda hyresintäkter',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Förutbetalda hyresintäkter',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2972',
    account_name: 'Förutbetalda medlemsavgifter',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Förutbetalda medlemsavgifter',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2979',
    account_name: 'Övriga förutbetalda intäkter',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga förutbetalda intäkter',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2980',
    account_name: 'Upplupna avtalskostnader',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Upplupna avtalskostnader',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2990',
    account_name: 'Övriga upplupna kostnader och förutbetalda intäkter',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Upplupna kostnader och förutbetalda intäkter som inte ryms i andra underkonton.',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2991',
    account_name: 'Beräknat arvode för bokslut',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Beräknat arvode för bokslut',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2992',
    account_name: 'Beräknat arvode för revision',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Beräknat arvode för revision',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2993',
    account_name: 'Ospecificerad skuld till leverantörer',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Ospecificerad skuld till leverantörer',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2995',
    account_name: 'Ej ankomna leverantörsfakturor',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Ej ankomna leverantörsfakturor',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2998',
    account_name: 'Övriga upplupna kostnader och förutbetalda intäkter',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'Övriga upplupna kostnader och förutbetalda intäkter',
    sru_code: '7370',
    k2_excluded: false,
  },
  {
    account_number: '2999',
    account_name: 'OBS-konto',
    account_class: 2,
    account_group: '29',
    account_type: 'liability',
    normal_balance: 'credit',
    description: 'OBS-konto',
    sru_code: '7370',
    k2_excluded: false,
  },
]
