import type { BASReferenceAccount } from '../bas-reference'

export const CLASS_6_ACCOUNTS: BASReferenceAccount[] = [
  {
    account_number: '6000',
    account_name: 'Övriga försäljningskostnader (gruppkonto)',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga försäljningskostnader (gruppkonto)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6010',
    account_name: 'Kataloger, prislistor m.m.',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kataloger, prislistor m.m.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6020',
    account_name: 'Egna facktidskrifter',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Egna facktidskrifter',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6030',
    account_name: 'Speciella orderkostnader',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Speciella orderkostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6040',
    account_name: 'Kontokortsavgifter',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kontokortsavgifter',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6050',
    account_name: 'Försäljningsprovisioner',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Försäljningsprovisioner',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6055',
    account_name: 'Franchisekostnader',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Franchisekostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6059',
    account_name: 'Övriga försäljningsprovisionskostnader',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga försäljningsprovisionskostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6060',
    account_name: 'Kreditförsäljningskostnader',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kreditförsäljningskostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6061',
    account_name: 'Kreditupplysning',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kreditupplysning',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6062',
    account_name: 'Inkasso och KFM-avgifter',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inkasso och KFM-avgifter',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6063',
    account_name: 'Kreditförsäkringspremier',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kreditförsäkringspremier',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6064',
    account_name: 'Factoringavgifter',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Factoringavgifter',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6069',
    account_name: 'Övriga kreditförsäljningskostnader',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kreditförsäljningskostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6070',
    account_name: 'Representation',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Representation',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6071',
    account_name: 'Representation, avdragsgill',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avdragsgill representation vid affarsrelaterade maltider och evenemang (max 300 kr/person).',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6072',
    account_name: 'Representation, ej avdragsgill',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Representation som överstiger avdragsgilla beloppet. Inte skattemässigt avdragsgill.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6080',
    account_name: 'Bankgarantier',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Bankgarantier',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6090',
    account_name: 'Övriga försäljningskostnader',
    account_class: 6,
    account_group: '60',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga försäljningskostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6100',
    account_name: 'Kontorsmateriel och trycksaker (gruppkonto)',
    account_class: 6,
    account_group: '61',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kontorsmateriel och trycksaker (gruppkonto)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6110',
    account_name: 'Kontorsmateriel',
    account_class: 6,
    account_group: '61',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Pennor, papper, toner, USB-minnen och övriga kontorsförnödenheter.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6150',
    account_name: 'Trycksaker',
    account_class: 6,
    account_group: '61',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Trycksaker för internt bruk, t.ex. blanketter och formulär.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6200',
    account_name: 'Tele, data och post (gruppkonto)',
    account_class: 6,
    account_group: '62',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Tele, data och post (gruppkonto)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6210',
    account_name: 'Telekommunikation',
    account_class: 6,
    account_group: '62',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Telekommunikation',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6211',
    account_name: 'Fast telefoni',
    account_class: 6,
    account_group: '62',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnad för fast telefoni och telefonabonnemang.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6212',
    account_name: 'Mobiltelefon',
    account_class: 6,
    account_group: '62',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Mobilabonnemang och samtalskostnader för företagets mobiler.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6219',
    account_name: 'Övriga kostnader för telekommunikation',
    account_class: 6,
    account_group: '62',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga kostnader för telekommunikation',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6230',
    account_name: 'Datakommunikation',
    account_class: 6,
    account_group: '62',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Bredband, internetabonnemang, domäner, hosting och molntjänster.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6250',
    account_name: 'Porto',
    account_class: 6,
    account_group: '62',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Porto, frimärken och kostnader för postutskick.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6290',
    account_name: 'Övriga tele-, data- och postkostnader',
    account_class: 6,
    account_group: '62',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga tele-, data- och postkostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6300',
    account_name: 'Företagsförsäkringar och övriga riskkostnader (gruppkonto)',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Företagsförsäkringar och övriga riskkostnader (gruppkonto)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6310',
    account_name: 'Företagsförsäkringar',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Premiekostnader för företagets försäkringar, t.ex. ansvars- och egendomsförsäkring.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6320',
    account_name: 'Självrisker vid skada',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Självrisker vid skada',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6330',
    account_name: 'Förluster i pågående arbeten',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förluster i pågående arbeten',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6340',
    account_name: 'Lämnade skadestånd',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Lämnade skadestånd',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6341',
    account_name: 'Lämnade skadestånd, avdragsgilla',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Lämnade skadestånd, avdragsgilla',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6342',
    account_name: 'Lämnade skadestånd, ej avdragsgilla',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Lämnade skadestånd, ej avdragsgilla',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6350',
    account_name: 'Förluster på kundfordringar',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förluster på kundfordringar',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6351',
    account_name: 'Konstaterade förluster på kundfordringar',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Konstaterade förluster på kundfordringar',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6352',
    account_name: 'Befarade förluster på kundfordringar',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Befarade förluster på kundfordringar',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6360',
    account_name: 'Garantikostnader',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för garantier och garantiavsättningar.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6361',
    account_name: 'Förändring av garantiavsättning',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förändring av garantiavsättning',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6362',
    account_name: 'Faktiska garantikostnader',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Faktiska garantikostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6370',
    account_name: 'Kostnader för bevakning och larm',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för bevakning och larm',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6380',
    account_name: 'Förluster på övriga kortfristiga fordringar',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förluster på övriga kortfristiga fordringar',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6390',
    account_name: 'Övriga riskkostnader',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga riskkostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6391',
    account_name: 'Övriga riskkostnader, avdragsgilla',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga riskkostnader, avdragsgilla',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6392',
    account_name: 'Övriga riskkostnader, ej avdragsgilla',
    account_class: 6,
    account_group: '63',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga riskkostnader, ej avdragsgilla',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6400',
    account_name: 'Förvaltningskostnader (gruppkonto)',
    account_class: 6,
    account_group: '64',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Förvaltningskostnader (gruppkonto)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6420',
    account_name: 'Ersättningar till revisor',
    account_class: 6,
    account_group: '64',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Ersättningar till revisor',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6421',
    account_name: 'Revision',
    account_class: 6,
    account_group: '64',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Revision',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6422',
    account_name: 'Revisonsverksamhet utöver revision',
    account_class: 6,
    account_group: '64',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Revisonsverksamhet utöver revision',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6423',
    account_name: 'Skatterådgivning: revisor',
    account_class: 6,
    account_group: '64',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Skatterådgivning: revisor',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6424',
    account_name: 'Övriga tjänster: revisor',
    account_class: 6,
    account_group: '64',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga tjänster: revisor',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6430',
    account_name: 'Management fees',
    account_class: 6,
    account_group: '64',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Management fees',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6440',
    account_name: 'Årsredovisning och delårsrapporter',
    account_class: 6,
    account_group: '64',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Årsredovisning och delårsrapporter',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6450',
    account_name: 'Bolagsstämma/års- eller föreningsstämma',
    account_class: 6,
    account_group: '64',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Bolagsstämma/års- eller föreningsstämma',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6490',
    account_name: 'Övriga förvaltningskostnader',
    account_class: 6,
    account_group: '64',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga förvaltningskostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6500',
    account_name: 'Övriga externa tjänster (gruppkonto)',
    account_class: 6,
    account_group: '65',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga externa tjänster (gruppkonto)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6510',
    account_name: 'Mätningskostnader',
    account_class: 6,
    account_group: '65',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för mätning och besiktning.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6520',
    account_name: 'Ritnings- och kopieringskostnader',
    account_class: 6,
    account_group: '65',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Ritnings- och kopieringskostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6530',
    account_name: 'Redovisningstjänster',
    account_class: 6,
    account_group: '65',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avgifter till bokföringsbyrå eller redovisningskonsult.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6540',
    account_name: 'IT-tjänster',
    account_class: 6,
    account_group: '65',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för extern IT-support, konsultation och drifttjänster.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6550',
    account_name: 'Konsultarvoden',
    account_class: 6,
    account_group: '65',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Arvode till externa konsulter för rådgivning och specialisttjänster.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6551',
    account_name: 'Arkitekttjänster',
    account_class: 6,
    account_group: '65',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Arkitekttjänster',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6552',
    account_name: 'Teknisk provning och analys',
    account_class: 6,
    account_group: '65',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Teknisk provning och analys',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6553',
    account_name: 'Tekniska konsulttjänster',
    account_class: 6,
    account_group: '65',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Tekniska konsulttjänster',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6554',
    account_name: 'Finansiell- och övrig ekonomisk rådgivning',
    account_class: 6,
    account_group: '65',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Finansiell- och övrig ekonomisk rådgivning',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6555',
    account_name: 'Skatterådgivning inkl. insolvens- och konkursförv.',
    account_class: 6,
    account_group: '65',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Skatterådgivning inkl. insolvens- och konkursförv.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6556',
    account_name: 'Köpta tjänster avseende forskning och utveckling',
    account_class: 6,
    account_group: '65',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Köpta tjänster avseende forskning och utveckling',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6559',
    account_name: 'Övriga konsultarvoden',
    account_class: 6,
    account_group: '65',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga konsultarvoden',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6560',
    account_name: 'Serviceavgifter till branschorganisationer',
    account_class: 6,
    account_group: '65',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Serviceavtal och underhållskostnader för utrustning och system.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6570',
    account_name: 'Bankkostnader',
    account_class: 6,
    account_group: '65',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avgifter för banktjänster, betalförmedling, Swish och kortinlösen.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6580',
    account_name: 'Advokat- och rättegångskostnader',
    account_class: 6,
    account_group: '65',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Advokat- och rättegångskostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6590',
    account_name: 'Övriga externa tjänster',
    account_class: 6,
    account_group: '65',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga externa tjänster',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6700',
    account_name: 'Särskilt för ideella föreningar och stiftelser (gruppkonto)',
    account_class: 6,
    account_group: '67',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Särskilt för ideella föreningar och stiftelser (gruppkonto)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6710',
    account_name: 'Lämnade bidrag',
    account_class: 6,
    account_group: '67',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Lämnade bidrag',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6800',
    account_name: 'Inhyrd personal (gruppkonto)',
    account_class: 6,
    account_group: '68',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inhyrd personal (gruppkonto)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6810',
    account_name: 'Inhyrd produktionspersonal',
    account_class: 6,
    account_group: '68',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inhyrd produktionspersonal',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6820',
    account_name: 'Inhyrd lagerpersonal',
    account_class: 6,
    account_group: '68',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inhyrd lagerpersonal',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6830',
    account_name: 'Inhyrd transportpersonal',
    account_class: 6,
    account_group: '68',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inhyrd transportpersonal',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6840',
    account_name: 'Inhyrd kontors- och ekonomipersonal',
    account_class: 6,
    account_group: '68',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inhyrd kontors- och ekonomipersonal',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6850',
    account_name: 'Inhyrd IT-personal',
    account_class: 6,
    account_group: '68',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inhyrd IT-personal',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6860',
    account_name: 'Inhyrd marknads- och försäljningspersonal',
    account_class: 6,
    account_group: '68',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inhyrd marknads- och försäljningspersonal',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6870',
    account_name: 'Inhyrd restaurang- och butikspersonal',
    account_class: 6,
    account_group: '68',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inhyrd restaurang- och butikspersonal',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6880',
    account_name: 'Inhyrda företagsledare',
    account_class: 6,
    account_group: '68',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Inhyrda företagsledare',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6890',
    account_name: 'Övrig inhyrd personal',
    account_class: 6,
    account_group: '68',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övrig inhyrd personal',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6900',
    account_name: 'Övriga externa kostnader (gruppkonto)',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga externa kostnader (gruppkonto)',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6910',
    account_name: 'Licensavgifter och royalties',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Licensavgifter och royalties',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6920',
    account_name: 'Kostnader för egna patent',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för egna patent',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6930',
    account_name: 'Kostnader för varumärken m.m.',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kostnader för varumärken m.m.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6940',
    account_name: 'Kontroll-, provnings- och stämpelavgifter',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Kontroll-, provnings- och stämpelavgifter',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6950',
    account_name: 'Tillsynsavgifter myndigheter',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Tillsynsavgifter myndigheter',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6970',
    account_name: 'Tidningar, facklitteratur, m.m.',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Prenumerationer på tidningar, tidskrifter och branschpublikationer.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6980',
    account_name: 'Föreningsavgifter',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Avgifter till foreningar och branschorganisationer.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6981',
    account_name: 'Föreningsavgifter, avdragsgilla',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Föreningsavgifter, avdragsgilla',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6982',
    account_name: 'Föreningsavgifter, ej avdragsgilla',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Föreningsavgifter, ej avdragsgilla',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6990',
    account_name: 'Övriga externa kostnader',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Övriga externa kostnader',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6991',
    account_name: 'Övriga externa kostnader, avdragsgilla',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Diverse externa kostnader som inte passar in under andra konton men är avdragsgilla.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6992',
    account_name: 'Övriga externa kostnader, ej avdragsgilla',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Externa kostnader som inte är skattemässigt avdragsgilla, t.ex. böter och förseningsavgifter.',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6993',
    account_name: 'Lämnade bidrag och gåvor',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Lämnade bidrag och gåvor',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6996',
    account_name: 'Betald utländsk inkomstskatt',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Betald utländsk inkomstskatt',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6997',
    account_name: 'Obetald utländsk inkomstskatt',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Obetald utländsk inkomstskatt',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6998',
    account_name: 'Utländsk moms',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Utländsk moms',
    sru_code: '7513',
    k2_excluded: false,
  },
  {
    account_number: '6999',
    account_name: 'Ingående moms, blandad verksamhet',
    account_class: 6,
    account_group: '69',
    account_type: 'expense',
    normal_balance: 'debit',
    description: 'Ingående moms, blandad verksamhet',
    sru_code: '7513',
    k2_excluded: false,
  },
]
