export function buildSandboxCustomers(userId: string, companyId: string) {
  return [
    {
      user_id: userId,
      company_id: companyId,
      name: 'Björk & Partner AB',
      customer_type: 'swedish_business',
      email: 'faktura@bjorkpartner.se',
      org_number: '5566778899',
      vat_number: 'SE556677889901',
      vat_number_validated: true,
      address_line1: 'Storgatan 10',
      postal_code: '111 44',
      city: 'Stockholm',
      country: 'SE',
      default_payment_terms: 30,
    },
    {
      user_id: userId,
      company_id: companyId,
      name: 'Schmidt GmbH',
      customer_type: 'eu_business',
      email: 'billing@schmidt.de',
      org_number: 'HRB 12345',
      vat_number: 'DE123456789',
      vat_number_validated: true,
      address_line1: 'Hauptstraße 5',
      postal_code: '10115',
      city: 'Berlin',
      country: 'DE',
      default_payment_terms: 30,
    },
    {
      user_id: userId,
      company_id: companyId,
      name: 'Anna Lindström',
      customer_type: 'individual',
      email: 'anna.lindstrom@example.com',
      vat_number_validated: false,
      address_line1: 'Lillgatan 3',
      postal_code: '222 33',
      city: 'Malmö',
      country: 'SE',
      default_payment_terms: 30,
    },
  ]
}
