-- pending_operations.operation_type: add the wave-1 setup operations of the
-- operation registry (src/lib/operations): cash accounts, fiscal years,
-- chart-of-accounts delete/activate/deactivate, the company tax profile and
-- the bookkeeping lock. Each is staged by its generated MCP tool and approval
-- runs the same operation the v1 endpoint runs. Same expand pattern as
-- 20260925220000: the full list is re-stated (keep it in step with
-- types/index.ts PendingOperationType) and the new values appended; the
-- VALIDATE runs in the next migration.
--
-- pg-test: tests/pg/pending-operations-op-type-audit.pg.test.ts.
ALTER TABLE public.pending_operations
  DROP CONSTRAINT IF EXISTS pending_operations_operation_type_check;

ALTER TABLE public.pending_operations
  ADD CONSTRAINT pending_operations_operation_type_check
  CHECK (operation_type IN (
    'categorize_transaction',
    'create_customer',
    'create_invoice',
    'mark_invoice_paid',
    'send_invoice',
    'mark_invoice_sent',
    'match_transaction_invoice',
    'close_period',
    'lock_period',
    'unlock_period',
    'set_opening_balances',
    'run_year_end',
    'post_kontantmetod_cutoff',
    'run_currency_revaluation',
    'import_sie',
    'explain_voucher_gap',
    'uncategorize_transaction',
    'approve_supplier_invoice',
    'credit_supplier_invoice',
    'credit_invoice',
    'convert_invoice',
    'delete_draft_invoice',
    'create_transaction',
    'attach_document_to_transaction',
    'create_voucher',
    'correct_entry',
    'reverse_entry',
    'create_supplier',
    'create_supplier_invoice_from_inbox',
    'post_annual_depreciation',
    'link_invoice_voucher',
    'undo_sie_import',
    'match_batch_allocate',
    'bulk_book_transactions',
    'create_salary_run',
    'generate_agi',
    'link_transaction_journal_entry',
    'link_supplier_invoice_voucher',
    'submit_vat_declaration',
    'submit_agi',
    'create_article',
    'update_article',
    'bulk_book_inbox_items',
    'create_dimension_value',
    'retag_line_dimensions',
    'link_document_to_voucher',
    'update_payslip_line',
    'set_run_salary',
    'update_salary_run',
    'register_absence',
    'create_employee',
    'update_employee',
    'set_employee_opening_balances',
    'vacation_year_close',
    'create_account',
    'update_account',
    'set_voucher_note',
    'book_salary_run',
    'delete_absence',
    'update_company_settings',
    'update_customer',
    'update_invoice',
    'create_recurring_schedule',
    'update_recurring_schedule',
    'log_mileage_trip',
    'book_mileage_period',
    'link_documents_to_vouchers',
    'reconciliation_match',
    'reconciliation_unmatch',
    'reconciliation_signoff',
    'reconciliation_residual',
    'book_skattekonto_row',
    'book_skattekonto_rows',
    'ignore_transaction',
    'create_sales_order',
    'transition_sales_order',
    'register_sales_order_delivery',
    'create_invoice_from_sales_order',
    'settle_rot_rut_payout',
    'create_asset',
    'update_asset',
    'dispose_asset',
    'arkiv_propose_fact',
    'link_rot_rut_payout_voucher',
    'create_dimension',
    'update_dimension',
    'delete_dimension',
    'create_cash_account',
    'update_cash_account',
    'set_primary_cash_account',
    'set_invoice_payee_default',
    'create_fiscal_period',
    'update_fiscal_period',
    'close_fiscal_period_external',
    'reopen_fiscal_period_external',
    'delete_account',
    'activate_accounts',
    'deactivate_accounts',
    'update_company_tax_profile',
    'update_bookkeeping_lock'
  )) NOT VALID;
